local L = LibStub("AceLocale-3.0"):GetLocale("APR")

APR.RouteQuestStepList["Forever-Starting-Zone-Dwarf-Gnome"] = {
    label = L["Forever - Starting Zone Dwarf / Gnome"],
    expansion = APR.EXPANSIONS.Forever,
    gameVersion = APR.GAME_VERSIONS.Forever,
    category = APR.CATEGORIES.Leveling,
    mapID = 1426,
    conditions = { Race = { APR.RACES.Dwarf, APR.RACES.Gnome }, Faction = "Alliance" },
    nextRoute = {
        { route = "Forever-Generated-Alliance-Loch-Modan-Hunter", conditions = { Race = APR.RACES.Dwarf, Class = APR.Classes.Hunter } },
        { route = "Forever-Generated-Alliance-Elwynn-Forest",     conditions = { ClassNot = APR.Classes.Hunter } },
    },
    prefab = { [APR.PREFAB_TYPES.Leveling] = { index = 1 }, [APR.PREFAB_TYPES.Speedrun] = { index = 1 }, [APR.PREFAB_TYPES.StartingZone] = 1 },
    steps = {
        {
            PickUp = { 179 },
            Coord = { y = -6217, x = 328.5 },
            Zone = 1426,
            _index = 1,
        },
        {
            Qpart = { [179] = { 1 } },
            Coord = { y = -6302.1, x = 300.5 },
            Range = 30,
            Zone = 1426,
            _index = 2,
        },
        {
            Done = { 179 },
            Coord = { y = -6216.9, x = 329.1 },
            Zone = 1426,
            _index = 3,
        },
        {
            PickUp = { 233 },
            Coord = { y = -6216.9, x = 329.1 },
            Zone = 1426,
            _index = 4,
        },
        {
            PickUp = { 3108 },
            Coord = { y = -6216.9, x = 329.1 },
            Range = 15,
            Class = { "HUNTER" },
            Race = { "Dwarf" },
            Zone = 1426,
            _index = 5,
        },
        {
            PickUp = { 3114 },
            Coord = { y = -6216.9, x = 329.1 },
            Range = 15,
            Class = { "MAGE" },
            Race = { "Gnome" },
            Zone = 1426,
            _index = 6,
        },
        {
            PickUp = { 3107 },
            Coord = { y = -6216.9, x = 329.1 },
            Range = 15,
            Class = { "PALADIN" },
            Race = { "Dwarf" },
            Zone = 1426,
            _index = 7,
        },
        {
            PickUp = { 3110 },
            Coord = { y = -6216.9, x = 329.1 },
            Range = 15,
            Class = { "PRIEST" },
            Race = { "Dwarf" },
            Zone = 1426,
            _index = 8,
        },
        {
            PickUp = { 98574 },
            Coord = { y = -6216, x = 328.5 },
            Range = 15,
            Class = { "PRIEST" },
            Race = { "Gnome" },
            Zone = 1426,
            _index = 9,
        },
        {
            PickUp = { 3113 },
            Coord = { y = -6216.9, x = 329.1 },
            Range = 15,
            Class = { "ROGUE" },
            Race = { "Gnome" },
            Zone = 1426,
            _index = 10,
        },
        {
            PickUp = { 3109 },
            Coord = { y = -6216.9, x = 329.1 },
            Range = 15,
            Class = { "ROGUE" },
            Race = { "Dwarf" },
            Zone = 1426,
            _index = 11,
        },
        {
            PickUp = { 98581 },
            Coord = { y = -6216.9, x = 329.1 },
            Range = 15,
            Class = { "SHAMAN" },
            Race = { "Dwarf" },
            Zone = 1426,
            _index = 12,
        },
        {
            PickUp = { 3115 },
            Coord = { y = -6216.9, x = 329.1 },
            Range = 15,
            Class = { "WARLOCK" },
            Race = { "Gnome" },
            Zone = 1426,
            _index = 13,
        },
        {
            PickUp = { 3112 },
            Coord = { y = -6216.9, x = 329.1 },
            Range = 15,
            Class = { "WARRIOR" },
            Race = { "Gnome" },
            Zone = 1426,
            _index = 14,
        },
        {
            PickUp = { 3106 },
            Coord = { y = -6216.9, x = 329.1 },
            Range = 15,
            Class = { "WARRIOR" },
            Race = { "Dwarf" },
            Zone = 1426,
            _index = 15,
        },
        {
            PickUp = { 170 },
            Coord = { y = -6217.7, x = 337.4 },
            Range = 15,
            Zone = 1426,
            _index = 16,
        },
        {
            SellItems = { junk = true },
            Coord = { y = -6229, x = 322.3 },
            Class = { "MAGE", "PRIEST", "SHAMAN", "WARLOCK" },
            Zone = 1426,
            _index = 17,
        },
        {
            BuyMerchant = { { quantity = 10, itemID = 159, questID = 170 } },
            Coord = { y = -6229, x = 322.3 },
            Class = { "MAGE", "PRIEST", "SHAMAN", "WARLOCK" },
            ItemCount = { itemID = 159, count = 10, operator = "<" },
            Money = { copper = 50, operator = ">=" },
            Zone = 1426,
            _index = 18,
        },
        {
            SellItems = { junk = true },
            Coord = { y = -6226.74, x = 320.3 },
            Class = "HUNTER",
            Race = "Dwarf",
            Zone = 1426,
            _index = 19,
        },
        {
            BuyMerchant = { { itemID = 2516, quantity = 600 } },
            Coord = { y = -6226.74, x = 320.3 },
            Class = "HUNTER",
            ItemCount = { count = 600, itemID = 2516, operator = "<" },
            Money = { copper = 30, operator = ">=" },
            Race = "Dwarf",
            Zone = 1426,
            _index = 20,
        },
        {
            Qpart = { [170] = { 2 } },
            Coord = { y = -6236.5, x = 467 },
            Range = 30,
            Zone = 1426,
            _index = 21,
        },
        {
            Qpart = { [170] = { 1 } },
            Coord = { y = -6353.3, x = 361.7 },
            Range = 30,
            Zone = 1426,
            _index = 22,
        },
        {
            Done = { 170 },
            Coord = { y = -6218.7, x = 338.7 },
            RaidIcon = 713,
            Zone = 1426,
            _index = 23,
        },
        {
            Grind = 3,
            Coord = { y = -6353.3, x = 361.7 },
            Range = 40,
            Zone = 1426,
            _index = 24,
        },
        {
            Waypoint = 233,
            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1426, 28.792, 68.804),
            Range = 12,
            Zone = 1426,
            _index = 25,
        },
        {
            Waypoint = 233,
            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1426, 28.939, 68.387),
            Range = 12,
            Zone = 1426,
            _index = 26,
        },
        {
            PickUp = { 3361 },
            Coord = { y = -6099.4, x = 399.7 },
            RaidIcon = 8416,
            Zone = 1426,
            _index = 27,
        },
        {
            Done = { 3107 },
            Coord = { y = -6120.5, x = 382.1 },
            Range = 15,
            RaidIcon = 926,
            Class = "PALADIN",
            Race = "Dwarf",
            Zone = 1426,
            _index = 28,
        },
        {
            LearnSkill = { spellIDs = { 19740 }, npcID = 926 },
            Coord = { y = -6120.5, x = 382.1 },
            RaidIcon = 926,
            Class = "PALADIN",
            MinLevel = 4,
            Race = "Dwarf",
            Zone = 1426,
            _index = 29,
        },
        {
            Done = { 3108 },
            Coord = { y = -6091.5, x = 365.3 },
            Range = 15,
            RaidIcon = 895,
            Class = "HUNTER",
            Race = "Dwarf",
            Zone = 1426,
            _index = 30,
        },
        {
            LearnSkill = { allAvailable = true, npcID = 895 },
            Coord = { y = -6091.5, x = 365.3 },
            RaidIcon = 895,
            Class = "HUNTER",
            MinLevel = 1,
            Race = "Dwarf",
            Zone = 1426,
            _index = 31,
        },
        {
            Done = { 3112 },
            Coord = { y = -6084.8, x = 382.5 },
            Range = 15,
            RaidIcon = 912,
            Class = "WARRIOR",
            Race = "Gnome",
            Zone = 1426,
            _index = 32,
        },
        {
            LearnSkill = { spellIDs = { 6673 }, npcID = 912 },
            Coord = { y = -6084.8, x = 382.5 },
            RaidIcon = 912,
            Class = "WARRIOR",
            MinLevel = 1,
            Race = "Gnome",
            Zone = 1426,
            _index = 33,
        },
        {
            Done = { 3106 },
            Coord = { y = -6084.8, x = 382.5 },
            Range = 15,
            RaidIcon = 912,
            Class = "WARRIOR",
            Race = "Dwarf",
            Zone = 1426,
            _index = 34,
        },
        {
            LearnSkill = { spellIDs = { 6673 }, npcID = 912 },
            Coord = { y = -6084.8, x = 382.5 },
            RaidIcon = 912,
            Class = "WARRIOR",
            MinLevel = 1,
            Race = "Dwarf",
            Zone = 1426,
            _index = 35,
        },
        {
            Done = { 3113 },
            Coord = { y = -6093.6, x = 405.1 },
            Range = 15,
            RaidIcon = 916,
            Class = "ROGUE",
            Race = "Gnome",
            Zone = 1426,
            _index = 36,
        },
        {
            LearnSkill = { spellIDs = { 1784 }, npcID = 916 },
            Coord = { y = -6093.6, x = 405.1 },
            RaidIcon = 916,
            Class = "ROGUE",
            MinLevel = 1,
            Race = "Gnome",
            Zone = 1426,
            _index = 37,
        },
        {
            Done = { 3109 },
            Coord = { y = -6093.6, x = 405.1 },
            Range = 15,
            RaidIcon = 916,
            Class = "ROGUE",
            Race = "Dwarf",
            Zone = 1426,
            _index = 38,
        },
        {
            LearnSkill = { spellIDs = { 1784 }, npcID = 916 },
            Coord = { y = -6093.6, x = 405.1 },
            RaidIcon = 916,
            Class = "ROGUE",
            MinLevel = 1,
            Race = "Dwarf",
            Zone = 1426,
            _index = 39,
        },
        {
            Done = { 3114 },
            Coord = { y = -6056.5, x = 388.3 },
            Range = 15,
            RaidIcon = 944,
            Class = "MAGE",
            Race = "Gnome",
            Zone = 1426,
            _index = 40,
        },
        {
            LearnSkill = { spellIDs = { 1459 }, npcID = 944 },
            Coord = { y = -6056.5, x = 388.3 },
            RaidIcon = 944,
            Class = "MAGE",
            MinLevel = 1,
            Race = "Gnome",
            Zone = 1426,
            _index = 41,
        },
        {
            Done = { 3110 },
            Coord = { y = -6057.5, x = 392.9 },
            Range = 15,
            RaidIcon = 837,
            Class = "PRIEST",
            Race = "Dwarf",
            Zone = 1426,
            _index = 42,
        },
        {
            LearnSkill = { allAvailable = true, npcID = 837 },
            Coord = { y = -6057.5, x = 392.9 },
            RaidIcon = 837,
            Class = "PRIEST",
            MinLevel = 1,
            Race = "Dwarf",
            Zone = 1426,
            _index = 43,
        },
        {
            Done = { 98574 },
            Coord = { y = -6057.5, x = 392.9 },
            Range = 15,
            RaidIcon = 837,
            Class = "PRIEST",
            Race = "Gnome",
            Zone = 1426,
            _index = 44,
        },
        {
            LearnSkill = { allAvailable = true, npcID = 837 },
            Coord = { y = -6057.5, x = 392.9 },
            RaidIcon = 837,
            Class = "PRIEST",
            MinLevel = 1,
            Race = "Gnome",
            Zone = 1426,
            _index = 45,
        },
        {
            Done = { 98581 },
            Coord = { y = -6050.4, x = 384 },
            Range = 15,
            RaidIcon = 257446,
            Class = "SHAMAN",
            Race = "Dwarf",
            Zone = 1426,
            _index = 46,
        },
        {
            LearnSkill = { spellIDs = { 8017 }, npcID = 257446 },
            Coord = { y = -6050.4, x = 384 },
            RaidIcon = 257446,
            Class = "SHAMAN",
            MinLevel = 1,
            Race = "Dwarf",
            Zone = 1426,
            _index = 47,
        },
        {
            PickUp = { 94373 },
            Coord = { y = -6050.6, x = 383.5 },
            Range = 15,
            RaidIcon = 257446,
            Class = "SHAMAN",
            Race = "Dwarf",
            Zone = 1426,
            _index = 48,
        },
        {
            Done = { 3115 },
            Coord = { y = -6051.7, x = 393.6 },
            Range = 15,
            RaidIcon = 460,
            Class = "WARLOCK",
            Race = "Gnome",
            Zone = 1426,
            _index = 49,
        },
        {
            LearnSkill = { spellIDs = { 348 }, npcID = 460 },
            Coord = { y = -6051.7, x = 393.6 },
            RaidIcon = 460,
            Class = "WARLOCK",
            MinLevel = 1,
            Race = "Gnome",
            Zone = 1426,
            _index = 50,
        },
        {
            PickUp = { 1599 },
            Coord = { y = -6051.7, x = 393.6 },
            Range = 15,
            Class = { "WARLOCK" },
            Race = "Gnome",
            Zone = 1426,
            _index = 51,
        },
        {
            Done = { 233 },
            Coord = { y = -6221.2, x = 687.5 },
            Zone = 1426,
            _index = 52,
        },
        {
            PickUp = { 234, 183 },
            Coord = { y = -6221.2, x = 687.5 },
            Zone = 1426,
            _index = 53,
        },
        {
            Qpart = { [183] = { 1 } },
            Coord = { y = -6181.5, x = 747 },
            Range = 30,
            RaidIcon = 714,
            Zone = 1426,
            _index = 54,
        },
        {
            Done = { 183 },
            Coord = { y = -6220.8, x = 689.2 },
            Zone = 1426,
            _index = 55,
        },
        {
            Done = { 234 },
            Coord = { y = -6363, x = 566.9 },
            Zone = 1426,
            _index = 56,
        },
        {
            PickUp = { 182 },
            Coord = { y = -6363, x = 566.9 },
            Zone = 1426,
            _index = 57,
        },
        {
            Qpart = { [3361] = { 1 } },
            Fillers = { [182] = { 1 }, [94373] = { 1 } },
            Coord = { y = -6373.7, x = 770.4 },
            Range = 5,
            Zone = 1426,
            _index = 58,
        },
        {
            Qpart = { [182] = { 1 } },
            Fillers = { [182] = { 1 }, [94373] = { 1 } },
            Coord = { y = -6441.6, x = 696.3 },
            Range = 30,
            ClassNot = "SHAMAN",
            Zone = 1426,
            _index = 59,
        },
        {
            Qpart = { [3361] = { 2 } },
            Fillers = { [182] = { 1 }, [94373] = { 1 } },
            Coord = { y = -6500.8, x = 679.4 },
            Range = 5,
            Zone = 1426,
            _index = 60,
        },
        {
            Qpart = { [3361] = { 3 } },
            Fillers = { [182] = { 1 }, [94373] = { 1 } },
            Coord = { y = -6479.4, x = 507.9 },
            Range = 5,
            Zone = 1426,
            _index = 61,
        },
        {
            Qpart = { [94373] = { 1 } },
            Fillers = { [182] = { 1 } },
            Coord = { y = -6450.9, x = 687.5 },
            Range = 15,
            Class = { "SHAMAN" },
            Race = "Dwarf",
            Zone = 1426,
            _index = 62,
        },
        {
            Qpart = { [182] = { 1 } },
            Coord = { y = -6441.6, x = 696.3 },
            Range = 30,
            Class = "SHAMAN",
            Race = "Dwarf",
            Zone = 1426,
            _index = 63,
        },
        {
            Done = { 182 },
            Coord = { y = -6366.9, x = 565.7 },
            Zone = 1426,
            _index = 64,
        },
        {
            PickUp = { 218 },
            Coord = { y = -6366.9, x = 565.7 },
            Zone = 1426,
            _index = 65,
        },
        {
            Waypoint = 218,
            NonSkippableWaypoint = true,
            Fillers = { [1599] = { 1 } },
            ExtraLineText = "GO_INSIDE_CAVE",
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1426, 27.098, 80.707),
            Range = 20,
            Zone = 1426,
            _index = 66,
        },
        {
            Waypoint = 218,
            NonSkippableWaypoint = true,
            Fillers = { [1599] = { 1 } },
            ExtraLineText = "GO_INSIDE_CAVE",
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1426, 28.298, 79.836),
            Range = 15,
            Zone = 1426,
            _index = 67,
        },
        {
            Waypoint = 218,
            NonSkippableWaypoint = true,
            Fillers = { [1599] = { 1 } },
            ExtraLineText = "GO_INSIDE_CAVE",
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1426, 29.252, 79.043),
            Range = 15,
            Zone = 1426,
            _index = 68,
        },
        {
            Waypoint = 218,
            NonSkippableWaypoint = true,
            Fillers = { [1599] = { 1 } },
            ExtraLineText = "GO_INSIDE_CAVE",
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1426, 30.489, 80.165),
            Range = 50,
            Zone = 1426,
            _index = 69,
        },
        {
            Qpart = { [218] = { 1 } },
            Fillers = { [1599] = { 1 } },
            Coord = { y = -6511.1, x = 302.1 },
            Range = 5,
            Zone = 1426,
            _index = 70,
        },
        {
            Qpart = { [1599] = { 1 } },
            Coord = { y = -6511, x = 302 },
            Range = 15,
            Class = { "WARLOCK" },
            Race = "Gnome",
            Zone = 1426,
            _index = 71,
        },
        {
            Waypoint = 218,
            NonSkippableWaypoint = true,
            ExtraLineText = "EXIT_CAVE",
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1426, 29.252, 79.043),
            Range = 15,
            Zone = 1426,
            _index = 72,
        },
        {
            Waypoint = 218,
            NonSkippableWaypoint = true,
            ExtraLineText = "EXIT_CAVE",
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1426, 28.298, 79.836),
            Range = 15,
            Zone = 1426,
            _index = 73,
        },
        {
            Waypoint = 218,
            NonSkippableWaypoint = true,
            ExtraLineText = "EXIT_CAVE",
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1426, 27.098, 80.707),
            Range = 20,
            Zone = 1426,
            _index = 74,
        },
        {
            Done = { 218 },
            Coord = { y = -6363.8, x = 566.5 },
            Zone = 1426,
            _index = 75,
        },
        {
            PickUp = { 282 },
            Coord = { y = -6363.8, x = 566.5 },
            Zone = 1426,
            _index = 76,
        },
        {
            PickUp = { 3364 },
            Coord = { y = -6369.6, x = 570.6 },
            Zone = 1426,
            _index = 77,
        },
        {
            UseHS = 3364,
            Zone = 1426,
            _index = 78,
        },
        {
            Done = { 3361 },
            Coord = { y = -6100.6, x = 398.2 },
            RaidIcon = 8416,
            Zone = 1426,
            _index = 79,
        },
        {
            PickUp = { 97277 },
            Coord = { y = -6094.7, x = 392.4 },
            RaidIcon = 2756,
            Zone = 1426,
            _index = 80,
        },
        {
            Done = { 3364 },
            Coord = { y = -6056.9, x = 385.1 },
            Zone = 1426,
            _index = 81,
        },
        {
            PickUp = { 3365 },
            Coord = { y = -6056.9, x = 385.1 },
            RaidIcon = 926,
            Zone = 1426,
            _index = 82,
        },
        {
            Done = { 1599 },
            Coord = { y = -6051.9, x = 394.5 },
            Range = 15,
            RaidIcon = 460,
            Class = { "WARLOCK" },
            Race = "Gnome",
            Zone = 1426,
            _index = 83,
        },
        {
            LearnSkill = { spellID = 1978, npcID = 895 },
            Coord = { y = -6091.86, x = 365.21 },
            Class = "HUNTER",
            MinLevel = 4,
            Race = "Dwarf",
            Zone = 1426,
            _index = 84,
        },
        {
            LearnSkill = { spellID = 172, npcID = 460 },
            Coord = { y = -6048.84, x = 391.07 },
            Class = "WARLOCK",
            MinLevel = 4,
            Race = "Gnome",
            Zone = 1426,
            _index = 85,
        },
        {
            LearnSkill = { spellID = 8042, npcID = 257446 },
            Coord = { y = -6050.2, x = 384 },
            RaidIcon = 257446,
            Class = "SHAMAN",
            MinLevel = 4,
            Race = "Dwarf",
            Zone = 1426,
            _index = 86,
        },
        {
            LearnSkill = { spellIDs = { 19740, 20271 }, npcID = 926 },
            Coord = { y = -6120.65, x = 382.06 },
            Class = "PALADIN",
            MinLevel = 4,
            Race = "Dwarf",
            Zone = 1426,
            _index = 87,
        },
        {
            LearnSkill = { spellID = 116, npcID = 944 },
            Coord = { y = -6056.1, x = 388.17 },
            Class = "MAGE",
            MinLevel = 4,
            Race = "Gnome",
            Zone = 1426,
            _index = 88,
        },
        {
            LearnSkill = { spellIDs = { 100, 772 }, npcID = 912 },
            Coord = { y = -6084.86, x = 382.11 },
            Class = "WARRIOR",
            MinLevel = 4,
            Race = "Dwarf",
            Zone = 1426,
            _index = 89,
        },
        {
            LearnSkill = { spellIDs = { 100, 772 }, npcID = 912 },
            Coord = { y = -6084.86, x = 382.11 },
            Class = "WARRIOR",
            MinLevel = 4,
            Race = "Gnome",
            Zone = 1426,
            _index = 90,
        },
        {
            Done = { 94373 },
            Coord = { y = -6050.7, x = 383.7 },
            Range = 15,
            RaidIcon = 257446,
            Class = { "SHAMAN" },
            Race = "Dwarf",
            Zone = 1426,
            _index = 91,
        },
        {
            PickUp = { 94374 },
            Coord = { y = -6050.7, x = 383.7 },
            Range = 15,
            RaidIcon = 257446,
            Class = { "SHAMAN" },
            Race = "Dwarf",
            Zone = 1426,
            _index = 92,
        },
        {
            Done = { 3365 },
            Coord = { y = -6372.5, x = 573.4 },
            Zone = 1426,
            _index = 93,
        },
        {
            Qpart = { [97277] = { 1, 2 } },
            Coord = { y = -5940.2, x = 456.1 },
            Range = 5,
            Zone = 1426,
            _index = 94,
        },
        {
            UseItem = { questID = 94374, itemID = 6635, itemSpellID = 1287900 },
            Coord = { y = -5907.6, x = 581.9 },
            Range = 15,
            Class = { "SHAMAN" },
            Race = "Dwarf",
            Zone = 1426,
            _index = 95,
        },
        {
            Done = { 94374 },
            Coord = { y = -5907.6, x = 581.9 },
            Range = 15,
            RaidIcon = 5891,
            Class = { "SHAMAN" },
            Race = "Dwarf",
            Zone = 1426,
            _index = 96,
        },
        {
            PickUp = { 94375 },
            Coord = { y = -5907.6, x = 581.9 },
            Range = 15,
            RaidIcon = 5891,
            Class = { "SHAMAN" },
            Race = "Dwarf",
            Zone = 1426,
            _index = 97,
        },
        {
            Done = { 97277 },
            Coord = { y = -6095.1, x = 391.8 },
            RaidIcon = 2756,
            Zone = 1426,
            _index = 98,
        },
        {
            Done = { 94375 },
            Coord = { y = -6050.5, x = 384.2 },
            Range = 15,
            RaidIcon = 257446,
            Class = { "SHAMAN" },
            Race = "Dwarf",
            Zone = 1426,
            _index = 99,
        },
        {
            Grind = 5,
            Coord = { y = -5940.2, x = 456.1 },
            Range = 30,
            Class = "PRIEST",
            IsQuestNotOnQuest = 5626,
            IsQuestUncompleted = 5626,
            Zone = 1426,
            _index = 100,
        },
        {
            PickUp = { 5626 },
            Coord = { y = -6057.6, x = 393.3 },
            Range = 15,
            RaidIcon = 837,
            Class = { "PRIEST" },
            MinLevel = 5,
            Zone = 1426,
            _index = 101,
        },
        {
            Done = { 282 },
            Coord = { y = -6236.1, x = 154.9 },
            Zone = 1426,
            _index = 102,
        },
        {
            PickUp = { 420, 96628 },
            Coord = { y = -6236.1, x = 154.9 },
            Zone = 1426,
            _index = 103,
        },
        {
            PickUp = { 2160 },
            Coord = { y = -6246.7, x = 137.1 },
            Zone = 1426,
            _index = 104,
        },
        {
            Waypoint = 2160,
            NonSkippableWaypoint = true,
            Coord = { y = -6206.61, x = 111.82 },
            Range = 15,
            Zone = 1426,
            _index = 105,
        },
        {
            Waypoint = 2160,
            NonSkippableWaypoint = true,
            Coord = { y = -6037.19, x = 46.32 },
            Range = 15,
            Zone = 1426,
            _index = 106,
        },
        {
            Done = { 96628 },
            Coord = { y = -5647.8, x = -497.4 },
            RaidIcon = 265813,
            Zone = 1426,
            _index = 107,
        },
        {
            PickUp = { 96608 },
            Coord = { y = -5647.8, x = -497.4 },
            RaidIcon = 265813,
            Zone = 1426,
            _index = 108,
        },
        {
            Qpart = { [96608] = { 1, 2 } },
            Emote = { emote = "sit", npcID = 0, manual = true },
            Coord = { y = -5647.8, x = -497.4 },
            Range = 5,
            EmoteETA = 60,
            Zone = 1426,
            _index = 109,
        },
        {
            Done = { 96608 },
            Coord = { y = -5647.8, x = -497.4 },
            RaidIcon = 265813,
            Zone = 1426,
            _index = 110,
        },
        {
            PickUp = { 96629 },
            Coord = { y = -5647.8, x = -497.4 },
            RaidIcon = 265813,
            Zone = 1426,
            _index = 111,
        },
        {
            Done = { 420 },
            Coord = { y = -5644.3, x = -500.1 },
            Zone = 1426,
            _index = 112,
        },
        {
            PickUp = { 98322 },
            Coord = { y = -5644.3, x = -500.1 },
            Zone = 1426,
            _index = 113,
        },
        {
            PickUp = { 384 },
            Coord = { y = -5597.7, x = -503.5 },
            MinLevel = 5,
            Zone = 1426,
            _index = 114,
        },
        {
            Done = { 2160 },
            Coord = { y = -5589.4, x = -523.8 },
            Zone = 1426,
            _index = 115,
        },
        {
            SetHS = 384,
            Coord = { y = -5600.1, x = -530.7 },
            Zone = 1426,
            _index = 116,
        },
        {
            SellItems = { junk = true },
            Coord = { y = -5600.4, x = -530.8 },
            DontHaveSpell = 2550,
            Zone = 1426,
            _index = 117,
        },
        {
            LearnProfession = 2550,
            Coord = { y = -5595.3, x = -544.5 },
            RaidIcon = 1699,
            MinLevel = 5,
            Zone = 1426,
            _index = 118,
        },
        {
            Done = { 96629 },
            Coord = { y = -5595.3, x = -544.5 },
            Zone = 1426,
            _index = 119,
        },
        {
            LearnSkill = { allAvailable = true, npcID = 1226 },
            Coord = { y = -5590.66, x = -529.51 },
            RaidIcon = 1226,
            Class = "PRIEST",
            MinLevel = 1,
            Zone = 1426,
            _index = 120,
        },
        {
            LearnSkill = { allAvailable = true, npcID = 1228 },
            Coord = { y = -5587, x = -537.2 },
            RaidIcon = 1228,
            Class = "MAGE",
            MinLevel = 1,
            Race = "Gnome",
            Zone = 1426,
            _index = 121,
        },
        {
            LearnSkill = { allAvailable = true, npcID = 1232 },
            Coord = { y = -5586.8, x = -542.1 },
            RaidIcon = 1232,
            Class = "PALADIN",
            MinLevel = 1,
            Race = "Dwarf",
            Zone = 1426,
            _index = 122,
        },
        {
            LearnSkill = { allAvailable = true, npcID = 258113 },
            Coord = { y = -5582.9, x = -541.5 },
            RaidIcon = 258113,
            Class = "SHAMAN",
            MinLevel = 1,
            Race = "Dwarf",
            Zone = 1426,
            _index = 123,
        },
        {
            LearnSkill = { allAvailable = true, npcID = 1231 },
            Coord = { y = -5618.53, x = -454.06 },
            RaidIcon = 1231,
            Class = "HUNTER",
            MinLevel = 1,
            Race = "Dwarf",
            Zone = 1426,
            _index = 124,
        },
        {
            LearnSkill = { allAvailable = true, npcID = 1234 },
            Coord = { y = -5604.38, x = -540.39 },
            RaidIcon = 1234,
            Class = "ROGUE",
            MinLevel = 1,
            Zone = 1426,
            _index = 125,
        },
        {
            LearnSkill = { allAvailable = true, npcID = 1229 },
            Coord = { y = -5605.63, x = -530.4 },
            RaidIcon = 1229,
            Class = "WARRIOR",
            MinLevel = 1,
            Zone = 1426,
            _index = 126,
        },
        {
            LearnSkill = { allAvailable = true, npcID = 5612 },
            Coord = { y = -5640, x = -528.87 },
            RaidIcon = 5612,
            Class = "WARLOCK",
            MinLevel = 1,
            Race = "Gnome",
            Zone = 1426,
            _index = 127,
        },
        {
            Done = { 5626 },
            Coord = { y = -5590, x = -529.4 },
            Range = 15,
            RaidIcon = 1226,
            Class = { "PRIEST" },
            MinLevel = 5,
            Zone = 1426,
            _index = 128,
        },
        {
            PickUp = { 5625 },
            Coord = { y = -5590, x = -529.4 },
            Range = 15,
            RaidIcon = 1226,
            Class = { "PRIEST" },
            MinLevel = 5,
            Zone = 1426,
            _index = 129,
        },
        {
            Qpart = { [5625] = { 1 } },
            Coord = { y = -5669.1, x = -455.1 },
            Range = 15,
            SpellButton = { ["5625-1"] = { 2052, 1243 } },
            RaidIcon = 12427,
            Class = { "PRIEST" },
            MinLevel = 5,
            Zone = 1426,
            _index = 130,
        },
        {
            Done = { 5625 },
            Coord = { y = -5589.6, x = -528.7 },
            Range = 15,
            RaidIcon = 1226,
            Class = { "PRIEST" },
            MinLevel = 5,
            Zone = 1426,
            _index = 131,
        },
        {
            PickUp = { 99158 },
            Coord = { y = -5590.6, x = -529.6 },
            RaidIcon = 1226,
            MinLevel = 5,
            Zone = 1426,
            _index = 132,
        },
        {
            SellItems = { junk = true },
            Coord = { y = -5387.58, x = 302.27 },
            Class = { "MAGE", "PRIEST", "WARLOCK" },
            MinLevel = 5,
            Zone = 1426,
            _index = 133,
        },
        {
            BuyMerchant = { { itemID = 1179, quantity = 20 } },
            Coord = { y = -5387.58, x = 302.27 },
            Class = { "MAGE", "PRIEST", "WARLOCK" },
            ItemCount = { count = 20, itemID = 1179, operator = "<" },
            MinLevel = 5,
            Money = { copper = 500, operator = ">=" },
            Zone = 1426,
            _index = 134,
        },
        {
            SellItems = { junk = true },
            Coord = { y = -5597.65, x = -521.97 },
            Class = "ROGUE",
            EquippedItemStat = { allowMissing = true, slot = 18, value = 3, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" },
            MinLevel = 3,
            Zone = 1426,
            _index = 135,
        },
        {
            BuyMerchant = { { itemID = 2946, quantity = 1 } },
            Coord = { y = -5597.65, x = -521.97 },
            Class = "ROGUE",
            EquippedItemStat = { allowMissing = true, slot = 18, value = 3, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" },
            ItemCount = { count = 1, itemID = 2946, operator = "<" },
            MinLevel = 3,
            Money = { copper = 30, operator = ">=" },
            Zone = 1426,
            _index = 136,
        },
        {
            SellItems = { junk = true, npcID = 1273 },
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1426, 45.288, 52.193),
            Class = "WARRIOR",
            EquippedItemStat = { allowMissing = true, slot = 16, value = 3.8, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" },
            Race = "Gnome",
            Zone = 1426,
            _index = 137,
        },
        {
            BuyMerchant = { { itemID = 2488, quantity = 1 } },
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1426, 45.288, 52.193),
            MerchantNPC = 1273,
            Class = "WARRIOR",
            EquippedItemStat = { allowMissing = true, slot = 16, value = 3.8, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" },
            ItemCount = { count = 1, itemID = 2488, operator = "<" },
            Money = { copper = 536, operator = ">=" },
            Race = "Gnome",
            Zone = 1426,
            _index = 138,
        },
        {
            SellItems = { junk = true, npcID = 1273 },
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1426, 45.288, 52.193),
            Class = "WARRIOR",
            EquippedItemStat = { allowMissing = true, slot = 16, value = 4.3, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" },
            Race = "Dwarf",
            Zone = 1426,
            _index = 139,
        },
        {
            BuyMerchant = { { itemID = 2491, quantity = 1 } },
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1426, 45.288, 52.193),
            MerchantNPC = 1273,
            Class = "WARRIOR",
            EquippedItemStat = { allowMissing = true, slot = 16, value = 4.3, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" },
            ItemCount = { count = 1, itemID = 2491, operator = "<" },
            Money = { copper = 484, operator = ">=" },
            Race = "Dwarf",
            Zone = 1426,
            _index = 140,
        },
        {
            SellItems = { junk = true, npcID = 1273 },
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1426, 45.288, 52.193),
            Class = "ROGUE",
            EquippedItemStat = { allowMissing = true, slot = 16, value = 3.3, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" },
            Zone = 1426,
            _index = 141,
        },
        {
            BuyMerchant = { { itemID = 2494, quantity = 1 } },
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1426, 45.288, 52.193),
            MerchantNPC = 1273,
            Class = "ROGUE",
            EquippedItemStat = { allowMissing = true, slot = 16, value = 3.3, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" },
            ItemCount = { count = 1, itemID = 2494, operator = "<" },
            Money = { copper = 401, operator = ">=" },
            Zone = 1426,
            _index = 142,
        },
        {
            SellItems = { junk = true, npcID = 1273 },
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1426, 45.288, 52.193),
            Class = "SHAMAN",
            EquippedItemStat = { allowMissing = true, slot = 16, value = 4.2, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" },
            Race = "Dwarf",
            Zone = 1426,
            _index = 143,
        },
        {
            BuyMerchant = { { itemID = 2495, quantity = 1 } },
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1426, 45.288, 52.193),
            MerchantNPC = 1273,
            Class = "SHAMAN",
            EquippedItemStat = { allowMissing = true, slot = 16, value = 4.2, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" },
            ItemCount = { count = 1, itemID = 2495, operator = "<" },
            Money = { copper = 504, operator = ">=" },
            Race = "Dwarf",
            Zone = 1426,
            _index = 144,
        },
        {
            PickUp = { 400 },
            Coord = { y = -5575.9, x = -466.4 },
            Zone = 1426,
            _index = 145,
        },
        {
            PickUp = { 98321 },
            Coord = { y = -5584, x = -430.5 },
            Zone = 1426,
            _index = 146,
        },
        {
            PickUp = { 317 },
            Coord = { y = -5465.2, x = -630.4 },
            Zone = 1426,
            _index = 147,
        },
        {
            PickUp = { 313 },
            Coord = { y = -5470.6, x = -640.9 },
            Zone = 1426,
            _index = 148,
        },
        {
            Done = { 400 },
            Coord = { y = -5488.3, x = -680.6 },
            Zone = 1426,
            _index = 149,
        },
        {
            PickUp = { 5541 },
            Coord = { y = -5496.4, x = -665.2 },
            Zone = 1426,
            _index = 150,
        },
        {
            Done = { 98322 },
            Coord = { y = -5748, x = -369 },
            Zone = 1426,
            _index = 151,
        },
        {
            PickUp = { 98319 },
            Coord = { y = -5748, x = -369 },
            Zone = 1426,
            _index = 152,
        },
        {
            Qpart = { [5541] = { 1 } },
            Fillers = { [313] = { 1 }, [98321] = { 1 } },
            Coord = { y = -5747.3, x = -369.7 },
            Range = 5,
            Zone = 1426,
            _index = 153,
        },
        {
            Qpart = { [98321] = { 1 } },
            Fillers = { [313] = { 1 }, [98319] = { 1 } },
            Coord = { y = -5575.6, x = -310.5 },
            Range = 30,
            Zone = 1426,
            _index = 154,
        },
        {
            Qpart = { [313] = { 1 }, [98319] = { 1 }, [98321] = { 1 } },
            ExtraLineText = "FINISH_MOB_BEFORE_LEAVING",
            Coord = { y = -5503.1, x = -309.8 },
            Range = 35,
            Zone = 1426,
            _index = 155,
        },
        {
            Done = { 98319 },
            Coord = { y = -5750.8, x = -366.8 },
            Zone = 1426,
            _index = 156,
        },
        {
            PickUp = { 98323 },
            Coord = { y = -5750.8, x = -366.8 },
            Zone = 1426,
            _index = 157,
        },
        {
            Qpart = { [317] = { 1, 2 } },
            Fillers = { [384] = { 1 } },
            ExtraLineText = "KEEP_CRAG_BOAR_RIBS_FOR_COOKING",
            Coord = { y = -5619.7, x = -672.4 },
            Range = 65,
            Zone = 1426,
            _index = 158,
        },
        {
            Qpart = { [384] = { 1 } },
            Coord = { y = -5653.8, x = -644 },
            Range = 30,
            RaidIcon = 1196,
            Zone = 1426,
            _index = 159,
        },
        {
            Done = { 313 },
            Coord = { y = -5469.3, x = -639.1 },
            Zone = 1426,
            _index = 160,
        },
        {
            Done = { 317 },
            Coord = { y = -5464.1, x = -631 },
            Zone = 1426,
            _index = 161,
        },
        {
            PickUp = { 318 },
            Coord = { y = -5464.1, x = -631 },
            Zone = 1426,
            _index = 162,
        },
        {
            Done = { 98321 },
            Coord = { y = -5584, x = -431.4 },
            Zone = 1426,
            _index = 163,
        },
        {
            Done = { 98323 },
            Coord = { y = -5642.7, x = -499.8 },
            Zone = 1426,
            _index = 164,
        },
        {
            PickUp = { 287 },
            Coord = { y = -5642.7, x = -499.8 },
            Zone = 1426,
            _index = 165,
        },
        {
            PickUp = { 412 },
            Coord = { y = -5497.6, x = -456.2 },
            Zone = 1426,
            _index = 166,
        },
        {
            Qpart = { [384] = { 2 } },
            Coord = { y = -5600.4, x = -530.8 },
            GossipOptionIDs = { 95589 },
            Zone = 1426,
            _index = 167,
        },
        {
            Done = { 384 },
            Coord = { y = -5597.6, x = -505.4 },
            Zone = 1426,
            _index = 168,
        },
        {
            Done = { 5541 },
            Coord = { y = -6014.4, x = -202.4 },
            Zone = 1426,
            _index = 169,
        },
        {
            SellItems = { junk = true, npcID = 1243 },
            Coord = { y = -6015.52, x = -201.51 },
            Class = "HUNTER",
            EquippedItemStat = { allowMissing = true, slot = 18, value = 2.95, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" },
            MinLevel = 4,
            Race = "Dwarf",
            Zone = 1426,
            _index = 170,
        },
        {
            BuyMerchant = { { itemID = 2509, quantity = 1 } },
            Fillers = { [384] = { 1, 2 } },
            Coord = { y = -6015.52, x = -201.51 },
            MerchantNPC = 1243,
            Class = "HUNTER",
            EquippedItemStat = { allowMissing = true, slot = 18, value = 2.95, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" },
            ItemCount = { count = 1, itemID = 2509, operator = "<" },
            MinLevel = 4,
            Money = { copper = 414, operator = ">=" },
            Race = "Dwarf",
            Zone = 1426,
            _index = 171,
        },
        {
            PickUp = { 312 },
            Fillers = { [384] = { 1, 2 } },
            Coord = { y = -5572.99, x = 99.17 },
            Zone = 1426,
            _index = 172,
        },
        {
            Done = { 318 },
            Coord = { y = -5381, x = 314.9 },
            Zone = 1426,
            _index = 173,
        },
        {
            PickUp = { 319, 315 },
            Coord = { y = -5381, x = 314.9 },
            Zone = 1426,
            _index = 174,
        },
        {
            PickUp = { 310 },
            Coord = { y = -5374.1, x = 312.9 },
            Zone = 1426,
            _index = 175,
        },
        {
            Qpart = { [319] = { 1 } },
            Fillers = { [319] = { 2, 3 }, [412] = { 1, 2 } },
            Coord = { y = -5263.9, x = 300.2 },
            Range = 30,
            Zone = 1426,
            _index = 176,
        },
        {
            Qpart = { [319] = { 3, 2 } },
            Fillers = { [412] = { 1, 2 } },
            Coord = { y = -5215.6, x = 355.2 },
            Range = 30,
            RaidIcon = 1397,
            Zone = 1426,
            _index = 177,
        },
        {
            Qpart = { [412] = { 2 } },
            Fillers = { [412] = { 1 } },
            Coord = { y = -5322.8, x = 477.3 },
            Range = 30,
            Zone = 1426,
            _index = 178,
        },
        {
            Qpart = { [412] = { 1 } },
            Coord = { y = -5237.8, x = 548.3 },
            Range = 30,
            Zone = 1426,
            _index = 179,
        },
        {
            Done = { 319 },
            Coord = { y = -5379.2, x = 312.9 },
            Zone = 1426,
            _index = 180,
        },
        {
            PickUp = { 320 },
            Coord = { y = -5379.2, x = 312.9 },
            Zone = 1426,
            _index = 181,
        },
        {
            Qpart = { [315] = { 1 } },
            Coord = { y = -5079.1, x = -277 },
            Range = 30,
            Zone = 1426,
            _index = 182,
        },
        {
            Qpart = { [312] = { 1 } },
            Coord = { y = -5647.69, x = -94.88 },
            Zone = 1426,
            _index = 183,
        },
        {
            Done = { 312 },
            Coord = { y = -5572.99, x = 99.17 },
            Zone = 1426,
            _index = 184,
        },
        {
            Done = { 315 },
            Coord = { y = -5379.2, x = 312.9 },
            Zone = 1426,
            _index = 185,
        },
        {
            PickUp = { 413 },
            Coord = { y = -5379.2, x = 312.9 },
            Zone = 1426,
            _index = 186,
        },
        {
            SellItems = { junk = true },
            Coord = { y = -5601.1, x = -530.4 },
            Zone = 1426,
            _index = 187,
        },
        {
            BuyMerchant = { { quantity = 1, itemID = 2686, questID = 308 } },
            Coord = { y = -5601.1, x = -530.4 },
            Range = 15,
            ItemCount = { itemID = 2686, count = 1, operator = "<" },
            Money = { copper = 50, operator = ">=" },
            Zone = 1426,
            _index = 188,
        },
        {
            PickUp = { 308 },
            Coord = { y = -5605.2, x = -543.8 },
            RaidIcon = 1373,
            IsQuestNotOnQuest = 308,
            IsQuestUncompleted = 310,
            Zone = 1426,
            _index = 189,
        },
        {
            Done = { 308 },
            Coord = { y = -5605.2, x = -543.8 },
            RaidIcon = 1373,
            IsQuestUncompleted = 310,
            Zone = 1426,
            _index = 190,
        },
        {
            Done = { 310 },
            Coord = { y = -5605.2, x = -543.8 },
            Zone = 1426,
            _index = 191,
        },
        {
            PickUp = { 311 },
            Coord = { y = -5607.2, x = -547.2 },
            Zone = 1426,
            _index = 192,
        },
        {
            Done = { 311 },
            Coord = { y = -5372.6, x = 312.1 },
            Zone = 1426,
            _index = 193,
        },
        {
            Qpart = { [287] = { 1 } },
            Coord = { y = -5545.5, x = 659.2 },
            Range = 30,
            Zone = 1426,
            _index = 194,
        },
        {
            Waypoint = 287,
            NonSkippableWaypoint = true,
            Fillers = { [287] = { 1 } },
            Note = { "GO_INSIDE_CAVE", "KEEP_LEFT_INSIDE_CAVE" },
            Coord = { y = -5579.5, x = 628.4 },
            Range = 20,
            Zone = 1426,
            _index = 195,
        },
        {
            Waypoint = 287,
            NonSkippableWaypoint = true,
            Fillers = { [287] = { 1 } },
            Note = { "GO_INSIDE_CAVE", "KEEP_LEFT_INSIDE_CAVE" },
            Coord = { y = -5674.6, x = 696.6 },
            Range = 20,
            Zone = 1426,
            _index = 196,
        },
        {
            Waypoint = 287,
            NonSkippableWaypoint = true,
            Fillers = { [287] = { 1 } },
            Note = { "GO_INSIDE_CAVE", "KEEP_LEFT_INSIDE_CAVE" },
            Coord = { y = -5614.9, x = 746.9 },
            Range = 20,
            Zone = 1426,
            _index = 197,
        },
        {
            Waypoint = 287,
            NonSkippableWaypoint = true,
            Fillers = { [287] = { 1 } },
            Note = { "GO_INSIDE_CAVE", "KEEP_LEFT_INSIDE_CAVE" },
            Coord = { y = -5528.3, x = 695.3 },
            Range = 20,
            Zone = 1426,
            _index = 198,
        },
        {
            Qpart = { [287] = { 2 } },
            Coord = { y = -5646, x = 755.3 },
            Range = 5,
            Zone = 1426,
            _index = 199,
        },
        {
            UseHS = 287,
            Zone = 1426,
            _index = 200,
        },
        {
            Done = { 287 },
            Coord = { y = -5642, x = -499 },
            Zone = 1426,
            _index = 201,
        },
        {
            PickUp = { 291 },
            Coord = { y = -5642, x = -499 },
            RaidIcon = 1269,
            Zone = 1426,
            _index = 202,
        },
        {
            Done = { 412 },
            Coord = { y = -5496.9, x = -456.9 },
            Zone = 1426,
            _index = 203,
        },
        {
            Done = { 320 },
            Coord = { y = -5464.4, x = -631 },
            Zone = 1426,
            _index = 204,
        },
        {
            PickUp = { 96408 },
            Coord = { y = -5487.7, x = -680.9 },
            Zone = 1426,
            _index = 205,
        },
        {
            Done = { 99158 },
            Coord = { y = -5348, x = -1040.2 },
            RaidIcon = 1253,
            Zone = 1426,
            _index = 206,
        },
        {
            Group = { questID = 314, Number = 2 },
            ExtraLineText = "SKIP_THIS_ONE_OR_GROUP",
            Zone = 1426,
            _index = 207,
        },
        {
            PickUp = { 314 },
            GroupTask = 314,
            ExtraLineText = "SKIP_THIS_ONE_OR_GROUP",
            Coord = { y = -5517.6, x = -1306.1 },
            Zone = 1426,
            _index = 208,
        },
        {
            Qpart = { [314] = { 1 } },
            GroupTask = 314,
            Coord = { y = -5481.7, x = -1270.8 },
            Range = 5,
            Zone = 1426,
            _index = 209,
        },
        {
            Done = { 314 },
            GroupTask = 314,
            Coord = { y = -5516.4, x = -1304.7 },
            Zone = 1426,
            _index = 210,
        },
        {
            Done = { 96408 },
            Coord = { y = -5796.4, x = -1390.8 },
            Zone = 1426,
            _index = 211,
        },
        {
            PickUp = { 96392 },
            Coord = { y = -5796.4, x = -1390.8 },
            GossipOptionIDs = { 139831 },
            Zone = 1426,
            _index = 212,
        },
        {
            Qpart = { [96392] = { 1 } },
            Coord = { y = -5796.4, x = -1390.8 },
            Range = 5,
            Zone = 1426,
            _index = 213,
        },
        {
            Done = { 96392 },
            Coord = { y = -5796.4, x = -1390.8 },
            Zone = 1426,
            _index = 214,
        },
        {
            PickUp = { 96390 },
            Coord = { y = -5796.4, x = -1390.8 },
            Zone = 1426,
            _index = 215,
        },
        {
            PickUp = { 433 },
            Coord = { y = -5713.6, x = -1577.8 },
            Zone = 1426,
            _index = 216,
        },
        {
            PickUp = { 432 },
            Coord = { y = -5723.9, x = -1599.4 },
            Zone = 1426,
            _index = 217,
        },
        {
            Qpart = { [432] = { 1 } },
            DroppableQuest = { Qid = 95213, MobId = 1116, Text = "Rockjaw Ambusher" },
            Fillers = { [433] = { 1 } },
            Coord = { y = -5761.3, x = -1626.4 },
            Range = 30,
            Zone = 1426,
            _index = 218,
        },
        {
            Qpart = { [433] = { 1 } },
            DroppableQuest = { Qid = 95213, MobId = 1116, Text = "Rockjaw Ambusher" },
            Fillers = { [432] = { 1 } },
            Coord = { y = -5695.7, x = -1671.2 },
            Range = 30,
            Zone = 1426,
            _index = 219,
        },
        {
            Done = { 432 },
            Coord = { y = -5724.9, x = -1598.8 },
            Zone = 1426,
            _index = 220,
        },
        {
            Done = { 433 },
            Coord = { y = -5715.9, x = -1580.7 },
            Zone = 1426,
            _index = 221,
        },
        {
            DropQuest = 95213,
            DroppableQuest = { Qid = 95213, MobId = 1116, Text = "Rockjaw Ambusher" },
            Coord = { y = -5695.7, x = -1671.2 },
            ItemCount = { itemID = 268548, count = 1 },
            Zone = 1426,
            _index = 222,
        },
        {
            Qpart = { [95213] = { 1 } },
            NoArrow = true,
            IsQuestOnQuest = 95213,
            _index = 223,
        },
        {
            Done = { 95213 },
            Coord = { y = -5676.35, x = -1606.02 },
            IsQuestOnQuest = 95213,
            Zone = 1426,
            _index = 224,
        },
        {
            PickUp = { 95214 },
            Coord = { y = -5676.35, x = -1606.02 },
            IsQuestCompleted = 95213,
            Zone = 1426,
            _index = 225,
        },
        {
            Qpart = { [95214] = { 1 } },
            Coord = { y = -5653.365, x = -1803.02 },
            Range = 164,
            IsQuestCompleted = 95213,
            Zone = 1426,
            _index = 226,
        },
        {
            Done = { 95214 },
            Coord = { y = -5676.35, x = -1606.02 },
            IsQuestCompleted = 95213,
            Zone = 1426,
            _index = 227,
        },
        {
            Qpart = { [96390] = { 1 } },
            DroppableQuest = { Qid = 96391, MobId = 6123, Text = "Dark Iron Spy" },
            Coord = { y = -5860, x = -2004 },
            Range = 30,
            Zone = 1426,
            _index = 228,
        },
        {
            DropQuest = 96391,
            DroppableQuest = { Qid = 96391, MobId = 6123, Text = "Dark Iron Spy" },
            Coord = { y = -5885.2, x = -1975.9 },
            MinLevel = 9,
            Zone = 1426,
            _index = 229,
        },
        {
            Done = { 96390, 96391 },
            Coord = { y = -5794.4, x = -1390 },
            Zone = 1426,
            _index = 230,
        },
        {
            PickUp = { 96393 },
            Coord = { y = -5794.4, x = -1390 },
            Zone = 1426,
            _index = 231,
        },
        {
            PickUp = { 419 },
            Coord = { y = -5164.2, x = -2327.8 },
            Zone = 1426,
            _index = 232,
        },
        {
            Done = { 419 },
            Coord = { y = -5064.1, x = -2124.4 },
            Zone = 1426,
            _index = 233,
        },
        {
            PickUp = { 417 },
            Coord = { y = -5064.1, x = -2124.4 },
            Zone = 1426,
            _index = 234,
        },
        {
            Qpart = { [417] = { 1 } },
            Coord = { y = -5091, x = -2090.4 },
            Range = 5,
            Zone = 1426,
            _index = 235,
        },
        {
            Done = { 417 },
            Coord = { y = -5161.6, x = -2328.1 },
            Zone = 1426,
            _index = 236,
        },
        {
            Grind = 10,
            Coord = { y = -5745.3, x = -576.69 },
            Range = 60,
            Class = "HUNTER",
            IsQuestNotOnQuest = 6064,
            IsQuestUncompleted = 6064,
            Race = "Dwarf",
            Zone = 1426,
            _index = 237,
        },
        {
            LearnSkill = { allAvailable = true, npcID = 1231 },
            Coord = { y = -5618.53, x = -454.06 },
            RaidIcon = 1231,
            Class = "HUNTER",
            MinLevel = 10,
            Race = "Dwarf",
            Zone = 1426,
            _index = 238,
        },
        {
            PickUp = { 6064 },
            Coord = { y = -5618.53, x = -454.06 },
            Class = "HUNTER",
            Race = "Dwarf",
            Zone = 1426,
            _index = 239,
        },
        {
            Qpart = { [6064] = { 1 } },
            Coord = { y = -5745.3, x = -576.69 },
            Button = { ["6064-1"] = 15911 },
            Class = "HUNTER",
            Race = "Dwarf",
            Zone = 1426,
            _index = 240,
        },
        {
            Done = { 6064 },
            Coord = { y = -5618.53, x = -454.06 },
            Class = "HUNTER",
            Race = "Dwarf",
            Zone = 1426,
            _index = 241,
        },
        {
            PickUp = { 6084 },
            Coord = { y = -5618.53, x = -454.06 },
            Class = "HUNTER",
            Race = "Dwarf",
            Zone = 1426,
            _index = 242,
        },
        {
            Qpart = { [6084] = { 1 } },
            Coord = { y = -5827.38, x = -630.87 },
            Button = { ["6084-1"] = 15913 },
            Class = "HUNTER",
            Race = "Dwarf",
            Zone = 1426,
            _index = 243,
        },
        {
            Done = { 6084 },
            Coord = { y = -5618.53, x = -454.06 },
            Class = "HUNTER",
            Race = "Dwarf",
            Zone = 1426,
            _index = 244,
        },
        {
            PickUp = { 6085 },
            Coord = { y = -5618.53, x = -454.06 },
            Class = "HUNTER",
            Race = "Dwarf",
            Zone = 1426,
            _index = 245,
        },
        {
            Qpart = { [6085] = { 1 } },
            Coord = { y = -5837.23, x = -680.12 },
            Button = { ["6085-1"] = 15908 },
            Class = "HUNTER",
            Race = "Dwarf",
            Zone = 1426,
            _index = 246,
        },
        {
            Done = { 6085 },
            Coord = { y = -5618.53, x = -454.06 },
            Class = "HUNTER",
            Race = "Dwarf",
            Zone = 1426,
            _index = 247,
        },
        {
            PickUp = { 6086 },
            Coord = { y = -5618.53, x = -454.06 },
            Class = "HUNTER",
            Race = "Dwarf",
            Zone = 1426,
            _index = 248,
        },
        {
            TameBeast = { npcID = 1201, spellID = 1515 },
            Coord = { y = -5827.38, x = -630.87 },
            Range = 45,
            Class = "HUNTER",
            HasSpell = 1515,
            IsQuestCompleted = 6085,
            IsQuestUncompleted = 6086,
            MinLevel = 10,
            Race = "Dwarf",
            Zone = 1426,
            _index = 249,
        },
        {
            Waypoint = 413,
            NonSkippableWaypoint = true,
            Coord = { y = -5609, x = -2165.6 },
            Range = 70,
            Zone = 1426,
            _index = 250,
        },
        {
            Waypoint = 413,
            NonSkippableWaypoint = true,
            Coord = { y = -5622.7, x = -2262.2 },
            Range = 20,
            Zone = 1426,
            _index = 251,
        },
        {
            Waypoint = 413,
            NonSkippableWaypoint = true,
            Coord = { y = -5558.7, x = -2350.7 },
            Range = 20,
            Zone = 1426,
            _index = 252,
        },
        {
            Done = { 413 },
            Coord = { y = -5479.74, x = -2447.11 },
            Zone = 1426,
            _index = 253,
        },
        {
            PickUp = { 414 },
            Coord = { y = -5479.74, x = -2447.11 },
            Zone = 1426,
            _index = 254,
        },
        {
            Waypoint = 414,

            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1432, 16.494, 58.424),
            Range = 20,
            Zone = 1432,
            _index = 255,
        },
        {
            Waypoint = 414,

            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1432, 19.594, 62.735),
            Range = 20,
            Zone = 1432,
            _index = 256,
        },
        {
            Waypoint = 414,

            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1432, 20.749, 64.326),
            Range = 20,
            Zone = 1432,
            _index = 257,
        },
        {
            Waypoint = 414,

            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1432, 21.106, 65.007),
            Range = 20,
            Zone = 1432,
            _index = 258,
        },
        {
            Waypoint = 414,

            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1432, 21.388, 66.357),
            Range = 20,
            Zone = 1432,
            _index = 259,
        },
        {
            Waypoint = 414,

            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1432, 21.498, 67.84),
            Range = 5,
            Zone = 1432,
            _index = 260,
        },
        {
            Grind = 10,
            ExtraLineText = "LEVEL_10_IS_REQUIRED_FOR_THE_LOCH_MODAN_STARTING_QUESTS",
            Coord = { y = -5832.73, x = -2602.54 },
            Range = 40,
            Zone = 1432,
            _index = 261,
        },
        {
            PickUp = { 224 },
            Coord = { y = -5832.73, x = -2602.54 },
            Zone = 1432,
            _index = 262,
        },
        {
            Waypoint = 414,
            NonSkippableWaypoint = true,
            Note = { "GET_INSIDE", ": ", "UPSTAIRS" },
            Coord = { y = -5879.14, x = -2635.61 },
            Range = 12,
            Zone = 1432,
            _index = 263,
        },
        {
            Waypoint = 414,
            NonSkippableWaypoint = true,
            Note = { "GET_INSIDE", ": ", "UPSTAIRS" },
            Coord = { y = -5874.91, x = -2645.27 },
            Range = 12,
            Zone = 1432,
            _index = 264,
        },
        {
            Waypoint = 414,
            NonSkippableWaypoint = true,
            Note = { "GET_INSIDE", ": ", "UPSTAIRS" },
            Coord = { y = -5847.5, x = -2631.48 },
            Range = 12,
            Zone = 1432,
            _index = 265,
        },
        {
            PickUp = { 267 },
            Coord = { y = -5842.81, x = -2634.59 },
            Zone = 1432,
            _index = 266,
        },
        {
            Waypoint = 414,
            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1432, 23.522, 70.102),
            Range = 40,
            Zone = 1432,
            _index = 267,
        },
        {
            Waypoint = 414,
            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1432, 27.501, 65.367),
            Range = 30,
            Zone = 1432,
            _index = 268,
        },
        {
            Waypoint = 414,
            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1432, 34.405, 48.276),
            Range = 5,
            Zone = 1432,
            _index = 269,
        },
        {
            Done = { 414 },
            Note = { "HE_PATROLS" },
            Coord = { y = -5337.39, x = -3007.99 },
            Zone = 1432,
            _index = 270,
        },
        {
            PickUp = { 416, 1339 },
            Note = { "HE_PATROLS" },
            NoArrow = true,
            _index = 271,
        },
        {
            Waypoint = 418,
            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1432, 35.273, 47.75),
            Range = 10,
            Zone = 1432,
            _index = 272,
        },
        {
            Waypoint = 418,
            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1432, 35.433, 48.243),
            Range = 12,
            Zone = 1432,
            _index = 273,
        },
        {
            PickUp = { 418 },
            Coord = { y = -5394.1, x = -2954.42 },
            Zone = 1432,
            _index = 274,
        },
        {
            SellItems = { junk = true },
            Coord = { y = -5381.87, x = -2952.46 },
            Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "WARLOCK", "WARRIOR" },
            Zone = 1432,
            _index = 275,
        },
        {
            BuyMerchant = { { itemID = 4470, quantity = 1 } },
            Note = { "MAKE_CAMPFIRES_ON_BOATS_TO_LEVEL_COOKING", "YOU_NEED_50_COOKING" },
            Coord = { y = -5381.87, x = -2952.46 },
            Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "WARLOCK", "WARRIOR" },
            HasSpell = 2550,
            ItemCount = { count = 1, itemID = 4470, operator = "<" },
            Money = { copper = 38, operator = ">=" },
            Skill = { operator = "<", skill = "cooking", rank = 50 },
            Zone = 1432,
            _index = 276,
        },
        {
            SellItems = { junk = true },
            Coord = { y = -5381.87, x = -2952.46 },
            Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "WARLOCK", "WARRIOR" },
            Zone = 1432,
            _index = 277,
        },
        {
            BuyMerchant = { { itemID = 4471, quantity = 1 } },
            Note = { "MAKE_CAMPFIRES_ON_BOATS_TO_LEVEL_COOKING", "YOU_NEED_50_COOKING" },
            Coord = { y = -5381.87, x = -2952.46 },
            Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "WARLOCK", "WARRIOR" },
            HasSpell = 2550,
            ItemCount = { count = 1, itemID = 4471, operator = "<" },
            Money = { copper = 135, operator = ">=" },
            Skill = { operator = "<", skill = "cooking", rank = 50 },
            Zone = 1432,
            _index = 278,
        },
        {
            SetHS = 418,
            Coord = { y = -5377.93, x = -2973.9 },
            Zone = 1432,
            _index = 279,
        },
        {
            Waypoint = 6387,
            NonSkippableWaypoint = true,
            Note = { "EXIT_BUILDING" },
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1432, 35.273, 47.75),
            Range = 10,
            Zone = 1432,
            _index = 280,
        },
        {
            PickUp = { 86667 },
            Coord = { y = -5376.02, x = -3003.3 },
            Class = "HUNTER",
            Race = "Dwarf",
            Zone = 1432,
            _index = 281,
        },
        {
            Waypoint = 6387,
            NonSkippableWaypoint = true,
            Coord = { y = -5369.4, x = -3019.02 },
            Range = 8,
            Zone = 1432,
            _index = 282,
        },
        {
            PickUp = { 6387 },
            Coord = { y = -5366.93, x = -3014.86 },
            Zone = 1432,
            _index = 283,
        },
        {
            Waypoint = 1339,
            NonSkippableWaypoint = true,
            Fillers = { [418] = { 1 } },
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1432, 23.49, 18.008),
            Range = 5,
            Zone = 1432,
            _index = 284,
        },
        {
            Waypoint = 1339,
            NonSkippableWaypoint = true,
            Note = { "GET_INSIDE", ": ", "UPSTAIRS" },
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1432, 23.49, 18.008),
            Range = 15,
            Zone = 1432,
            _index = 285,
        },
        {
            Waypoint = 1339,
            NonSkippableWaypoint = true,
            Note = { "GET_INSIDE", ": ", "UPSTAIRS" },
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1432, 24.279, 17.959),
            Range = 12,
            Zone = 1432,
            _index = 286,
        },
        {
            Done = { 1339 },
            Coord = { y = -4825.98, x = -2676.99 },
            Zone = 1432,
            _index = 287,
        },
        {
            PickUp = { 1338, 307 },
            Coord = { y = -4825.98, x = -2676.99 },
            Zone = 1432,
            _index = 288,
        },
        {
            UseHS = 418,
            Note = { "BUY_FOOD_IF_NEEDED" },
            ETA = 2,
            Class = { "ROGUE", "WARRIOR" },
            _index = 289,
        },
        {
            UseHS = 418,
            Note = { "BUY_FOOD_WATER_IF_NEEDED" },
            ETA = 2,
            Class = { "MAGE", "PALADIN", "PRIEST", "SHAMAN", "WARLOCK" },
            _index = 290,
        },
        {
            Qpart = { [418] = { 1 } },
            ExtraLineText = "COLLECT_THE_BOAR_BEAR_AND_SPIDER_INGREDIENTS",
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1432, 23.49, 18.008),
            Range = 90,
            Zone = 1432,
            _index = 291,
        },
        {
            Done = { 418 },
            Coord = { y = -5394.1, x = -2954.42 },
            Zone = 1432,
            _index = 292,
        },
        {
            GetFP = 8,
            Coord = { y = -5424.84, x = -2929.87 },
            Zone = 1432,
            _index = 293,
        },
        {
            Done = { 6387 },
            Coord = { y = -5424.84, x = -2929.87 },
            Zone = 1432,
            _index = 294,
        },
        {
            PickUp = { 6391 },
            Coord = { y = -5424.84, x = -2929.87 },
            Zone = 1432,
            _index = 295,
        },
        {
            UseFlightPath = 6391,
            NodeID = 6,
            Coord = { y = -5424.84, x = -2929.87 },
            SkipInZones = { 1455 },
            Zone = 1432,
            _index = 296,
        },
        {
            Waypoint = 6391,
            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1455, 56.714, 41.945),
            Range = 20,
            Zone = 1455,
            _index = 297,
        },
        {
            Waypoint = 6391,
            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1455, 55.748, 38.127),
            Range = 20,
            Zone = 1455,
            _index = 298,
        },
        {
            Waypoint = 6391,
            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1455, 51.569, 29.956),
            Range = 15,
            Zone = 1455,
            _index = 299,
        },
        {
            Waypoint = 6391,
            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1455, 49.645, 28.195),
            Range = 12,
            Zone = 1455,
            _index = 300,
        },
        {
            Waypoint = 6391,
            NonSkippableWaypoint = true,
            Coord = { y = -4708.06, x = -1120.93 },
            Range = 10,
            Zone = 1455,
            _index = 301,
        },
        {
            Done = { 6391 },
            Coord = { y = -4708.06, x = -1120.93 },
            Zone = 1455,
            _index = 302,
        },
        {
            PickUp = { 6388 },
            Coord = { y = -4708.06, x = -1120.93 },
            Zone = 1455,
            _index = 303,
        },
        {
            PickUp = { 94449 },
            Coord = { y = -4642.4, x = -1086.5 },
            RaidIcon = 258098,
            Class = "SHAMAN",
            MinLevel = 10,
            Race = "Dwarf",
            Zone = 1455,
            _index = 304,
        },
        {
            LearnSkill = { allAvailable = true, npcID = 258098 },
            Coord = { y = -4642.4, x = -1086.5 },
            RaidIcon = 258098,
            Class = "SHAMAN",
            MinLevel = 1,
            Race = "Dwarf",
            Zone = 1455,
            _index = 305,
        },
        {
            Waypoint = 291,
            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1455, 44.029, 50.074),
            Range = 20,
            Zone = 1455,
            _index = 306,
        },
        {
            Waypoint = 291,
            NonSkippableWaypoint = true,
            Coord = { y = -4872.56, x = -1026.28 },
            Range = 12,
            Zone = 1455,
            _index = 307,
        },
        {
            Done = { 291 },
            Coord = { y = -4872.56, x = -1026.28 },
            Zone = 1455,
            _index = 308,
        },
        {
            GetFP = 6,
            Coord = { y = -4821.13, x = -1152.4 },
            Zone = 1455,
            _index = 309,
        },
        {
            Done = { 6388 },
            Coord = { y = -4821.13, x = -1152.4 },
            Zone = 1455,
            _index = 310,
        },
        {
            PickUp = { 6392 },
            Coord = { y = -4821.13, x = -1152.4 },
            Zone = 1455,
            _index = 311,
        },
        {
            LearnSkill = { spellID = 2567, npcID = 13084 },
            Coord = { y = -5041.49, x = -1197.27 },
            Class = "WARRIOR",
            MinLevel = 1,
            Money = { copper = 1000, operator = ">=" },
            Zone = 1455,
            _index = 312,
        },
        {
            LearnSkill = { spellID = 199, npcID = 11865 },
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1455, 61.6, 89.4),
            Class = "WARRIOR",
            MinLevel = 1,
            Money = { copper = 1000, operator = ">=" },
            Zone = 1455,
            _index = 313,
        },
        {
            Waypoint = 6086,
            NonSkippableWaypoint = true,
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1455, 66.847, 83.366),
            Range = 15,
            Class = "HUNTER",
            Race = "Dwarf",
            Zone = 1455,
            _index = 314,
        },
        {
            Waypoint = 6086,
            NonSkippableWaypoint = true,
            Coord = { y = -5022.08, x = -1273.83 },
            Range = 15,
            Class = "HUNTER",
            Race = "Dwarf",
            Zone = 1455,
            _index = 315,
        },
        {
            Done = { 6086 },
            Coord = { y = -5022.08, x = -1273.83 },
            Class = "HUNTER",
            Race = "Dwarf",
            Zone = 1455,
            _index = 316,
        },
        {
            LearnSkill = { allAvailable = true, npcID = 10090 },
            Coord = { y = -5022.08, x = -1273.83 },
            RaidIcon = 10090,
            Class = "HUNTER",
            MinLevel = 1,
            Race = "Dwarf",
            Zone = 1455,
            _index = 317,
        },
        {
            PickUp = { 5639 },
            Coord = { y = -4607.2, x = -897.2 },
            RaidIcon = 11406,
            Class = "PRIEST",
            MinLevel = 10,
            Race = "Dwarf",
            Zone = 1455,
            _index = 318,
        },
        {
            LearnSkill = { allAvailable = true, npcID = 11406 },
            Coord = { y = -4607.2, x = -897.2 },
            RaidIcon = 11406,
            Class = "PRIEST",
            MinLevel = 1,
            Race = "Dwarf",
            Zone = 1455,
            _index = 319,
        },
        {
            SetHS = 6661,
            Coord = { y = -4841.49, x = -856.69 },
            Class = "PALADIN",
            Race = "Dwarf",
            Zone = 1455,
            _index = 320,
        },
        {
            UseFlightPath = 6392,
            NodeID = 8,
            Coord = { y = -4821.13, x = -1152.4 },
            Class = "HUNTER",
            Race = "Dwarf",
            SkipInZones = { 1432 },
            Zone = 1455,
            _index = 321,
        },
        {
            Waypoint = 6661,
            NonSkippableWaypoint = true,
            Note = { "ENTER_TRAM" },
            Coord = { y = -4840.43, x = -1330.28 },
            Range = 5,
            Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "WARLOCK", "WARRIOR" },
            Zone = 1455,
            _index = 322,
        },
        {
            PickUp = { 6661 },
            NoArrow = true,
            Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "WARLOCK", "WARRIOR" },
            _index = 323,
        },
        {
            Qpart = { [6661] = { 1 } },
            Button = { ["6661-1"] = 17117 },
            NoArrow = true,
            Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "WARLOCK", "WARRIOR" },
            _index = 324,
        },
        {
            Done = { 6661 },
            NoArrow = true,
            Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "WARLOCK", "WARRIOR" },
            _index = 325,
        },
        {
            PickUp = { 6662 },
            ETA = 11,
            Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "WARLOCK", "WARRIOR" },
            _index = 326,
        },
        {
            Done = { 6662 },
            ExtraLineText = "TAKE_THE_DEEPRUN_TRAM_TO_STORMWIND_AND_DELIVER_THE_RATS_ON_ARRIVAL",
            NoArrow = true,
            Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "WARLOCK", "WARRIOR" },
            _index = 327,
        },
        {
            Done = { 5639 },
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1453, 38.8, 26.4),
            RaidIcon = 376,
            Class = "PRIEST",
            IsQuestOnQuest = 5639,
            Race = "Dwarf",
            Zone = 1453,
            _index = 328,
        },
        {
            Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "WARLOCK", "WARRIOR" },
            Zone = 1453,
            _index = 329,
        },
        {
            PickUp = { 353 },
            Coord = { y = -8387.23, x = 685.22 },
            Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "WARLOCK", "WARRIOR" },
            Zone = 1453,
            _index = 330,
        },
        {
            Done = { 1338 },
            Coord = { y = -8427.22, x = 600.07 },
            Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "WARLOCK", "WARRIOR" },
            Zone = 1453,
            _index = 331,
        },
        {
            Waypoint = 1638,
            NonSkippableWaypoint = true,
            Coord = { y = -8728.28, x = 358.25 },
            Range = 15,
            Class = "WARRIOR",
            Zone = 1453,
            _index = 332,
        },
        {
            Waypoint = 1638,
            NonSkippableWaypoint = true,
            Coord = { y = -8685.53, x = 302.6 },
            Range = 15,
            Class = "WARRIOR",
            Zone = 1453,
            _index = 333,
        },
        {
            LearnSkill = { allAvailable = true, npcID = 5480 },
            Coord = { y = -8688.59, x = 325.68 },
            RaidIcon = 5480,
            Class = "WARRIOR",
            MinLevel = 1,
            Zone = 1453,
            _index = 334,
        },
        {
            PickUp = { 1638 },
            Coord = { y = -8688.59, x = 325.68 },
            Class = "WARRIOR",
            Zone = 1453,
            _index = 335,
        },
        {
            Waypoint = 1638,
            NonSkippableWaypoint = true,
            Note = { "GET_INSIDE", ": ", "TAVERN" },
            Coord = { y = -8741.21, x = 401.29 },
            Range = 17,
            Class = "WARRIOR",
            Zone = 1453,
            _index = 336,
        },
        {
            Waypoint = 1638,
            NonSkippableWaypoint = true,
            Note = { "GET_INSIDE", ": ", "TAVERN" },
            Coord = { y = -8636.5, x = 417.13 },
            Range = 12,
            Class = "WARRIOR",
            Zone = 1453,
            _index = 337,
        },
        {
            Done = { 1638 },
            Coord = { y = -8612.69, x = 382.86 },
            Class = "WARRIOR",
            Zone = 1453,
            _index = 338,
        },
        {
            PickUp = { 1639 },
            Coord = { y = -8612.69, x = 382.86 },
            Class = "WARRIOR",
            Zone = 1453,
            _index = 339,
        },
        {
            Done = { 1639 },
            Coord = { y = -8604.43, x = 389.07 },
            Class = "WARRIOR",
            Zone = 1453,
            _index = 340,
        },
        {
            PickUp = { 1640 },
            Coord = { y = -8604.43, x = 389.07 },
            Class = "WARRIOR",
            Zone = 1453,
            _index = 341,
        },
        {
            Qpart = { [1640] = { 1 } },
            Coord = { y = -8604.43, x = 389.07 },
            Range = 10,
            Class = "WARRIOR",
            Zone = 1453,
            _index = 342,
        },
        {
            Done = { 1640 },
            Coord = { y = -8604.43, x = 389.07 },
            Class = "WARRIOR",
            Zone = 1453,
            _index = 343,
        },
        {
            PickUp = { 1665 },
            Coord = { y = -8604.43, x = 389.07 },
            Class = "WARRIOR",
            Zone = 1453,
            _index = 344,
        },
        {
            Done = { 1665 },
            Coord = { y = -8612.69, x = 382.86 },
            Class = "WARRIOR",
            Zone = 1453,
            _index = 345,
        },
        {
            Waypoint = 40,
            NonSkippableWaypoint = true,
            Coord = { y = -8942.15, x = 988.44 },
            Range = 20,
            Class = "WARLOCK",
            Race = "Gnome",
            Zone = 1453,
            _index = 346,
        },
        {
            Waypoint = 40,
            NonSkippableWaypoint = true,
            Coord = { y = -8978.9, x = 1015.33 },
            Range = 15,
            Class = "WARLOCK",
            Race = "Gnome",
            Zone = 1453,
            _index = 347,
        },
        {
            LearnSkill = { allAvailable = true, npcID = 461 },
            Coord = { y = -8971.06, x = 1029.89 },
            RaidIcon = 461,
            Class = "WARLOCK",
            MinLevel = 1,
            Race = "Gnome",
            Zone = 1453,
            _index = 348,
        },
        {
            PickUp = { 1688 },
            Coord = { y = -8983.29, x = 1041.54 },
            Class = "WARLOCK",
            Race = "Gnome",
            Zone = 1453,
            _index = 349,
        },
        {
            LearnSkill = { spellID = 202, npcID = 11867 },
            Coord = { y = -8796.03, x = 613 },
            Class = { "PALADIN", "WARRIOR" },
            MinLevel = 1,
            Money = { copper = 1000, operator = ">=" },
            Zone = 1453,
            _index = 350,
        },
        {
            LearnSkill = { spellID = 201, npcID = 11867 },
            Coord = { y = -8796.03, x = 613 },
            Class = { "MAGE", "ROGUE" },
            MinLevel = 1,
            Money = { copper = 1000, operator = ">=" },
            Zone = 1453,
            _index = 351,
        },
        {
            LearnSkill = { spellID = 227, npcID = 11867 },
            Coord = { y = -8796.03, x = 613 },
            Class = "PRIEST",
            MinLevel = 1,
            Money = { copper = 1000, operator = ">=" },
            Zone = 1453,
            _index = 352,
        },
        {
            LearnSkill = { spellID = 201, npcID = 11867 },
            Coord = { y = -8796.03, x = 613 },
            Class = "WARLOCK",
            MinLevel = 1,
            Money = { copper = 1000, operator = ">=" },
            Race = "Gnome",
            Zone = 1453,
            _index = 353,
        },
        {
            LearnSkill = { spellID = 227, npcID = 11867 },
            Coord = { y = -8796.03, x = 613 },
            Class = "WARLOCK",
            MinLevel = 1,
            Money = { copper = 1000, operator = ">=" },
            Race = "Gnome",
            Zone = 1453,
            _index = 354,
        },
        {
            RouteCompleted = true,
            _index = 355,
        },
    },
    parallelSteps = {
        {
            conditions = { ItemCount = { itemID = 2946, count = 1 }, EquippedItemStat = { allowMissing = true, slot = 18, value = 3, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" }, Class = "ROGUE", EquippedItem = { invert = true, itemID = 2946, slot = 18 }, MinLevel = 3 },
            steps = {
                {
                    EquipItem = { itemID = 2946, slot = 18 },
                    EquippedItemStat = { allowMissing = true, slot = 18, value = 3, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" },
                    ItemCount = { itemID = 2946, count = 1 },
                    MinLevel = 3,
                    _index = 356,
                },
            },
        },
        {
            conditions = { ItemCount = { itemID = 2488, count = 1 }, EquippedItemStat = { allowMissing = true, slot = 16, value = 3.79, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" }, MinLevel = 4, Class = "WARRIOR", EquippedItem = { invert = true, itemID = 2488, slot = 16 }, Race = "Gnome" },
            steps = {
                {
                    EquipItem = { itemID = 2488, slot = 16 },
                    EquippedItemStat = { allowMissing = true, slot = 16, value = 3.79, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" },
                    ItemCount = { itemID = 2488, count = 1 },
                    MinLevel = 4,
                    _index = 357,
                },
            },
        },
        {
            conditions = { ItemCount = { itemID = 2491, count = 1 }, EquippedItemStat = { allowMissing = true, slot = 16, value = 4.29, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" }, MinLevel = 3, Class = "WARRIOR", EquippedItem = { invert = true, itemID = 2491, slot = 16 }, Race = "Dwarf" },
            steps = {
                {
                    EquipItem = { itemID = 2491, slot = 16 },
                    EquippedItemStat = { allowMissing = true, slot = 16, value = 4.29, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" },
                    ItemCount = { itemID = 2491, count = 1 },
                    MinLevel = 3,
                    _index = 358,
                },
            },
        },
        {
            conditions = { ItemCount = { itemID = 2494, count = 1 }, EquippedItemStat = { allowMissing = true, slot = 16, value = 3.29, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" }, Class = "ROGUE", EquippedItem = { invert = true, itemID = 2494, slot = 16 }, MinLevel = 3 },
            steps = {
                {
                    EquipItem = { itemID = 2494, slot = 16 },
                    EquippedItemStat = { allowMissing = true, slot = 16, value = 3.29, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" },
                    ItemCount = { itemID = 2494, count = 1 },
                    MinLevel = 3,
                    _index = 359,
                },
            },
        },
        {
            conditions = { ItemCount = { itemID = 2495, count = 1 }, EquippedItemStat = { allowMissing = true, slot = 16, value = 4.2, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" }, MinLevel = 3, Class = "SHAMAN", EquippedItem = { invert = true, itemID = 2495, slot = 16 }, Race = "Dwarf" },
            steps = {
                {
                    EquipItem = { itemID = 2495, slot = 16 },
                    EquippedItemStat = { allowMissing = true, slot = 16, value = 4.2, precision = 1, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<" },
                    ItemCount = { itemID = 2495, count = 1 },
                    MinLevel = 3,
                    _index = 360,
                },
            },
        },
        {
            conditions = { ItemCount = { itemID = 2509, count = 1 }, EquippedItemStat = { slot = 18, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 2.95, precision = 2, allowMissing = true }, Class = "HUNTER", EquippedItem = { itemID = 2509, slot = 18, invert = true }, MinLevel = 4, Race = "Dwarf" },
            steps = {
                {
                    EquipItem = { itemID = 2509, slot = 18 },
                    EquippedItemStat = { slot = 18, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 2.95, precision = 2, allowMissing = true },
                    ItemCount = { itemID = 2509, count = 1 },
                    MinLevel = 4,
                    _index = 361,
                },
            },
        },
    },
}
