-- Generated locally by the APR route converter.
APR.RouteQuestStepList["Forever-Generated-Alliance-Westfall"] = {
    label = "Alliance - Westfall - generated",
    expansion = APR.EXPANSIONS.Forever,
    gameVersion = APR.GAME_VERSIONS.Forever,
    category = APR.CATEGORIES.Leveling,
    mapID = 1436,
    conditions = { Race = { APR.RACES.Dwarf, APR.RACES.Gnome, APR.RACES.Human, APR.RACES.Skyborne }, Class = { APR.Classes.Druid, APR.Classes.Mage, APR.Classes.Paladin, APR.Classes.Priest, APR.Classes.Rogue, APR.Classes.Shaman, APR.Classes.Warlock, APR.Classes.Warrior }, Faction = "Alliance" },
    nextRoute = { "Forever-Generated-Alliance-Darkshore" },
    prefab = { [APR.PREFAB_TYPES.Leveling] = { index = 15 }, [APR.PREFAB_TYPES.Speedrun] = { index = 15 } },
    steps = {
        {
            SetHS = 6261,
            Coord = { x = 673.58, y = -8867.76 },
            Race = "Human",
            SkipForLvl = 15,
            Zone = 1453,
            _index = 1,
        },
        {
            SetHS = 36,
            AnyOf = { { SkipForLvl = 15, Race = "Dwarf" }, { SkipForLvl = 15, Race = "Gnome" }, { SkipForLvl = 15, Race = "Skyborne" } },
            Coord = { x = 673.58, y = -8867.76 },
            Zone = 1453,
            _index = 2,
        },
        {
            Note = { "If you don't want to or can't do this, skip this step", "`Stringy Vulture Meat`", "`Murloc Eye`", "`Goretusk Snout`", "`Okra`", "`Goretusk Liver`", "`Golem Isospring`", "`Harvester Gyrostabilizer`" },
            BuyMerchant = { { itemID = 729, quantity = 3, questID = 38 } },
            Coord = { x = 660.28, y = -8814.55 },
            ItemCount = { itemID = 729, count = 3, operator = "<" },
            SkipForLvl = 15,
            Zone = 1453,
            _index = 3,
        },
        {
            Note = { "If you don't want to or can't do this, skip this step", "`Stringy Vulture Meat`", "`Murloc Eye`", "`Goretusk Snout`", "`Okra`", "`Goretusk Liver`", "`Golem Isospring`", "`Harvester Gyrostabilizer`" },
            BuyMerchant = { { itemID = 730, quantity = 3, questID = 38 } },
            Coord = { x = 660.28, y = -8814.55 },
            ItemCount = { itemID = 730, count = 3, operator = "<" },
            SkipForLvl = 15,
            Zone = 1453,
            _index = 4,
        },
        {
            Note = { "If you don't want to or can't do this, skip this step", "`Stringy Vulture Meat`", "`Murloc Eye`", "`Goretusk Snout`", "`Okra`", "`Goretusk Liver`", "`Golem Isospring`", "`Harvester Gyrostabilizer`" },
            BuyMerchant = { { itemID = 731, quantity = 3, questID = 38 } },
            Coord = { x = 660.28, y = -8814.55 },
            ItemCount = { itemID = 731, count = 3, operator = "<" },
            SkipForLvl = 15,
            Zone = 1453,
            _index = 5,
        },
        {
            Note = { "If you don't want to or can't do this, skip this step", "`Stringy Vulture Meat`", "`Murloc Eye`", "`Goretusk Snout`", "`Okra`", "`Goretusk Liver`", "`Golem Isospring`", "`Harvester Gyrostabilizer`" },
            BuyMerchant = { { itemID = 732, quantity = 3, questID = 38 } },
            Coord = { x = 660.28, y = -8814.55 },
            ItemCount = { itemID = 732, count = 3, operator = "<" },
            SkipForLvl = 15,
            Zone = 1453,
            _index = 6,
        },
        {
            Note = { "If you don't want to or can't do this, skip this step", "`Stringy Vulture Meat`", "`Murloc Eye`", "`Goretusk Snout`", "`Okra`", "`Goretusk Liver`", "`Golem Isospring`", "`Harvester Gyrostabilizer`" },
            BuyMerchant = { { itemID = 723, quantity = 8, questID = 22 } },
            Coord = { x = 660.28, y = -8814.55 },
            ItemCount = { itemID = 723, count = 8, operator = "<" },
            SkipForLvl = 15,
            Zone = 1453,
            _index = 7,
        },
        {
            Note = { "If you don't want to or can't do this, skip this step", "`Stringy Vulture Meat`", "`Murloc Eye`", "`Goretusk Snout`", "`Okra`", "`Goretusk Liver`", "`Golem Isospring`", "`Harvester Gyrostabilizer`" },
            BuyMerchant = { { itemID = 255007, quantity = 14, questID = 92909 } },
            Coord = { x = 660.28, y = -8814.55 },
            ItemCount = { itemID = 255007, count = 14, operator = "<" },
            SkipForLvl = 15,
            Zone = 1453,
            _index = 8,
        },
        {
            Note = { "If you don't want to or can't do this, skip this step", "`Stringy Vulture Meat`", "`Murloc Eye`", "`Goretusk Snout`", "`Okra`", "`Goretusk Liver`", "`Golem Isospring`", "`Harvester Gyrostabilizer`" },
            BuyMerchant = { { itemID = 255010, quantity = 5, questID = 92909 } },
            Coord = { x = 660.28, y = -8814.55 },
            ItemCount = { itemID = 255010, count = 5, operator = "<" },
            SkipForLvl = 15,
            Zone = 1453,
            _index = 9,
        },
        {
            Done = { 6261 },
            Coord = { x = 489.99, y = -8835.76 },
            Race = "Human",
            Zone = 1453,
            _index = 10,
        },
        {
            PickUp = { 6285 },
            Coord = { x = 489.99, y = -8835.76 },
            Race = "Human",
            Zone = 1453,
            _index = 11,
        },
        {
            UseFlightPath = 36,
            Coord = { x = 490.03, y = -8835.82 },
            NodeID = 4,
            Race = { "Dwarf", "Gnome", "Human" },
            SkipForLvl = 15,
            Zone = 1453,
            _index = 12,
        },
        {
            Waypoint = 36,
            Coord = { x = 875.96, y = -9814.4 },
            NonSkippableWaypoint = true,
            Range = 5,
            SkipForLvl = 15,
            Zone = 1429,
            _index = 13,
        },
        {
            PickUp = { 64 },
            Coord = { x = 918.42, y = -9851.5 },
            Zone = 1436,
            _index = 14,
        },
        {
            PickUp = { 36, 151 },
            Coord = { x = 919.47, y = -9853.13 },
            Zone = 1436,
            _index = 15,
        },
        {
            Waypoint = 36,
            Coord = { x = 1055.27, y = -10128.7 },
            NonSkippableWaypoint = true,
            Range = 65.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 16,
        },
        {
            PickUp = { 9 },
            Coord = { x = 1055.27, y = -10128.7 },
            Zone = 1436,
            _index = 17,
        },
        {
            Done = { 36 },
            Coord = { x = 1042.67, y = -10111.67 },
            Zone = 1436,
            _index = 18,
        },
        {
            PickUp = { 38, 22 },
            Coord = { x = 1042.67, y = -10111.67 },
            Zone = 1436,
            _index = 19,
        },
        {
            Done = { 6285 },
            Coord = { x = 1021.67, y = -10500.63 },
            Race = "Human",
            Zone = 1436,
            _index = 20,
        },
        {
            Done = { 109 },
            Coord = { x = 1045.12, y = -10508.8 },
            Race = { "Dwarf", "Gnome" },
            Zone = 1436,
            _index = 21,
        },
        {
            PickUp = { 12 },
            Coord = { x = 1045.12, y = -10508.8 },
            Race = { "Dwarf", "Gnome", "Human" },
            Zone = 1436,
            _index = 22,
        },
        {
            PickUp = { 12 },
            Coord = { x = 1045.12, y = -10508.8 },
            Race = "Skyborne",
            Zone = 1436,
            _index = 23,
        },
        {
            Done = { 98021 },
            Coord = { x = 1045.12, y = -10508.8 },
            Race = "Skyborne",
            Zone = 1436,
            _index = 24,
        },
        {
            PickUp = { 102 },
            Coord = { x = 1041.97, y = -10511.13 },
            Zone = 1436,
            _index = 25,
        },
        {
            PickUp = { 153 },
            Coord = { x = 1126.67, y = -10636.67 },
            Race = "Human",
            Zone = 1436,
            _index = 26,
        },
        {
            PickUp = { 153 },
            Coord = { x = 1126.67, y = -10636.67 },
            Race = { "Dwarf", "Gnome", "Skyborne" },
            Zone = 1436,
            _index = 27,
        },
        {
            Waypoint = 64,
            Note = { "Buy food/water if needed" },
            Coord = { x = 1166.57, y = -10653.23 },
            NonSkippableWaypoint = true,
            Range = 5,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 28,
        },
        {
            PickUp = { 92742, 92744 },
            Coord = { x = 1179.8, y = -10635.601 },
            RaidIcon = 253092,
            Zone = 1436,
            _index = 29,
        },
        {
            Waypoint = 399,
            Note = { "Work on completing the other quest objectives as you move there" },
            Coord = { x = 1602.67, y = -10629.67 },
            IsQuestOnQuest = 399,
            NonSkippableWaypoint = true,
            Range = 75.0,
            Zone = 1436,
            _index = 30,
        },
        {
            Qpart = { [399] = { 1 } },
            Note = { "Open Alexston's Chest. Loot it for A Simple Compass" },
            Coord = { x = 1748.27, y = -10672.13 },
            Zone = 1436,
            _index = 31,
        },
        {
            Qpart = { [92742] = { 2 } },
            Note = { "Use the `Well Water Sample Kit` at the Molsen Farm well" },
            Button = { ["92742-2"] = 254545 },
            Coord = { x = 1404.2, y = -10290.9 },
            Zone = 1436,
            _index = 32,
        },
        {
            Waypoint = 64,
            Coord = { x = 1266.67, y = -9927.33 },
            NonSkippableWaypoint = true,
            Range = 75.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 33,
        },
        {
            Qpart = { [64] = { 1 } },
            Note = { "Open Furlbrow's Wardrobe. Loot it for Furlbrow's Pocket Watch", "You can loot Furlbrow's Wardrobe from outside if you angle your camera correctly", "Be aware of Benny Blanco. He hits hard" },
            Coord = { x = 1289.77, y = -9849.63 },
            Zone = 1436,
            _index = 34,
        },
        {
            Waypoint = 102,
            Note = { "Kill Riverpaw Gnolls and Riverpaw Scouts. Loot them for their Gnoll Paws" },
            Coord = { x = 1042.67, y = -9715.0 },
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 35,
        },
        {
            Waypoint = 102,
            Note = { "Kill Riverpaw Gnolls and Riverpaw Scouts. Loot them for their Gnoll Paws" },
            Coord = { x = 1517.97, y = -9743.0 },
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 36,
        },
        {
            Waypoint = 102,
            Note = { "Kill Riverpaw Gnolls and Riverpaw Scouts. Loot them for their Gnoll Paws" },
            Coord = { x = 1412.62, y = -9720.83 },
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 37,
        },
        {
            Waypoint = 102,
            Note = { "Kill Riverpaw Gnolls and Riverpaw Scouts. Loot them for their Gnoll Paws" },
            Coord = { x = 1184.07, y = -9745.8 },
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 38,
        },
        {
            Waypoint = 102,
            Note = { "Kill Riverpaw Gnolls and Riverpaw Scouts. Loot them for their Gnoll Paws" },
            Coord = { x = 1026.57, y = -9715.7 },
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 39,
        },
        {
            Waypoint = 102,
            Note = { "Kill Riverpaw Gnolls and Riverpaw Scouts. Loot them for their Gnoll Paws" },
            Coord = { x = 1026.57, y = -9715.7 },
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 40,
        },
        {
            Waypoint = 102,
            Note = { "Kill Riverpaw Gnolls and Riverpaw Scouts. Loot them for their Gnoll Paws" },
            Coord = { x = 1517.97, y = -9743.0 },
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 41,
        },
        {
            Waypoint = 102,
            Note = { "Kill Riverpaw Gnolls and Riverpaw Scouts. Loot them for their Gnoll Paws" },
            Coord = { x = 1184.07, y = -9745.8 },
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 42,
        },
        {
            Qpart = { [102] = { 1 } },
            Coord = { x = 1028.32, y = -9710.33 },
            Range = 30,
            Zone = 1436,
            _index = 43,
        },
        {
            Waypoint = 92744,
            Note = { "Kill Murloc Raiders and Murloc Coastrunners. Loot them for their Eyes and Gills" },
            Coord = { x = 1192.12, y = -9641.73 },
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 44,
        },
        {
            Waypoint = 92744,
            Note = { "Kill Murloc Raiders and Murloc Coastrunners. Loot them for their Eyes and Gills" },
            Coord = { x = 1042.67, y = -9619.33 },
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 45,
        },
        {
            Waypoint = 92744,
            Note = { "Kill Murloc Raiders and Murloc Coastrunners. Loot them for their Eyes and Gills" },
            Coord = { x = 1192.12, y = -9641.73 },
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 46,
        },
        {
            Waypoint = 92744,
            Note = { "Kill Murloc Raiders and Murloc Coastrunners. Loot them for their Eyes and Gills" },
            Coord = { x = 1042.67, y = -9619.33 },
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 47,
        },
        {
            Note = { "Kill Murloc Raiders and Murloc Coastrunners. Loot them for their Eyes and Gills" },
            LootItems = { { itemID = 730, quantity = 3, questID = 38 } },
            Coord = { x = 1042.67, y = -9619.33 },
            SkipForLvl = 15,
            Zone = 1436,
            _index = 48,
        },
        {
            Qpart = { [92744] = { 1 } },
            Coord = { x = 1042.67, y = -9619.33 },
            Range = 30,
            Zone = 1436,
            _index = 49,
        },
        {
            Waypoint = 151,
            Note = { "Open the Sacks of Oats on the ground. Loot them for the Handful of Oats", "You can usually find them near Farm Fences or Buildings" },
            Coord = { x = 1004.87, y = -9716.87 },
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 50,
        },
        {
            Waypoint = 151,
            Note = { "Open the Sacks of Oats on the ground. Loot them for the Handful of Oats", "You can usually find them near Farm Fences or Buildings" },
            Coord = { x = 1013.62, y = -9861.53 },
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 51,
        },
        {
            Waypoint = 151,
            Note = { "Open the Sacks of Oats on the ground. Loot them for the Handful of Oats", "You can usually find them near Farm Fences or Buildings" },
            Coord = { x = 1192.12, y = -10175.13 },
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 52,
        },
        {
            Waypoint = 151,
            Note = { "Open the Sacks of Oats on the ground. Loot them for the Handful of Oats", "You can usually find them near Farm Fences or Buildings" },
            Coord = { x = 1019.57, y = -10204.3 },
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 53,
        },
        {
            Qpart = { [151] = { 1 } },
            Note = { "Open the Sacks of Oats on the ground. Loot them for the Handful of Oats", "You can usually find them near Farm Fences or Buildings" },
            Coord = { x = 1013.62, y = -9861.53 },
            Zone = 1436,
            _index = 54,
        },
        {
            Qpart = { [92742] = { 1 } },
            Note = { "Use the `Well Water Sample Kit` at the Jansen Stead well" },
            Button = { ["92742-1"] = 254545 },
            Coord = { x = 1035.3, y = -9835.101 },
            Zone = 1436,
            _index = 55,
        },
        {
            Waypoint = 64,
            Class = "WARLOCK",
            Coord = { x = 918.42, y = -9851.5 },
            IsQuestOnQuest = 184,
            NonSkippableWaypoint = true,
            Race = "Human",
            Range = 5,
            Zone = 1436,
            _index = 56,
        },
        {
            Done = { 64 },
            Class = "WARLOCK",
            Coord = { x = 919.47, y = -9853.13 },
            IsQuestOnQuest = 184,
            Race = "Human",
            Zone = 1436,
            _index = 57,
        },
        {
            Done = { 184 },
            Class = "WARLOCK",
            Coord = { x = 919.47, y = -9853.13 },
            Race = "Human",
            Zone = 1436,
            _index = 58,
        },
        {
            Qpart = { [151] = { 1 } },
            Note = { "Open the Sacks of Oats on the ground. Loot them for the Handful of Oats", "You can usually find them near Farm Fences or Buildings" },
            Class = "WARLOCK",
            IsQuestOnQuest = 184,
            Race = "Human",
            _index = 59,
        },
        {
            Done = { 151 },
            Class = "WARLOCK",
            Coord = { x = 919.47, y = -9853.13 },
            IsQuestOnQuest = 184,
            Race = "Human",
            Zone = 1436,
            _index = 60,
        },
        {
            Waypoint = 64,
            AnyOf = { { Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "WARRIOR" } }, { Race = "Dwarf" }, { Race = "Gnome" }, { Race = "Skyborne" } },
            Coord = { x = 918.42, y = -9851.5 },
            NonSkippableWaypoint = true,
            Range = 5,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 61,
        },
        {
            Done = { 64 },
            AnyOf = { { Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "WARRIOR" } }, { Race = "Dwarf" }, { Race = "Gnome" }, { Race = "Skyborne" } },
            Coord = { x = 919.47, y = -9853.13 },
            Zone = 1436,
            _index = 62,
        },
        {
            Qpart = { [151] = { 1 } },
            Note = { "Open the Sacks of Oats on the ground. Loot them for the Handful of Oats", "You can usually find them near Farm Fences or Buildings" },
            AnyOf = { { Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "WARRIOR" } }, { Race = "Dwarf" }, { Race = "Gnome" }, { Race = "Skyborne" } },
            _index = 63,
        },
        {
            Done = { 151 },
            AnyOf = { { Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "WARRIOR" } }, { Race = "Dwarf" }, { Race = "Gnome" }, { Race = "Skyborne" } },
            Coord = { x = 919.47, y = -9853.13 },
            Zone = 1436,
            _index = 64,
        },
        {
            Waypoint = 64,
            Class = "WARLOCK",
            Coord = { x = 918.42, y = -9851.5 },
            NonSkippableWaypoint = true,
            Race = "Human",
            Range = 5,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 65,
        },
        {
            Done = { 64, 151 },
            Class = "WARLOCK",
            Coord = { x = 919.47, y = -9853.13 },
            Race = "Human",
            Zone = 1436,
            _index = 66,
        },
        {
            Note = { "Do NOT sell `Murloc Eyes`, `Goretusk Snouts`, `Goretusk Livers` or `Stringy Vulture Meat`" },
            SellItems = { junk = true, questID = 9 },
            Coord = { x = 1055.27, y = -10128.7 },
            SkipForLvl = 15,
            Zone = 1436,
            _index = 67,
        },
        {
            Qpart = { [9] = { 1 } },
            Note = { "Kill Harvest Watchers located on any of the fields as you run by them" },
            Range = 30,
            _index = 68,
        },
        {
            Done = { 9 },
            Coord = { x = 1055.27, y = -10128.7 },
            Zone = 1436,
            _index = 69,
        },
        {
            Qpart = { [22] = { 1 } },
            AnyOf = { { IsQuestOnQuest = 22, Race = "Human", SkipForLvl = 15, AllOf = { { IsQuestOnQuest = 38 }, { IsQuestReadyForTurnIn = 38 }, { IsQuestReadyForTurnIn = 22 }, { IsQuestUncompleted = 38 }, { IsQuestUncompleted = 22 } } }, { IsQuestOnQuest = 22, Race = "Dwarf", SkipForLvl = 15, AllOf = { { IsQuestOnQuest = 38 }, { IsQuestReadyForTurnIn = 38 }, { IsQuestReadyForTurnIn = 22 }, { IsQuestUncompleted = 38 }, { IsQuestUncompleted = 22 } } }, { IsQuestOnQuest = 22, Race = "Gnome", SkipForLvl = 15, AllOf = { { IsQuestOnQuest = 38 }, { IsQuestReadyForTurnIn = 38 }, { IsQuestReadyForTurnIn = 22 }, { IsQuestUncompleted = 38 }, { IsQuestUncompleted = 22 } } }, { IsQuestOnQuest = 22, Race = "Skyborne", SkipForLvl = 15, AllOf = { { IsQuestOnQuest = 38 }, { IsQuestReadyForTurnIn = 38 }, { IsQuestReadyForTurnIn = 22 }, { IsQuestUncompleted = 38 }, { IsQuestUncompleted = 22 } } } },
            _index = 70,
        },
        {
            Done = { 22 },
            AnyOf = { { SkipForLvl = 15, Race = "Human", AllOf = { { IsQuestOnQuest = 38 }, { IsQuestOnQuest = 22 }, { IsQuestReadyForTurnIn = 38 }, { IsQuestReadyForTurnIn = 22 }, { IsQuestUncompleted = 38 }, { IsQuestUncompleted = 22 } } }, { SkipForLvl = 15, Race = "Dwarf", AllOf = { { IsQuestOnQuest = 38 }, { IsQuestOnQuest = 22 }, { IsQuestReadyForTurnIn = 38 }, { IsQuestReadyForTurnIn = 22 }, { IsQuestUncompleted = 38 }, { IsQuestUncompleted = 22 } } }, { SkipForLvl = 15, Race = "Gnome", AllOf = { { IsQuestOnQuest = 38 }, { IsQuestOnQuest = 22 }, { IsQuestReadyForTurnIn = 38 }, { IsQuestReadyForTurnIn = 22 }, { IsQuestUncompleted = 38 }, { IsQuestUncompleted = 22 } } }, { SkipForLvl = 15, Race = "Skyborne", AllOf = { { IsQuestOnQuest = 38 }, { IsQuestOnQuest = 22 }, { IsQuestReadyForTurnIn = 38 }, { IsQuestReadyForTurnIn = 22 }, { IsQuestUncompleted = 38 }, { IsQuestUncompleted = 22 } } } },
            Coord = { x = 1042.67, y = -10111.67 },
            Zone = 1436,
            _index = 71,
        },
        {
            Qpart = { [38] = { 1 } },
            AnyOf = { { SkipForLvl = 15, Race = "Human", AllOf = { { IsQuestOnQuest = 38 }, { IsQuestOnQuest = 22 } }, IsQuestReadyForTurnIn = 22, IsQuestUncompleted = 22 }, { SkipForLvl = 15, Race = "Dwarf", AllOf = { { IsQuestOnQuest = 38 }, { IsQuestOnQuest = 22 } }, IsQuestReadyForTurnIn = 22, IsQuestUncompleted = 22 }, { SkipForLvl = 15, Race = "Gnome", AllOf = { { IsQuestOnQuest = 38 }, { IsQuestOnQuest = 22 } }, IsQuestReadyForTurnIn = 22, IsQuestUncompleted = 22 }, { SkipForLvl = 15, Race = "Skyborne", AllOf = { { IsQuestOnQuest = 38 }, { IsQuestOnQuest = 22 } }, IsQuestReadyForTurnIn = 22, IsQuestUncompleted = 22 } },
            _index = 72,
        },
        {
            Done = { 38 },
            AnyOf = { { SkipForLvl = 15, Race = "Human", IsQuestOnQuest = 22, IsQuestReadyForTurnIn = 22, IsQuestUncompleted = 22 }, { SkipForLvl = 15, Race = "Dwarf", IsQuestOnQuest = 22, IsQuestReadyForTurnIn = 22, IsQuestUncompleted = 22 }, { SkipForLvl = 15, Race = "Gnome", IsQuestOnQuest = 22, IsQuestReadyForTurnIn = 22, IsQuestUncompleted = 22 }, { SkipForLvl = 15, Race = "Skyborne", IsQuestOnQuest = 22, IsQuestReadyForTurnIn = 22, IsQuestUncompleted = 22 } },
            Coord = { x = 1042.67, y = -10111.67 },
            Zone = 1436,
            _index = 73,
        },
        {
            Done = { 22, 38 },
            Coord = { x = 1042.67, y = -10111.67 },
            Zone = 1436,
            _index = 74,
        },
        {
            PickUp = { 92909 },
            AnyOf = { { SkipForLvl = 15, Race = "Human", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } }, { SkipForLvl = 15, Race = "Dwarf", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } }, { SkipForLvl = 15, Race = "Gnome", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } }, { SkipForLvl = 15, Race = "Skyborne", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } } },
            Coord = { x = 1213.4, y = -10153.8 },
            RaidIcon = 253395,
            Zone = 1436,
            _index = 75,
        },
        {
            Done = { 92909 },
            AnyOf = { { SkipForLvl = 15, Race = "Human", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } }, { SkipForLvl = 15, Race = "Dwarf", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } }, { SkipForLvl = 15, Race = "Gnome", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } }, { SkipForLvl = 15, Race = "Skyborne", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } } },
            Coord = { x = 1213.4, y = -10153.8 },
            RaidIcon = 253395,
            Zone = 1436,
            _index = 76,
        },
        {
            Waypoint = 9,
            Note = { "Kill Harvest Watchers. Loot them for their Okra and Flasks of Oil" },
            Coord = { x = 1132.27, y = -10146.67 },
            IsQuestUncompleted = 38,
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 77,
        },
        {
            Waypoint = 9,
            Note = { "Kill Harvest Watchers. Loot them for their Okra and Flasks of Oil" },
            Coord = { x = 1238.67, y = -9907.73 },
            IsQuestUncompleted = 38,
            NonSkippableWaypoint = true,
            Range = 80.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 78,
        },
        {
            Waypoint = 9,
            Note = { "Kill Harvest Watchers. Loot them for their Okra and Flasks of Oil" },
            Coord = { x = 1460.22, y = -10224.83 },
            IsQuestUncompleted = 38,
            NonSkippableWaypoint = true,
            Range = 80.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 79,
        },
        {
            Waypoint = 9,
            Note = { "Kill Harvest Watchers. Loot them for their Okra and Flasks of Oil" },
            Coord = { x = 1132.27, y = -10146.67 },
            IsQuestUncompleted = 38,
            NonSkippableWaypoint = true,
            Range = 80.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 80,
        },
        {
            Waypoint = 9,
            Note = { "Kill Harvest Watchers. Loot them for their Okra and Flasks of Oil" },
            Coord = { x = 1238.67, y = -9907.73 },
            IsQuestUncompleted = 38,
            NonSkippableWaypoint = true,
            Range = 80.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 81,
        },
        {
            Waypoint = 9,
            Note = { "Kill Harvest Watchers. Loot them for their Okra and Flasks of Oil" },
            Coord = { x = 1460.22, y = -10224.83 },
            IsQuestUncompleted = 38,
            NonSkippableWaypoint = true,
            Range = 80.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 82,
        },
        {
            Waypoint = 9,
            Note = { "Kill Harvest Watchers. Loot them for their Okra and Flasks of Oil" },
            Coord = { x = 1132.27, y = -10146.67 },
            IsQuestUncompleted = 38,
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 83,
        },
        {
            Waypoint = 9,
            Note = { "Kill Harvest Watchers. Loot them for their Okra and Flasks of Oil" },
            Coord = { x = 1460.22, y = -10224.83 },
            IsQuestUncompleted = 38,
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 84,
        },
        {
            Qpart = { [9] = { 1 } },
            Coord = { x = 1238.67, y = -9907.73 },
            IsQuestUncompleted = 38,
            Range = 30,
            Zone = 1436,
            _index = 85,
        },
        {
            Note = { "Kill Harvest Watchers. Loot them for their Okra and Flasks of Oil" },
            LootItems = { { itemID = 732, quantity = 3, questID = 38 } },
            Coord = { x = 1238.67, y = -9907.73 },
            IsQuestUncompleted = 38,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 86,
        },
        {
            Note = { "Kill Harvest Watchers. Loot them for their Okra and Flasks of Oil" },
            LootItems = { { itemID = 814, quantity = 5, questID = 103 } },
            Coord = { x = 1238.67, y = -9907.73 },
            IsQuestUncompleted = 38,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 87,
        },
        {
            Waypoint = 9,
            Note = { "Kill Harvest Watchers. Loot them for their Flasks of Oil" },
            Coord = { x = 1132.27, y = -10146.67 },
            IsQuestCompleted = 38,
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 88,
        },
        {
            Waypoint = 9,
            Note = { "Kill Harvest Watchers. Loot them for their Flasks of Oil" },
            Coord = { x = 1238.67, y = -9907.73 },
            IsQuestCompleted = 38,
            NonSkippableWaypoint = true,
            Range = 80.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 89,
        },
        {
            Waypoint = 9,
            Note = { "Kill Harvest Watchers. Loot them for their Flasks of Oil" },
            Coord = { x = 1460.22, y = -10224.83 },
            IsQuestCompleted = 38,
            NonSkippableWaypoint = true,
            Range = 80.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 90,
        },
        {
            Waypoint = 9,
            Note = { "Kill Harvest Watchers. Loot them for their Flasks of Oil" },
            Coord = { x = 1132.27, y = -10146.67 },
            IsQuestCompleted = 38,
            NonSkippableWaypoint = true,
            Range = 80.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 91,
        },
        {
            Waypoint = 9,
            Note = { "Kill Harvest Watchers. Loot them for their Flasks of Oil" },
            Coord = { x = 1238.67, y = -9907.73 },
            IsQuestCompleted = 38,
            NonSkippableWaypoint = true,
            Range = 80.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 92,
        },
        {
            Waypoint = 9,
            Note = { "Kill Harvest Watchers. Loot them for their Flasks of Oil" },
            Coord = { x = 1460.22, y = -10224.83 },
            IsQuestCompleted = 38,
            NonSkippableWaypoint = true,
            Range = 80.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 93,
        },
        {
            Waypoint = 9,
            Note = { "Kill Harvest Watchers. Loot them for their Flasks of Oil" },
            Coord = { x = 1132.27, y = -10146.67 },
            IsQuestCompleted = 38,
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 94,
        },
        {
            Waypoint = 9,
            Note = { "Kill Harvest Watchers. Loot them for their Flasks of Oil" },
            Coord = { x = 1460.22, y = -10224.83 },
            IsQuestCompleted = 38,
            NonSkippableWaypoint = true,
            Range = 60.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 95,
        },
        {
            Qpart = { [9] = { 1 } },
            Coord = { x = 1238.67, y = -9907.73 },
            IsQuestCompleted = 38,
            Range = 30,
            Zone = 1436,
            _index = 96,
        },
        {
            Note = { "Kill Harvest Watchers. Loot them for their Flasks of Oil" },
            LootItems = { { itemID = 814, quantity = 5, questID = 103 } },
            Coord = { x = 1238.67, y = -9907.73 },
            IsQuestCompleted = 38,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 97,
        },
        {
            Done = { 9 },
            Coord = { x = 1055.27, y = -10128.7 },
            Zone = 1436,
            _index = 98,
        },
        {
            PickUp = { 92909 },
            AnyOf = { { SkipForLvl = 15, Race = "Human", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } }, { SkipForLvl = 15, Race = "Dwarf", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } }, { SkipForLvl = 15, Race = "Gnome", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } }, { SkipForLvl = 15, Race = "Skyborne", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } } },
            Coord = { x = 1213.4, y = -10153.8 },
            RaidIcon = 253395,
            Zone = 1436,
            _index = 99,
        },
        {
            Done = { 92909 },
            AnyOf = { { SkipForLvl = 15, Race = "Human", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } }, { SkipForLvl = 15, Race = "Dwarf", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } }, { SkipForLvl = 15, Race = "Gnome", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } }, { SkipForLvl = 15, Race = "Skyborne", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } } },
            Coord = { x = 1213.4, y = -10153.8 },
            RaidIcon = 253395,
            Zone = 1436,
            _index = 100,
        },
        {
            Waypoint = 9,
            Note = { "Kill Young Goretusks and Young Fleshrippers. Loot them for their Vulture Meat, Snouts and Livers" },
            Coord = { x = 1179.52, y = -10382.57 },
            NonSkippableWaypoint = true,
            Range = 75.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 101,
        },
        {
            Waypoint = 9,
            Note = { "Kill Young Goretusks and Young Fleshrippers. Loot them for their Vulture Meat, Snouts and Livers" },
            Coord = { x = 1138.22, y = -10474.97 },
            NonSkippableWaypoint = true,
            Range = 75.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 102,
        },
        {
            Waypoint = 9,
            Note = { "Kill Young Goretusks and Young Fleshrippers. Loot them for their Vulture Meat, Snouts and Livers" },
            Coord = { x = 860.67, y = -10462.83 },
            NonSkippableWaypoint = true,
            Range = 75.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 103,
        },
        {
            Waypoint = 9,
            Note = { "Kill Young Goretusks and Young Fleshrippers. Loot them for their Vulture Meat, Snouts and Livers" },
            Coord = { x = 904.07, y = -10038.87 },
            NonSkippableWaypoint = true,
            Range = 75.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 104,
        },
        {
            Waypoint = 9,
            Note = { "Kill Young Goretusks and Young Fleshrippers. Loot them for their Vulture Meat, Snouts and Livers" },
            Coord = { x = 1104.62, y = -9848.0 },
            NonSkippableWaypoint = true,
            Range = 75.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 105,
        },
        {
            Waypoint = 9,
            Note = { "Kill Young Goretusks and Young Fleshrippers. Loot them for their Vulture Meat, Snouts and Livers" },
            Coord = { x = 1298.52, y = -10028.13 },
            NonSkippableWaypoint = true,
            Range = 75.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 106,
        },
        {
            Waypoint = 9,
            Note = { "Kill Young Goretusks and Young Fleshrippers. Loot them for their Vulture Meat, Snouts and Livers" },
            Coord = { x = 1340.52, y = -10401.93 },
            NonSkippableWaypoint = true,
            Range = 75.0,
            SkipForLvl = 15,
            Zone = 1436,
            _index = 107,
        },
        {
            Note = { "Kill Young Goretusks and Young Fleshrippers. Loot them for their Vulture Meat, Snouts and Livers" },
            LootItems = { { itemID = 729, quantity = 3, questID = 38 } },
            Coord = { x = 1111.97, y = -10342.2 },
            SkipForLvl = 15,
            Zone = 1436,
            _index = 108,
        },
        {
            Note = { "Kill Young Goretusks and Young Fleshrippers. Loot them for their Vulture Meat, Snouts and Livers" },
            LootItems = { { itemID = 731, quantity = 3, questID = 38 } },
            Coord = { x = 1111.97, y = -10342.2 },
            SkipForLvl = 15,
            Zone = 1436,
            _index = 109,
        },
        {
            Note = { "Kill Young Goretusks and Young Fleshrippers. Loot them for their Vulture Meat, Snouts and Livers" },
            LootItems = { { itemID = 723, quantity = 8, questID = 22 } },
            Coord = { x = 1111.97, y = -10342.2 },
            SkipForLvl = 15,
            Zone = 1436,
            _index = 110,
        },
        {
            Done = { 9 },
            Coord = { x = 1055.27, y = -10128.7 },
            Zone = 1436,
            _index = 111,
        },
        {
            Done = { 38, 22 },
            Coord = { x = 1042.67, y = -10111.67 },
            Zone = 1436,
            _index = 112,
        },
        {
            PickUp = { 92909 },
            AnyOf = { { SkipForLvl = 15, Race = "Human", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } }, { SkipForLvl = 15, Race = "Dwarf", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } }, { SkipForLvl = 15, Race = "Gnome", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } }, { SkipForLvl = 15, Race = "Skyborne", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } } },
            Coord = { x = 1213.4, y = -10153.8 },
            RaidIcon = 253395,
            Zone = 1436,
            _index = 113,
        },
        {
            Done = { 92909 },
            AnyOf = { { SkipForLvl = 15, Race = "Human", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } }, { SkipForLvl = 15, Race = "Dwarf", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } }, { SkipForLvl = 15, Race = "Gnome", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } }, { SkipForLvl = 15, Race = "Skyborne", AllOf = { { ItemCount = { operator = ">=", count = 5, includeUsableToys = true, itemID = 255010 } }, { ItemCount = { operator = ">=", count = 14, includeUsableToys = true, itemID = 255007 } } } } },
            Coord = { x = 1213.4, y = -10153.8 },
            RaidIcon = 253395,
            Zone = 1436,
            _index = 114,
        },
        {
            Qpart = { [12] = { 1, 2 }, [153] = { 1 } },
            Note = { "It is a dynamic respawn area meaning if you kill enough they will keep respawning" },
            Coord = { x = 1324.2, y = -10490.4 },
            Range = 30,
            Zone = 1436,
            _index = 115,
        },
        {
            Qpart = { [12] = { 1, 2 } },
            Range = 30,
            _index = 116,
        },
        {
            Done = { 12 },
            Coord = { x = 1045.12, y = -10508.8 },
            Zone = 1436,
            _index = 117,
        },
        {
            PickUp = { 65 },
            Coord = { x = 1045.12, y = -10508.8 },
            MinLevel = 14,
            Zone = 1436,
            _index = 118,
        },
        {
            Done = { 102 },
            Coord = { x = 1041.97, y = -10511.13 },
            Zone = 1436,
            _index = 119,
        },
        {
            Qpart = { [153] = { 1 } },
            Range = 30,
            _index = 120,
        },
        {
            Done = { 153 },
            Coord = { x = 1126.67, y = -10636.67 },
            Zone = 1436,
            _index = 121,
        },
        {
            Done = { 92742, 92744 },
            Coord = { x = 1179.8, y = -10635.601 },
            RaidIcon = 253092,
            Zone = 1436,
            _index = 122,
        },
        {
            Note = { "Hearth to Stormwind" },
            UseHS = 399,
            AnyOf = { { SkipInZones = { 1439, 1453 }, SkipForLvl = 15, Race = "Human" }, { SkipInZones = { 1439, 1453 }, SkipForLvl = 15, Race = "Dwarf" }, { SkipInZones = { 1439, 1453 }, SkipForLvl = 15, Race = "Gnome" }, { SkipInZones = { 1439, 1453 }, SkipForLvl = 15, Race = "Skyborne" } },
            ETA = 2.0,
            _index = 123,
        },
        {
            UseFlightPath = 399,
            AnyOf = { { SkipInZones = { 1439, 1453 }, SkipForLvl = 15, Race = "Human" }, { SkipInZones = { 1439, 1453 }, SkipForLvl = 15, Race = "Dwarf" }, { SkipInZones = { 1439, 1453 }, SkipForLvl = 15, Race = "Gnome" }, { SkipInZones = { 1439, 1453 }, SkipForLvl = 15, Race = "Skyborne" } },
            Coord = { x = 1037.42, y = -10628.27 },
            NodeID = 2,
            Zone = 1436,
            _index = 124,
        },
        {
            Waypoint = 399,
            Class = "ROGUE",
            Coord = { x = 609.63, y = -8787.71 },
            EquippedItemStat = { slot = 17, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 8.7, precision = 1, allowMissing = true },
            Money = { operator = ">=", copper = 3815 },
            NonSkippableWaypoint = true,
            Race = "Human",
            RaidIcon = 1287,
            Range = 5,
            Zone = 1453,
            _index = 125,
        },
        {
            BuyMerchant = { { itemID = 2027, quantity = 1 } },
            Class = "ROGUE",
            Coord = { x = 609.63, y = -8787.71 },
            EquippedItemStat = { slot = 17, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 8.7, precision = 1, allowMissing = true },
            ItemCount = { itemID = 2027, count = 1, operator = "<" },
            Money = { operator = ">=", copper = 3815 },
            Race = "Human",
            RaidIcon = 1287,
            Range = 5,
            Zone = 1453,
            _index = 126,
        },
        {
            Note = { "This is used to make `Basic Campfires` on Boats to level your `Cooking` skill without losing time", "You need 50 `Cooking` for a quest in Duskwood later" },
            BuyMerchant = { { itemID = 4470, quantity = 1 } },
            AnyOf = { { Race = "Human", ItemCount = { itemID = 4470, count = 1, operator = "<" }, Skill = { skill = "cooking", rank = 50, operator = "<" } }, { Race = "Dwarf", ItemCount = { itemID = 4470, count = 1, operator = "<" }, Skill = { skill = "cooking", rank = 50, operator = "<" } }, { Race = "Gnome", ItemCount = { itemID = 4470, count = 1, operator = "<" }, Skill = { skill = "cooking", rank = 50, operator = "<" } }, { Race = "Skyborne", ItemCount = { itemID = 4470, count = 1, operator = "<" }, Skill = { skill = "cooking", rank = 50, operator = "<" } } },
            Coord = { x = 596.4, y = -8831.7 },
            Zone = 1453,
            _index = 127,
        },
        {
            Note = { "This is used to make `Basic Campfires` on Boats to level your `Cooking` skill without losing time", "You need 50 `Cooking` for a quest in Duskwood later" },
            BuyMerchant = { { itemID = 4471, quantity = 1 } },
            AnyOf = { { Race = "Human", ItemCount = { itemID = 4471, count = 1, operator = "<" }, Skill = { skill = "cooking", rank = 50, operator = "<" } }, { Race = "Dwarf", ItemCount = { itemID = 4471, count = 1, operator = "<" }, Skill = { skill = "cooking", rank = 50, operator = "<" } }, { Race = "Gnome", ItemCount = { itemID = 4471, count = 1, operator = "<" }, Skill = { skill = "cooking", rank = 50, operator = "<" } }, { Race = "Skyborne", ItemCount = { itemID = 4471, count = 1, operator = "<" }, Skill = { skill = "cooking", rank = 50, operator = "<" } } },
            Coord = { x = 596.4, y = -8831.7 },
            Zone = 1453,
            _index = 128,
        },
        {
            Waypoint = 399,
            Note = { "You need 50 `Cooking` for a quest in Darkshire later", "If you don't want to or can't do this, skip this step", "`Strider Meat`", "`Darkshore Grouper`", "`Chunks of Boar Meat`", "`Stringy Wolf Meat`" },
            Coord = { x = 660.28, y = -8814.55 },
            NonSkippableWaypoint = true,
            Range = 5,
            Skill = { skill = "cooking", rank = 50, operator = "<" },
            Zone = 1453,
            _index = 129,
        },
        {
            BuyMerchant = { { itemID = 769, quantity = 50 }, { itemID = 2672, quantity = 50 }, { itemID = 5469, quantity = 5 }, { itemID = 12238, quantity = 6 } },
            AnyOf = { { Race = "Human", AllOf = { { Skill = { skill = "cooking", rank = 50, operator = "<" } }, { AnyOf = { { ItemCount = { itemID = 769, count = 50, operator = "<" } }, { ItemCount = { itemID = 2672, count = 50, operator = "<" } }, { ItemCount = { itemID = 5469, count = 5, operator = "<" } }, { ItemCount = { itemID = 12238, count = 6, operator = "<" } } } } } }, { Race = "Dwarf", AllOf = { { Skill = { skill = "cooking", rank = 50, operator = "<" } }, { AnyOf = { { ItemCount = { itemID = 769, count = 50, operator = "<" } }, { ItemCount = { itemID = 2672, count = 50, operator = "<" } }, { ItemCount = { itemID = 5469, count = 5, operator = "<" } }, { ItemCount = { itemID = 12238, count = 6, operator = "<" } } } } } }, { Race = "Gnome", AllOf = { { Skill = { skill = "cooking", rank = 50, operator = "<" } }, { AnyOf = { { ItemCount = { itemID = 769, count = 50, operator = "<" } }, { ItemCount = { itemID = 2672, count = 50, operator = "<" } }, { ItemCount = { itemID = 5469, count = 5, operator = "<" } }, { ItemCount = { itemID = 12238, count = 6, operator = "<" } } } } } }, { Race = "Skyborne", AllOf = { { Skill = { skill = "cooking", rank = 50, operator = "<" } }, { AnyOf = { { ItemCount = { itemID = 769, count = 50, operator = "<" } }, { ItemCount = { itemID = 2672, count = 50, operator = "<" } }, { ItemCount = { itemID = 5469, count = 5, operator = "<" } }, { ItemCount = { itemID = 12238, count = 6, operator = "<" } } } } } } },
            Coord = { x = 660.28, y = -8814.55 },
            Range = 5,
            Zone = 1453,
            _index = 130,
        },
        {
            Note = { "If you don't want to or can't do this, skip this step", "`Strider Meat`", "`Darkshore Grouper`" },
            BuyMerchant = { { itemID = 5469, quantity = 5, questID = 2178 } },
            AnyOf = { { Race = "Human", ItemCount = { itemID = 5469, count = 5, operator = "<" }, Skill = { skill = "cooking", rank = 50, operator = ">=" } }, { Race = "Dwarf", ItemCount = { itemID = 5469, count = 5, operator = "<" }, Skill = { skill = "cooking", rank = 50, operator = ">=" } }, { Race = "Gnome", ItemCount = { itemID = 5469, count = 5, operator = "<" }, Skill = { skill = "cooking", rank = 50, operator = ">=" } }, { Race = "Skyborne", ItemCount = { itemID = 5469, count = 5, operator = "<" }, Skill = { skill = "cooking", rank = 50, operator = ">=" } } },
            Coord = { x = 660.28, y = -8814.55 },
            Zone = 1453,
            _index = 131,
        },
        {
            Note = { "If you don't want to or can't do this, skip this step", "`Strider Meat`", "`Darkshore Grouper`" },
            BuyMerchant = { { itemID = 12238, quantity = 6, questID = 1141 } },
            AnyOf = { { Race = "Human", ItemCount = { itemID = 12238, count = 6, operator = "<" }, Skill = { skill = "cooking", rank = 50, operator = ">=" } }, { Race = "Dwarf", ItemCount = { itemID = 12238, count = 6, operator = "<" }, Skill = { skill = "cooking", rank = 50, operator = ">=" } }, { Race = "Gnome", ItemCount = { itemID = 12238, count = 6, operator = "<" }, Skill = { skill = "cooking", rank = 50, operator = ">=" } }, { Race = "Skyborne", ItemCount = { itemID = 12238, count = 6, operator = "<" }, Skill = { skill = "cooking", rank = 50, operator = ">=" } } },
            Coord = { x = 660.28, y = -8814.55 },
            Zone = 1453,
            _index = 132,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "ROGUE",
            Coord = { x = 377.47, y = -8752.39 },
            DontHaveSpell = 1758,
            MinLevel = 1,
            Zone = 1453,
            _index = 133,
        },
        {
            Waypoint = 399,
            Class = "WARRIOR",
            Coord = { x = 358.25, y = -8728.28 },
            DontHaveSpell = 1160,
            NonSkippableWaypoint = true,
            Range = 15.0,
            Zone = 1453,
            _index = 134,
        },
        {
            Waypoint = 399,
            Class = "WARRIOR",
            Coord = { x = 302.6, y = -8685.53 },
            DontHaveSpell = 1160,
            NonSkippableWaypoint = true,
            Range = 15.0,
            Zone = 1453,
            _index = 135,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "WARRIOR",
            Coord = { x = 323.3, y = -8689.29 },
            DontHaveSpell = 1160,
            MinLevel = 1,
            Zone = 1453,
            _index = 136,
        },
        {
            Done = { 399 },
            Coord = { x = 719.67, y = -8550.3 },
            Zone = 1453,
            _index = 137,
        },
        {
            Waypoint = 95065,
            Note = { "Travel to The Slaughtered Lamb and go downstairs" },
            Class = "WARLOCK",
            Coord = { x = 988.44, y = -8942.15 },
            NonSkippableWaypoint = true,
            Race = { "Gnome", "Human" },
            Range = 20.0,
            Zone = 1453,
            _index = 138,
        },
        {
            Waypoint = 95065,
            Note = { "Travel to The Slaughtered Lamb and go downstairs" },
            Class = "WARLOCK",
            Coord = { x = 1015.33, y = -8978.9 },
            NonSkippableWaypoint = true,
            Race = { "Gnome", "Human" },
            Range = 15.0,
            Zone = 1453,
            _index = 139,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "WARLOCK",
            Coord = { x = 1029.89, y = -8971.06 },
            DontHaveSpell = 6222,
            MinLevel = 1,
            Race = { "Gnome", "Human" },
            Zone = 1453,
            _index = 140,
        },
        {
            Waypoint = 95065,
            Class = "MAGE",
            Coord = { x = 874.32, y = -9014.67 },
            NonSkippableWaypoint = true,
            Race = { "Gnome", "Human", "Skyborne" },
            Range = 10.0,
            Zone = 1453,
            _index = 141,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "MAGE",
            Coord = { x = 885.34, y = -9006.15 },
            DontHaveSpell = 2137,
            MinLevel = 1,
            Race = { "Gnome", "Human", "Skyborne" },
            Zone = 1453,
            _index = 142,
        },
        {
            Waypoint = 95065,
            Class = { "PALADIN", "PRIEST" },
            Coord = { x = 809.52, y = -8579.22 },
            NonSkippableWaypoint = true,
            Range = 20.0,
            Zone = 1453,
            _index = 143,
        },
        {
            Waypoint = 95065,
            Class = "PALADIN",
            Coord = { x = 859.13, y = -8559.14 },
            DontHaveSpell = 19742,
            NonSkippableWaypoint = true,
            Race = { "Dwarf", "Human" },
            Range = 10.0,
            Zone = 1453,
            _index = 144,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "PALADIN",
            Coord = { x = 861.14, y = -8573.03 },
            DontHaveSpell = 19742,
            MinLevel = 1,
            Race = { "Dwarf", "Human" },
            Zone = 1453,
            _index = 145,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "PRIEST",
            Coord = { x = 862.89, y = -8519.61 },
            DontHaveSpell = 8122,
            MinLevel = 1,
            Race = { "Dwarf", "Gnome", "Human" },
            Zone = 1453,
            _index = 146,
        },
        {
            BuyMerchant = { { itemID = 6529, quantity = 1, questID = 95065 } },
            Coord = { x = 765.7, y = -8804.0 },
            ItemCount = { itemID = 6529, count = 1, operator = "<" },
            Zone = 1453,
            _index = 147,
        },
        {
            BuyMerchant = { { itemID = 6530, quantity = 3, questID = 95065 } },
            Coord = { x = 765.7, y = -8804.0 },
            ItemCount = { itemID = 6530, count = 3, operator = "<" },
            Zone = 1453,
            _index = 148,
        },
        {
            PickUp = { 97220 },
            Class = "SHAMAN",
            Coord = { x = 1193.1, y = -8328.9 },
            Race = "Dwarf",
            RaidIcon = 268511,
            Zone = 1453,
            _index = 149,
        },
        {
            PickUp = { 95065 },
            Coord = { x = 1269.1, y = -8540.601 },
            RaidIcon = 267118,
            Zone = 1453,
            _index = 150,
        },
        {
            Done = { 95065 },
            Coord = { x = 1269.1, y = -8540.601 },
            RaidIcon = 267118,
            Zone = 1453,
            _index = 151,
        },
        {
            Note = { "On the Boat if it just arrived or on the dock if the boat just left:", "Create a `Basic Campfire` (in your Profession Book)" },
            UseSpell = { spellID = 818, questID = 1141 },
            AnyOf = { { Race = "Human", Skill = { skill = "cooking", rank = 50, operator = "<" }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4470 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 769 } } }, SkipInZones = { 1439 } }, { Race = "Dwarf", Skill = { skill = "cooking", rank = 50, operator = "<" }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4470 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 769 } } }, SkipInZones = { 1439 } }, { Race = "Gnome", Skill = { skill = "cooking", rank = 50, operator = "<" }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4470 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 769 } } }, SkipInZones = { 1439 } }, { Race = "Skyborne", Skill = { skill = "cooking", rank = 50, operator = "<" }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4470 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 769 } } }, SkipInZones = { 1439 } } },
            _index = 152,
        },
        {
            Note = { "On the Boat if it just arrived or on the dock if the boat just left:", "Create a `Basic Campfire` (in your Profession Book)" },
            UseSpell = { spellID = 818, questID = 1141 },
            AnyOf = { { Race = "Human", Skill = { skill = "cooking", rank = 50, operator = "<" }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4470 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = "<", count = 1, includeUsableToys = true, itemID = 769 } } }, SkipInZones = { 1439 } }, { Race = "Dwarf", Skill = { skill = "cooking", rank = 50, operator = "<" }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4470 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = "<", count = 1, includeUsableToys = true, itemID = 769 } } }, SkipInZones = { 1439 } }, { Race = "Gnome", Skill = { skill = "cooking", rank = 50, operator = "<" }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4470 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = "<", count = 1, includeUsableToys = true, itemID = 769 } } }, SkipInZones = { 1439 } }, { Race = "Skyborne", Skill = { skill = "cooking", rank = 50, operator = "<" }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4470 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = "<", count = 1, includeUsableToys = true, itemID = 769 } } }, SkipInZones = { 1439 } } },
            _index = 153,
        },
        {
            Note = { "On the Boat if it just arrived or on the dock if the boat just left:", "Create a `Basic Campfire` (in your Profession Book)" },
            UseSpell = { spellID = 818, questID = 1141 },
            AnyOf = { { Race = "Human", Skill = { skill = "cooking", rank = 50, operator = "<" }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4470 } }, { ItemCount = { operator = "<", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 769 } } }, SkipInZones = { 1439 } }, { Race = "Dwarf", Skill = { skill = "cooking", rank = 50, operator = "<" }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4470 } }, { ItemCount = { operator = "<", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 769 } } }, SkipInZones = { 1439 } }, { Race = "Gnome", Skill = { skill = "cooking", rank = 50, operator = "<" }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4470 } }, { ItemCount = { operator = "<", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 769 } } }, SkipInZones = { 1439 } }, { Race = "Skyborne", Skill = { skill = "cooking", rank = 50, operator = "<" }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4470 } }, { ItemCount = { operator = "<", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 769 } } }, SkipInZones = { 1439 } } },
            _index = 154,
        },
        {
            Note = { "You need 50 `Cooking` for a quest in Duskwood later", "`Cook` the following items:", "`Cook` the `Chunks of Boar Meat` into `Roasted Boar Meat`", "`Cook` the `Stringy Wolf Meat` into `Charred Wolf Meat`" },
            UseSpell = { spellID = 2550, questID = 1141 },
            AnyOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 }, Race = "Human", Skill = { skill = "cooking", rank = 50, operator = "<" }, SkipInZones = { 1439 }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 769 } } } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 }, Race = "Dwarf", Skill = { skill = "cooking", rank = 50, operator = "<" }, SkipInZones = { 1439 }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 769 } } } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 }, Race = "Gnome", Skill = { skill = "cooking", rank = 50, operator = "<" }, SkipInZones = { 1439 }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 769 } } } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 }, Race = "Skyborne", Skill = { skill = "cooking", rank = 50, operator = "<" }, SkipInZones = { 1439 }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 769 } } } } },
            _index = 155,
        },
        {
            Note = { "You need 50 `Cooking` for a quest in Duskwood later", "`Cook` the `Stringy Wolf Meat` into `Charred Wolf Meat`" },
            UseSpell = { spellID = 2550, questID = 1141 },
            AnyOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 }, Race = "Human", Skill = { skill = "cooking", rank = 50, operator = "<" }, SkipInZones = { 1439 }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = "<", count = 1, includeUsableToys = true, itemID = 769 } } } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 }, Race = "Dwarf", Skill = { skill = "cooking", rank = 50, operator = "<" }, SkipInZones = { 1439 }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = "<", count = 1, includeUsableToys = true, itemID = 769 } } } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 }, Race = "Gnome", Skill = { skill = "cooking", rank = 50, operator = "<" }, SkipInZones = { 1439 }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = "<", count = 1, includeUsableToys = true, itemID = 769 } } } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 }, Race = "Skyborne", Skill = { skill = "cooking", rank = 50, operator = "<" }, SkipInZones = { 1439 }, AllOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = "<", count = 1, includeUsableToys = true, itemID = 769 } } } } },
            _index = 156,
        },
        {
            Note = { "You need 50 `Cooking` for a quest in Duskwood later", "`Cook` the `Chunks of Boar Meat` into `Roasted Boar Meat`" },
            UseSpell = { spellID = 2550, questID = 1141 },
            AnyOf = { { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 }, Race = "Human", Skill = { skill = "cooking", rank = 50, operator = "<" }, SkipInZones = { 1439 }, AllOf = { { ItemCount = { operator = "<", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 769 } } } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 }, Race = "Dwarf", Skill = { skill = "cooking", rank = 50, operator = "<" }, SkipInZones = { 1439 }, AllOf = { { ItemCount = { operator = "<", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 769 } } } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 }, Race = "Gnome", Skill = { skill = "cooking", rank = 50, operator = "<" }, SkipInZones = { 1439 }, AllOf = { { ItemCount = { operator = "<", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 769 } } } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 4471 }, Race = "Skyborne", Skill = { skill = "cooking", rank = 50, operator = "<" }, SkipInZones = { 1439 }, AllOf = { { ItemCount = { operator = "<", count = 1, includeUsableToys = true, itemID = 2672 } }, { ItemCount = { operator = ">=", count = 1, includeUsableToys = true, itemID = 769 } } } } },
            _index = 157,
        },
        {
            Waypoint = 1141,
            Note = { "Level your `First Aid` while waiting for the boat to Darkshore if needed", "Take the boat to Darkshore" },
            Coord = { x = 1330.1, y = -8645.4 },
            HasSpell = 3273,
            NonSkippableWaypoint = true,
            Range = 5,
            Zone = 1453,
            _index = 158,
        },
        {
            Waypoint = 1141,
            Note = { "Take the boat to Darkshore" },
            Coord = { x = 1330.1, y = -8645.4 },
            NonSkippableWaypoint = true,
            Range = 5,
            Zone = 1453,
            _index = 159,
        },
        {
            RouteCompleted = true,
            _index = 160,
        },
    },
    parallelSteps = {
        {
            conditions = { EquippedItemStat = { slot = 17, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 8.7, precision = 1, allowMissing = true }, ItemCount = { itemID = 2027, count = 1 }, EquippedItem = { slot = 17, itemID = 2027, invert = true }, Race = "Human", Class = "ROGUE", MinLevel = 14 },
            steps = {
                {
                    EquipItem = { itemID = 2027, slot = 17 },
                    EquippedItemStat = { slot = 17, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 8.7, precision = 1, allowMissing = true },
                    ItemCount = { itemID = 2027, count = 1 },
                    MinLevel = 14,
                    _index = 161,
                },
            },
        },
    },
}
