-- Generated locally by the APR route converter.
APR.RouteQuestStepList["Forever-Generated-Horde-Tirisfal-Glades"] = {
    label = "Horde - Tirisfal Glades - generated",
    expansion = APR.EXPANSIONS.Forever,
    gameVersion = APR.GAME_VERSIONS.Forever,
    category = APR.CATEGORIES.Leveling,
    mapID = 1420,
    conditions = { Race = { APR.RACES.Orc, APR.RACES.Troll }, Class = { APR.Classes.Mage, APR.Classes.Priest, APR.Classes.Rogue, APR.Classes.Warlock, APR.Classes.Warrior } },
    nextRoute = { { route = "Forever-Generated-Horde-Silverpine-Forest" } },
    prefab = { [APR.PREFAB_TYPES.Leveling] = { index = 8 }, [APR.PREFAB_TYPES.Speedrun] = { index = 8 } },
    steps = {
        {
            Waypoint = 1818,
            Class = "WARRIOR",
            Coord = { x = 253.4, y = 2234.85 },
            NonSkippableWaypoint = true,
            Range = 80.0,
            Zone = 1420,
            _index = 1,
        },
        {
            Waypoint = 96895,
            Class = { "MAGE", "PRIEST", "ROGUE", "WARLOCK" },
            Coord = { x = 253.4, y = 2234.85 },
            NonSkippableWaypoint = true,
            Range = 80.0,
            Zone = 1420,
            _index = 2,
        },
        {
            PickUp = { 96895 },
            Coord = { x = 254.6, y = 2225.8 },
            Zone = 1420,
            _index = 3,
        },
        {
            Note = { "Abandon Veteran Uzzek" },
            LeaveQuests = { 1505 },
            Class = "WARRIOR",
            IsQuestOnQuest = 1505,
            _index = 4,
        },
        {
            Note = { "Abandon Path of Defense" },
            LeaveQuests = { 1498 },
            Class = "WARRIOR",
            IsQuestOnQuest = 1498,
            _index = 5,
        },
        {
            PickUp = { 1818 },
            Class = "WARRIOR",
            Coord = { x = 238.49, y = 2254.43 },
            IsQuestUncompleted = 1498,
            Zone = 1420,
            _index = 6,
        },
        {
            PickUp = { 1478 },
            Class = "WARLOCK",
            Coord = { x = 248.88, y = 2251.12 },
            DontHaveSpell = 697,
            IsQuestUncompleted = 1504,
            Zone = 1420,
            _index = 7,
        },
        {
            Done = { 1818 },
            Class = "WARRIOR",
            Coord = { x = 403.87, y = 2287.87 },
            IsQuestUncompleted = 1498,
            Zone = 1420,
            _index = 8,
        },
        {
            PickUp = { 1819 },
            Class = "WARRIOR",
            Coord = { x = 403.87, y = 2287.87 },
            IsQuestUncompleted = 1498,
            Zone = 1420,
            _index = 9,
        },
        {
            Qpart = { [1819] = { 1 } },
            Note = { "Click the Mausoleum Trigger on the ground. This will summon Ulag. Kill him" },
            Class = "WARRIOR",
            Coord = { x = 360.04, y = 2376.14 },
            IsQuestUncompleted = 1498,
            Range = 10,
            Zone = 1420,
            _index = 10,
        },
        {
            Done = { 1819 },
            Class = "WARRIOR",
            Coord = { x = 403.87, y = 2287.87 },
            IsQuestUncompleted = 1498,
            Zone = 1420,
            _index = 11,
        },
        {
            PickUp = { 1820 },
            Class = "WARRIOR",
            Coord = { x = 403.87, y = 2287.87 },
            IsQuestUncompleted = 1498,
            Zone = 1420,
            _index = 12,
        },
        {
            PickUp = { 445 },
            Coord = { x = 346.94, y = 2258.95 },
            Zone = 1420,
            _index = 13,
        },
        {
            Done = { 1820 },
            Class = "WARRIOR",
            Coord = { x = 244.36, y = 2262.26 },
            Zone = 1420,
            _index = 14,
        },
        {
            LearnSkill = { spellID = 588 },
            Class = "PRIEST",
            Coord = { x = 251.14, y = 2265.28 },
            MinLevel = 12,
            Race = "Troll",
            Zone = 1420,
            _index = 15,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "PRIEST",
            Coord = { x = 251.14, y = 2265.28 },
            Race = "Troll",
            Zone = 1420,
            _index = 16,
        },
        {
            LearnSkill = { spellID = 145 },
            Class = "MAGE",
            Coord = { x = 233.06, y = 2256.84 },
            MinLevel = 12,
            Zone = 1420,
            _index = 17,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "MAGE",
            Coord = { x = 233.06, y = 2256.84 },
            Zone = 1420,
            _index = 18,
        },
        {
            LearnSkill = { spellID = 7384 },
            Class = "WARRIOR",
            Coord = { x = 238.49, y = 2255.03 },
            MinLevel = 12,
            Zone = 1420,
            _index = 19,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "WARRIOR",
            Coord = { x = 238.49, y = 2255.03 },
            Zone = 1420,
            _index = 20,
        },
        {
            LearnSkill = { spellID = 1766 },
            Class = "ROGUE",
            Coord = { x = 243.01, y = 2271.0 },
            MinLevel = 12,
            Zone = 1420,
            _index = 21,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "ROGUE",
            Coord = { x = 243.01, y = 2271.0 },
            Zone = 1420,
            _index = 22,
        },
        {
            LearnSkill = { spellID = 755 },
            Class = "WARLOCK",
            Coord = { x = 250.24, y = 2259.25 },
            MinLevel = 12,
            Zone = 1420,
            _index = 23,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "WARLOCK",
            Coord = { x = 250.24, y = 2259.25 },
            Zone = 1420,
            _index = 24,
        },
        {
            SellItems = { junk = true, questID = 96895 },
            Class = { "ROGUE", "WARRIOR" },
            Coord = { x = 244.81, y = 2269.19 },
            Money = { operator = ">=", copper = 500 },
            Zone = 1420,
            _index = 25,
        },
        {
            BuyMerchant = { { itemID = 4605, quantity = 20, questID = 96897 } },
            Class = { "ROGUE", "WARRIOR" },
            Coord = { x = 244.81, y = 2269.19 },
            ItemCount = { itemID = 4605, count = 20, operator = "<" },
            Money = { operator = ">=", copper = 500 },
            Zone = 1420,
            _index = 26,
        },
        {
            SellItems = { junk = true, questID = 96895 },
            Class = "WARLOCK",
            Coord = { x = 244.81, y = 2269.19 },
            Money = { operator = ">=", copper = 375 },
            Zone = 1420,
            _index = 27,
        },
        {
            BuyMerchant = { { itemID = 1179, quantity = 15, questID = 96897 } },
            Class = "WARLOCK",
            Coord = { x = 244.81, y = 2269.19 },
            ItemCount = { itemID = 1179, count = 15, operator = "<" },
            Money = { operator = ">=", copper = 375 },
            Zone = 1420,
            _index = 28,
        },
        {
            BuyMerchant = { { itemID = 4605, quantity = 15, questID = 96897 } },
            Class = "WARLOCK",
            Coord = { x = 244.81, y = 2269.19 },
            ItemCount = { itemID = 4605, count = 15, operator = "<" },
            Money = { operator = ">=", copper = 375 },
            Zone = 1420,
            _index = 29,
        },
        {
            SellItems = { junk = true, questID = 96895 },
            Class = "PRIEST",
            Coord = { x = 244.81, y = 2269.19 },
            Money = { operator = ">=", copper = 500 },
            Race = "Troll",
            Zone = 1420,
            _index = 30,
        },
        {
            BuyMerchant = { { itemID = 1179, quantity = 20, questID = 96897 } },
            Class = "PRIEST",
            Coord = { x = 244.81, y = 2269.19 },
            ItemCount = { itemID = 1179, count = 20, operator = "<" },
            Money = { operator = ">=", copper = 500 },
            Race = "Troll",
            Zone = 1420,
            _index = 31,
        },
        {
            Waypoint = 1478,
            Note = { "Enter Undercity" },
            Class = "WARLOCK",
            Coord = { x = 240.75, y = 1877.57 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 20.0,
            SkipInZones = { 1458 },
            Zone = 1420,
            _index = 32,
        },
        {
            Waypoint = 1478,
            Note = { "Take the lift down to the Undercity" },
            Class = "WARLOCK",
            Coord = { x = 239.14, y = 1749.54 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 35.0,
            Zone = 1458,
            _index = 33,
        },
        {
            Waypoint = 1478,
            Note = { "Take the lift down to the Undercity" },
            Class = "WARLOCK",
            Coord = { x = 255.64, y = 1724.7 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 35.0,
            Zone = 1458,
            _index = 34,
        },
        {
            Waypoint = 1478,
            Note = { "Take the lift down to the Undercity" },
            Class = "WARLOCK",
            Coord = { x = 240.68, y = 1706.97 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 10.0,
            Zone = 1458,
            _index = 35,
        },
        {
            Waypoint = 1478,
            Note = { "Take the lift down to the Undercity" },
            Class = "WARLOCK",
            Coord = { x = 241.06, y = 1660.12 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 10.0,
            Zone = 1458,
            _index = 36,
        },
        {
            Waypoint = 1478,
            Note = { "Take the lift down to the Undercity" },
            Class = "WARLOCK",
            Coord = { x = 257.08, y = 1623.38 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 10.0,
            Zone = 1458,
            _index = 37,
        },
        {
            Waypoint = 1478,
            Note = { "Take the lift down to the Undercity" },
            Class = "WARLOCK",
            Coord = { x = 244.51, y = 1598.73 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 15.0,
            Zone = 1458,
            _index = 38,
        },
        {
            GetFP = 11,
            Class = "WARLOCK",
            Coord = { x = 266.39, y = 1567.11 },
            DontHaveSpell = 697,
            Zone = 1458,
            _index = 39,
        },
        {
            Done = { 1478 },
            Class = "WARLOCK",
            Coord = { x = 57.05, y = 1711.77 },
            DontHaveSpell = 697,
            IsQuestUncompleted = 1504,
            Zone = 1458,
            _index = 40,
        },
        {
            PickUp = { 1473 },
            Class = "WARLOCK",
            Coord = { x = 57.05, y = 1711.77 },
            DontHaveSpell = 697,
            IsQuestUncompleted = 1504,
            Zone = 1458,
            _index = 41,
        },
        {
            Waypoint = 1473,
            Note = { "Leave Undercity through the Sewers" },
            Class = "WARLOCK",
            Coord = { x = 419.89, y = 1627.54 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 50.0,
            SkipInZones = { 1420 },
            Zone = 1458,
            _index = 42,
        },
        {
            Waypoint = 1473,
            Note = { "Leave Undercity through the Sewers" },
            Class = "WARLOCK",
            Coord = { x = 428.52, y = 1597.2 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 10.0,
            SkipInZones = { 1420 },
            Zone = 1458,
            _index = 43,
        },
        {
            Waypoint = 1473,
            Note = { "Leave Undercity through the Sewers" },
            Class = "WARLOCK",
            Coord = { x = 439.17, y = 1626.06 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 10.0,
            SkipInZones = { 1420 },
            Zone = 1458,
            _index = 44,
        },
        {
            Waypoint = 1473,
            Note = { "Leave Undercity through the Sewers" },
            Class = "WARLOCK",
            Coord = { x = 476.78, y = 1632.15 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 10.0,
            SkipInZones = { 1420 },
            Zone = 1458,
            _index = 45,
        },
        {
            Waypoint = 1473,
            Note = { "Leave Undercity through the Sewers" },
            Class = "WARLOCK",
            Coord = { x = 482.34, y = 1660.63 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 10.0,
            SkipInZones = { 1420 },
            Zone = 1458,
            _index = 46,
        },
        {
            Waypoint = 1473,
            Note = { "Leave Undercity through the Sewers" },
            Class = "WARLOCK",
            Coord = { x = 539.33, y = 1665.49 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 15.0,
            SkipInZones = { 1420 },
            Zone = 1458,
            _index = 47,
        },
        {
            Waypoint = 1473,
            Note = { "Leave Undercity through the Sewers" },
            Class = "WARLOCK",
            Coord = { x = 610.42, y = 1684.44 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 35.0,
            SkipInZones = { 1420 },
            Zone = 1458,
            _index = 48,
        },
        {
            Waypoint = 1473,
            Note = { "Leave Undercity through the Sewers" },
            Class = "WARLOCK",
            Coord = { x = 663.19, y = 1600.46 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 35.0,
            SkipInZones = { 1420 },
            Zone = 1458,
            _index = 49,
        },
        {
            Waypoint = 1473,
            Note = { "Leave Undercity through the Sewers" },
            Class = "WARLOCK",
            Coord = { x = 724.25, y = 1682.66 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 50.0,
            SkipInZones = { 1420 },
            Zone = 1420,
            _index = 50,
        },
        {
            Qpart = { [1473] = { 1 } },
            Note = { "Loot Perrine's Chest on the ground for `Egalin's Grimoire`" },
            Class = "WARLOCK",
            Coord = { x = 726.06, y = 1801.95 },
            DontHaveSpell = 697,
            IsQuestUncompleted = 1504,
            Zone = 1420,
            _index = 51,
        },
        {
            Waypoint = 1473,
            Note = { "Travel back into the Undercity through the sewers" },
            Class = "WARLOCK",
            Coord = { x = 714.8, y = 1604.24 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 35.0,
            Zone = 1458,
            _index = 52,
        },
        {
            Waypoint = 1473,
            Note = { "Travel back into the Undercity through the sewers" },
            Class = "WARLOCK",
            Coord = { x = 652.73, y = 1623.44 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 35.0,
            Zone = 1458,
            _index = 53,
        },
        {
            Waypoint = 1473,
            Note = { "Travel back into the Undercity through the sewers" },
            Class = "WARLOCK",
            Coord = { x = 634.02, y = 1669.66 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 35.0,
            Zone = 1458,
            _index = 54,
        },
        {
            Waypoint = 1473,
            Note = { "Travel back into the Undercity through the sewers" },
            Class = "WARLOCK",
            Coord = { x = 539.52, y = 1665.17 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 10.0,
            Zone = 1458,
            _index = 55,
        },
        {
            Waypoint = 1473,
            Note = { "Travel back into the Undercity through the sewers" },
            Class = "WARLOCK",
            Coord = { x = 481.48, y = 1659.8 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 10.0,
            Zone = 1458,
            _index = 56,
        },
        {
            Waypoint = 1473,
            Note = { "Travel back into the Undercity through the sewers" },
            Class = "WARLOCK",
            Coord = { x = 476.49, y = 1632.15 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 10.0,
            Zone = 1458,
            _index = 57,
        },
        {
            Waypoint = 1473,
            Note = { "Travel back into the Undercity through the sewers" },
            Class = "WARLOCK",
            Coord = { x = 439.08, y = 1627.02 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 10.0,
            Zone = 1458,
            _index = 58,
        },
        {
            Waypoint = 1473,
            Note = { "Travel back into the Undercity through the sewers" },
            Class = "WARLOCK",
            Coord = { x = 435.05, y = 1598.86 },
            DontHaveSpell = 697,
            NonSkippableWaypoint = true,
            Range = 10.0,
            Zone = 1458,
            _index = 59,
        },
        {
            Done = { 1473 },
            Class = "WARLOCK",
            Coord = { x = 57.05, y = 1711.77 },
            DontHaveSpell = 697,
            IsQuestUncompleted = 1504,
            Zone = 1458,
            _index = 60,
        },
        {
            PickUp = { 1471 },
            Class = "WARLOCK",
            Coord = { x = 57.05, y = 1711.77 },
            DontHaveSpell = 697,
            IsQuestUncompleted = 1504,
            Zone = 1458,
            _index = 61,
        },
        {
            Note = { "Use the `Runes of Summoning` at the Summoning Circle" },
            Button = { ["1471-1"] = 6284 },
            Class = "WARLOCK",
            Coord = { x = 41.99, y = 1704.48 },
            DontHaveSpell = 697,
            SpellButton = { ["1471-1"] = 9221 },
            Zone = 1458,
            _index = 62,
        },
        {
            Qpart = { [1471] = { 1 } },
            Button = { ["1471-1"] = 6284 },
            Class = "WARLOCK",
            Coord = { x = 41.99, y = 1704.48 },
            DontHaveSpell = 697,
            IsQuestUncompleted = 1504,
            Range = 10,
            Zone = 1458,
            _index = 63,
        },
        {
            Done = { 1471 },
            Class = "WARLOCK",
            Coord = { x = 57.34, y = 1711.71 },
            DontHaveSpell = 697,
            IsQuestUncompleted = 1504,
            Zone = 1458,
            _index = 64,
        },
        {
            Waypoint = 356,
            Class = "WARLOCK",
            Coord = { x = 244.51, y = 1598.73 },
            NonSkippableWaypoint = true,
            OnlyInZones = { 1458 },
            Range = 9,
            Zone = 1458,
            _index = 65,
        },
        {
            Waypoint = 356,
            Class = "WARLOCK",
            Coord = { x = 257.08, y = 1623.38 },
            NonSkippableWaypoint = true,
            OnlyInZones = { 1458 },
            Range = 9,
            Zone = 1458,
            _index = 66,
        },
        {
            Waypoint = 356,
            Class = "WARLOCK",
            Coord = { x = 241.06, y = 1660.12 },
            NonSkippableWaypoint = true,
            OnlyInZones = { 1458 },
            Range = 9,
            Zone = 1458,
            _index = 67,
        },
        {
            Waypoint = 356,
            Class = "WARLOCK",
            Coord = { x = 240.68, y = 1706.97 },
            NonSkippableWaypoint = true,
            OnlyInZones = { 1458 },
            Range = 9,
            Zone = 1458,
            _index = 68,
        },
        {
            Waypoint = 356,
            Class = "WARLOCK",
            Coord = { x = 255.64, y = 1724.7 },
            NonSkippableWaypoint = true,
            OnlyInZones = { 1458 },
            Range = 9,
            Zone = 1458,
            _index = 69,
        },
        {
            Waypoint = 356,
            Class = "WARLOCK",
            Coord = { x = 239.14, y = 1749.54 },
            NonSkippableWaypoint = true,
            OnlyInZones = { 1458 },
            Range = 9,
            Zone = 1458,
            _index = 70,
        },
        {
            Waypoint = 356,
            Class = "WARLOCK",
            Coord = { x = 240.75, y = 1877.57 },
            NonSkippableWaypoint = true,
            OnlyInZones = { 1458 },
            Range = 9,
            Zone = 1420,
            _index = 71,
        },
        {
            PickUp = { 356 },
            Coord = { x = 74.0, y = 2022.47 },
            Zone = 1420,
            _index = 72,
        },
        {
            Done = { 96895 },
            Coord = { x = 54.6, y = 1996.6 },
            Zone = 1420,
            _index = 73,
        },
        {
            PickUp = { 96897, 96898 },
            Coord = { x = 54.6, y = 1996.6 },
            Zone = 1420,
            _index = 74,
        },
        {
            Qpart = { [356] = { 1, 2 } },
            Coord = { x = -420.345, y = 2012.525 },
            Range = 147,
            Zone = 1420,
            _index = 75,
        },
        {
            Qpart = { [96897] = { 2, 1 }, [96898] = { 1 } },
            Note = { "Necrotic Crystal Fragments can also be looted on the ground", "Be careful! These mobs hit hard. Dark Enforcers also have an instant cast 50-70 damage ability" },
            Coord = { x = -130.5, y = 1907.8 },
            Range = 30,
            Zone = 1420,
            _index = 76,
        },
        {
            Done = { 96897, 96898 },
            Coord = { x = 54.5, y = 1996.4 },
            Zone = 1420,
            _index = 77,
        },
        {
            Done = { 356 },
            Coord = { x = 74.0, y = 2022.47 },
            Zone = 1420,
            _index = 78,
        },
        {
            Waypoint = 435,
            Note = { "Enter Undercity" },
            AnyOf = { { SkipInZones = { 1458 }, Race = "Orc" }, { SkipInZones = { 1458 }, Race = "Troll" } },
            Coord = { x = 240.75, y = 1877.57 },
            NonSkippableWaypoint = true,
            Range = 20.0,
            Zone = 1420,
            _index = 79,
        },
        {
            Waypoint = 435,
            Note = { "Take the lift down to the Undercity" },
            Coord = { x = 239.14, y = 1749.54 },
            NonSkippableWaypoint = true,
            Range = 35.0,
            Zone = 1458,
            _index = 80,
        },
        {
            Waypoint = 435,
            Note = { "Take the lift down to the Undercity" },
            Coord = { x = 255.64, y = 1724.7 },
            NonSkippableWaypoint = true,
            Range = 35.0,
            Zone = 1458,
            _index = 81,
        },
        {
            Waypoint = 435,
            Note = { "Take the lift down to the Undercity" },
            Coord = { x = 240.68, y = 1706.97 },
            NonSkippableWaypoint = true,
            Range = 10.0,
            Zone = 1458,
            _index = 82,
        },
        {
            Waypoint = 435,
            Note = { "Take the lift down to the Undercity" },
            Coord = { x = 241.06, y = 1660.12 },
            NonSkippableWaypoint = true,
            Range = 10.0,
            Zone = 1458,
            _index = 83,
        },
        {
            Waypoint = 435,
            Note = { "Take the lift down to the Undercity" },
            Coord = { x = 257.08, y = 1623.38 },
            NonSkippableWaypoint = true,
            Range = 10.0,
            Zone = 1458,
            _index = 84,
        },
        {
            Waypoint = 435,
            Note = { "Take the lift down to the Undercity" },
            Coord = { x = 244.51, y = 1598.73 },
            NonSkippableWaypoint = true,
            Range = 15.0,
            Zone = 1458,
            _index = 85,
        },
        {
            GetFP = 11,
            Coord = { x = 266.39, y = 1567.11 },
            Zone = 1458,
            _index = 86,
        },
        {
            Note = { "Alternatively, check the Auction House for something better or cheaper" },
            BuyMerchant = { { itemID = 851, quantity = 1 } },
            Class = "ROGUE",
            Coord = { x = 286.53, y = 1616.21 },
            EquippedItemStat = { { slot = 16, stat = "QUALITY", operator = "<", value = 7.0, precision = 1, allowMissing = true }, { slot = 16, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 6.8, precision = 1, allowMissing = true } },
            ItemCount = { itemID = 851, count = 1, operator = "<" },
            Money = { operator = ">=", copper = 2023 },
            OnlyInZones = { 1458 },
            Zone = 1458,
            _index = 87,
        },
        {
            LearnSkill = { spellID = 201 },
            Class = "ROGUE",
            Coord = { x = 323.57, y = 1668.5 },
            MinLevel = 1,
            Money = { operator = ">=", copper = 1000 },
            Zone = 1458,
            _index = 88,
        },
        {
            BuyMerchant = { { itemID = 854, quantity = 1, questID = 435 } },
            Class = "WARRIOR",
            Coord = { x = 308.89, y = 1667.8 },
            EquippedItemStat = { { slot = 16, stat = "QUALITY", operator = "<", value = 7.0, precision = 1, allowMissing = true }, { slot = 16, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 9.0, precision = 1, allowMissing = true } },
            ItemCount = { itemID = 854, count = 1, operator = "<" },
            Money = { operator = ">=", copper = 3022 },
            Race = "Troll",
            Zone = 1458,
            _index = 89,
        },
        {
            Note = { "Skip this if you want, it's only a small time saver" },
            BuyMerchant = { { itemID = 730, quantity = 3, questID = 91920 } },
            Coord = { x = 224.3, y = 1648.2 },
            ItemCount = { itemID = 730, count = 3, operator = "<" },
            OnlyInZones = { 1458 },
            Zone = 1458,
            _index = 90,
        },
        {
            LearnProfession = 7411,
            Class = "PRIEST",
            Coord = { x = 273.87, y = 1482.36 },
            EquippedItemStat = { { slot = 18, stat = "QUALITY", operator = "<", value = 7.0, precision = 1, allowMissing = true }, { slot = 18, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 11.3, precision = 1, allowMissing = true } },
            MinLevel = 5,
            Race = "Troll",
            SkipForPrimaryProfessions = 2,
            Zone = 1458,
            _index = 91,
        },
        {
            LearnProfession = 3908,
            Class = "PRIEST",
            Coord = { x = 194.24, y = 1681.5 },
            EquippedItemStat = { { slot = 18, stat = "QUALITY", operator = "<", value = 7.0, precision = 1, allowMissing = true }, { slot = 18, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 11.3, precision = 1, allowMissing = true } },
            MinLevel = 5,
            Race = "Troll",
            SkipForPrimaryProfessions = 2,
            Zone = 1458,
            _index = 92,
        },
        {
            Note = { "Turn all your `Linen Cloth` into `Bolt of linen Linen Cloth`" },
            LootItems = { { itemID = 2996, quantity = 30, questID = 435 } },
            Class = "PRIEST",
            Coord = { x = 194.34, y = 1681.63 },
            EquippedItemStat = { { slot = 18, stat = "QUALITY", operator = "<", value = 7.0, precision = 1, allowMissing = true }, { slot = 18, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 11.3, precision = 1, allowMissing = true } },
            HasSpell = 3908,
            Race = "Troll",
            Zone = 1458,
            _index = 93,
        },
        {
            LearnProfession = 7623,
            Class = "PRIEST",
            Coord = { x = 194.34, y = 1681.63 },
            EquippedItemStat = { { slot = 18, stat = "QUALITY", operator = "<", value = 7.0, precision = 1, allowMissing = true }, { slot = 18, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 11.3, precision = 1, allowMissing = true } },
            HasSpell = 3908,
            MinLevel = 5,
            Race = "Troll",
            Zone = 1458,
            _index = 94,
        },
        {
            BuyMerchant = { { itemID = 2320, quantity = 30, questID = 435 } },
            Class = "PRIEST",
            Coord = { x = 196.16, y = 1684.83 },
            EquippedItemStat = { { slot = 18, stat = "QUALITY", operator = "<", value = 7.0, precision = 1, allowMissing = true }, { slot = 18, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 11.3, precision = 1, allowMissing = true } },
            HasSpell = 3908,
            ItemCount = { itemID = 2320, count = 30, operator = "<" },
            Race = "Troll",
            Zone = 1458,
            _index = 95,
        },
        {
            Note = { "Create as many `Brown Linen Robes` as you can" },
            LootItems = { { itemID = 6238, quantity = 9, questID = 398 } },
            Class = "PRIEST",
            EquippedItemStat = { { slot = 18, stat = "QUALITY", operator = "<", value = 7.0, precision = 1, allowMissing = true }, { slot = 18, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 11.3, precision = 1, allowMissing = true } },
            HasSpell = 3908,
            Race = "Troll",
            _index = 96,
        },
        {
            Note = { "Disenchant all the `Brown Linen Robes` that you made and create a `Runed Copper Rod`", "If you did not get a `Lesser Magic Essence` then buy one from Thaddeus if there is one available. Otherwise finish this step later" },
            BuyMerchant = { { itemID = 6218, quantity = 1, questID = 435 } },
            Class = "PRIEST",
            Coord = { x = 275.02, y = 1487.55 },
            EquippedItemStat = { { slot = 18, stat = "QUALITY", operator = "<", value = 7.0, precision = 1, allowMissing = true }, { slot = 18, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 11.3, precision = 1, allowMissing = true } },
            HasSpell = 7411,
            ItemCount = { itemID = 6218, count = 1, operator = "<" },
            Race = "Troll",
            Zone = 1458,
            _index = 97,
        },
        {
            Note = { "Disenchant all the `Brown Linen Robes` that you made and create a `Runed Copper Rod`", "If you did not get a `Lesser Magic Essence` then buy one from Thaddeus if there is one available. Otherwise finish this step later" },
            BuyMerchant = { { itemID = 4470, quantity = 1, questID = 435 } },
            Class = "PRIEST",
            Coord = { x = 275.02, y = 1487.55 },
            EquippedItemStat = { { slot = 18, stat = "QUALITY", operator = "<", value = 7.0, precision = 1, allowMissing = true }, { slot = 18, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 11.3, precision = 1, allowMissing = true } },
            HasSpell = 7411,
            ItemCount = { itemID = 4470, count = 1, operator = "<" },
            Race = "Troll",
            Zone = 1458,
            _index = 98,
        },
        {
            LearnProfession = 14293,
            Class = "PRIEST",
            Coord = { x = 273.2, y = 1491.71 },
            EquippedItemStat = { { slot = 18, stat = "QUALITY", operator = "<", value = 7.0, precision = 1, allowMissing = true }, { slot = 18, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 11.3, precision = 1, allowMissing = true } },
            HasSpell = 7411,
            MinLevel = 5,
            Race = "Troll",
            Zone = 1458,
            _index = 99,
        },
        {
            Note = { "Create a `Lesser Magic Wand`", "If you did not get a `Lesser Magic Essence` then buy one from Thaddeus if there is one available. Otherwise finish this step later" },
            LootItems = { { itemID = 11287, quantity = 1, questID = 435 } },
            Class = "PRIEST",
            EquippedItemStat = { { slot = 18, stat = "QUALITY", operator = "<", value = 7.0, precision = 1, allowMissing = true }, { slot = 18, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 11.3, precision = 1, allowMissing = true } },
            HasSpell = 7411,
            Race = "Troll",
            _index = 100,
        },
        {
            LearnSkill = { spellID = 1766 },
            Class = "ROGUE",
            Coord = { x = 68.66, y = 1416.69 },
            MinLevel = 12,
            Money = { operator = ">=", copper = 800 },
            Zone = 1458,
            _index = 101,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "ROGUE",
            Coord = { x = 68.66, y = 1416.69 },
            Zone = 1458,
            _index = 102,
        },
        {
            LearnSkill = { spellID = 145 },
            Class = "MAGE",
            Coord = { x = 56.38, y = 1813.81 },
            MinLevel = 12,
            Money = { operator = ">=", copper = 800 },
            Zone = 1458,
            _index = 103,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "MAGE",
            Coord = { x = 56.38, y = 1813.81 },
            Zone = 1458,
            _index = 104,
        },
        {
            LearnSkill = { spellID = 755 },
            Class = "WARLOCK",
            Coord = { x = 20.02, y = 1776.42 },
            MinLevel = 12,
            Money = { operator = ">=", copper = 800 },
            Zone = 1458,
            _index = 105,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "WARLOCK",
            Coord = { x = 20.02, y = 1776.42 },
            Zone = 1458,
            _index = 106,
        },
        {
            LearnSkill = { spellID = 588 },
            Class = "PRIEST",
            Coord = { x = 416.91, y = 1757.03 },
            MinLevel = 12,
            Money = { operator = ">=", copper = 800 },
            Race = "Troll",
            Zone = 1458,
            _index = 107,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "PRIEST",
            Coord = { x = 416.91, y = 1757.03 },
            Race = "Troll",
            Zone = 1458,
            _index = 108,
        },
        {
            LearnSkill = { spellID = 7384 },
            Class = "WARRIOR",
            Coord = { x = 418.35, y = 1767.02 },
            MinLevel = 12,
            Money = { operator = ">=", copper = 800 },
            Zone = 1458,
            _index = 109,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "WARRIOR",
            Coord = { x = 418.35, y = 1767.02 },
            Zone = 1458,
            _index = 110,
        },
        {
            Note = { "Abandon Dark Storms" },
            LeaveQuests = { 806 },
            _index = 111,
        },
        {
            Note = { "Abandon The Family Crypt" },
            LeaveQuests = { 408 },
            _index = 112,
        },
        {
            Note = { "Abandon Agamand Heirlooms" },
            LeaveQuests = { 1821 },
            Class = "WARRIOR",
            _index = 113,
        },
        {
            Note = { "Abandon The Chill of Death" },
            LeaveQuests = { 375 },
            _index = 114,
        },
        {
            Waypoint = 435,
            Note = { "Leave Undercity through the Sewers" },
            Coord = { x = 419.89, y = 1627.54 },
            NonSkippableWaypoint = true,
            Range = 50.0,
            SkipInZones = { 1421 },
            Zone = 1458,
            _index = 115,
        },
        {
            Waypoint = 435,
            Note = { "Leave Undercity through the Sewers" },
            Coord = { x = 428.52, y = 1597.2 },
            NonSkippableWaypoint = true,
            Range = 10.0,
            SkipInZones = { 1421 },
            Zone = 1458,
            _index = 116,
        },
        {
            Waypoint = 435,
            Note = { "Leave Undercity through the Sewers" },
            Coord = { x = 439.17, y = 1626.06 },
            NonSkippableWaypoint = true,
            Range = 10.0,
            SkipInZones = { 1421 },
            Zone = 1458,
            _index = 117,
        },
        {
            Waypoint = 435,
            Note = { "Leave Undercity through the Sewers" },
            Coord = { x = 476.78, y = 1632.15 },
            NonSkippableWaypoint = true,
            Range = 10.0,
            SkipInZones = { 1421 },
            Zone = 1458,
            _index = 118,
        },
        {
            Waypoint = 435,
            Note = { "Leave Undercity through the Sewers" },
            Coord = { x = 482.34, y = 1660.63 },
            NonSkippableWaypoint = true,
            Range = 10.0,
            SkipInZones = { 1421 },
            Zone = 1458,
            _index = 119,
        },
        {
            Waypoint = 435,
            Note = { "Leave Undercity through the Sewers" },
            Coord = { x = 539.33, y = 1665.49 },
            NonSkippableWaypoint = true,
            Range = 15.0,
            SkipInZones = { 1421 },
            Zone = 1458,
            _index = 120,
        },
        {
            Waypoint = 435,
            Note = { "Leave Undercity through the Sewers" },
            Coord = { x = 610.42, y = 1684.44 },
            NonSkippableWaypoint = true,
            Range = 35.0,
            SkipInZones = { 1421 },
            Zone = 1458,
            _index = 121,
        },
        {
            Waypoint = 435,
            Note = { "Leave Undercity through the Sewers" },
            Coord = { x = 663.19, y = 1600.46 },
            NonSkippableWaypoint = true,
            Range = 35.0,
            SkipInZones = { 1421 },
            Zone = 1458,
            _index = 122,
        },
        {
            Waypoint = 435,
            Note = { "Leave Undercity through the Sewers" },
            Coord = { x = 724.25, y = 1682.66 },
            NonSkippableWaypoint = true,
            Range = 50.0,
            SkipInZones = { 1421 },
            Zone = 1420,
            _index = 123,
        },
        {
            Waypoint = 435,
            Coord = { x = 629.36, y = 1553.42 },
            NonSkippableWaypoint = true,
            Range = 5,
            SkipInZones = { 1421 },
            Zone = 1420,
            _index = 124,
        },
        {
            RouteCompleted = true,
            _index = 125,
        },
    },
    parallelSteps = {
        {
            conditions = { EquippedItemStat = { { slot = 16, stat = "QUALITY", operator = "<", value = 7.0, precision = 1, allowMissing = true }, { slot = 16, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 6.8, precision = 1, allowMissing = true } }, DontHaveSpell = 201, ItemCount = { itemID = 851, count = 1 }, EquippedItem = { slot = 16, itemID = 851, invert = true }, Class = "ROGUE", MinLevel = 10 },
            steps = {
                {
                    DontHaveSpell = 201,
                    EquipItem = { itemID = 851, slot = 16 },
                    EquippedItemStat = { { slot = 16, stat = "QUALITY", operator = "<", value = 7.0, precision = 1, allowMissing = true }, { slot = 16, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 6.8, precision = 1, allowMissing = true } },
                    ItemCount = { itemID = 851, count = 1 },
                    MinLevel = 10,
                    _index = 126,
                },
            },
        },
        {
            conditions = { EquippedItemStat = { { slot = 16, stat = "QUALITY", operator = "<", value = 7.0, precision = 1, allowMissing = true }, { slot = 16, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 9.0, precision = 1, allowMissing = true } }, ItemCount = { itemID = 854, count = 1 }, EquippedItem = { slot = 16, itemID = 854, invert = true }, Race = "Troll", Class = "WARRIOR", MinLevel = 11 },
            steps = {
                {
                    EquipItem = { itemID = 854, slot = 16 },
                    EquippedItemStat = { { slot = 16, stat = "QUALITY", operator = "<", value = 7.0, precision = 1, allowMissing = true }, { slot = 16, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 9.0, precision = 1, allowMissing = true } },
                    ItemCount = { itemID = 854, count = 1 },
                    MinLevel = 11,
                    _index = 127,
                },
            },
        },
        {
            conditions = { EquippedItemStat = { { slot = 18, stat = "QUALITY", operator = "<", value = 7.0, precision = 1, allowMissing = true }, { slot = 18, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 11.3, precision = 1, allowMissing = true } }, ItemCount = { itemID = 11287, count = 1 }, EquippedItem = { slot = 18, itemID = 11287, invert = true }, Race = "Troll", Class = "PRIEST", MinLevel = 5 },
            steps = {
                {
                    EquipItem = { itemID = 11287, slot = 18 },
                    EquippedItemStat = { { slot = 18, stat = "QUALITY", operator = "<", value = 7.0, precision = 1, allowMissing = true }, { slot = 18, stat = "ITEM_MOD_DAMAGE_PER_SECOND_SHORT", operator = "<", value = 11.3, precision = 1, allowMissing = true } },
                    ItemCount = { itemID = 11287, count = 1 },
                    MinLevel = 5,
                    _index = 128,
                },
            },
        },
    },
}
