-- Generated locally by the APR route converter.
APR.RouteQuestStepList["Forever-Generated-Alliance-Elwynn-Forest"] = {
    label = "Alliance - Elwynn Forest - generated",
    expansion = APR.EXPANSIONS.Forever,
    gameVersion = APR.GAME_VERSIONS.Forever,
    category = APR.CATEGORIES.Leveling,
    mapID = 1429,
    conditions = { Race = { APR.RACES.Dwarf, APR.RACES.Gnome }, Class = { APR.Classes.Mage, APR.Classes.Paladin, APR.Classes.Priest, APR.Classes.Rogue, APR.Classes.Shaman, APR.Classes.Warlock, APR.Classes.Warrior } },
    nextRoute = { "Forever-Generated-Alliance-Loch-Modan-Dwarf-Gnome" },
    prefab = { [APR.PREFAB_TYPES.Leveling] = { index = 9 }, [APR.PREFAB_TYPES.Speedrun] = { index = 9 } },
    steps = {
        {
            Note = { "Cast `Life Tap` repeatedly until you have <10% health while on the way to Dungar Longdrink" },
            Class = "WARLOCK",
            Hardcore = false,
            Race = "Gnome",
            _index = 1,
        },
        {
            GetFP = 2,
            Coord = { x = 490.03, y = -8835.82 },
            Zone = 1453,
            _index = 2,
        },
        {
            Note = { "Cast `Life Tap` repeatedly until you have <10% health then jump down the ledge (NOT into the water) next to the flight master and die intentionally", "Respawn at the Spirit Healer" },
            DeathSkip = true,
            Class = "WARLOCK",
            Hardcore = false,
            Race = "Gnome",
            _index = 3,
        },
        {
            Note = { "Travel to Goldshire" },
            _index = 4,
        },
        {
            Waypoint = 40,
            Note = { "Travel upstairs in the Inn" },
            Class = { "MAGE", "ROGUE" },
            Coord = { x = 12.52, y = -9479.85 },
            NonSkippableWaypoint = true,
            Range = 9.0,
            Zone = 1429,
            _index = 5,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "MAGE",
            Coord = { x = 34.28, y = -9471.61 },
            MinLevel = 1,
            Race = "Gnome",
            Zone = 1429,
            _index = 6,
        },
        {
            Note = { "Prioritize training `Dual Wield`" },
            LearnSkill = { allAvailable = true },
            Class = "ROGUE",
            Coord = { x = 12.69, y = -9465.75 },
            MinLevel = 1,
            Zone = 1429,
            _index = 7,
        },
        {
            PickUp = { 40 },
            Coord = { x = 72.81, y = -9496.23 },
            Zone = 1429,
            _index = 8,
        },
        {
            Done = { 40 },
            Coord = { x = 73.92, y = -9465.54 },
            Zone = 1429,
            _index = 9,
        },
        {
            PickUp = { 35 },
            Coord = { x = 73.92, y = -9465.54 },
            Zone = 1429,
            _index = 10,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "PALADIN",
            Coord = { x = 109.04, y = -9468.16 },
            MinLevel = 1,
            Race = "Dwarf",
            Zone = 1429,
            _index = 11,
        },
        {
            PickUp = { 176 },
            Note = { "Click the Wanted Poster" },
            Class = "WARLOCK",
            Coord = { x = 683.4, y = -9667.93 },
            Race = "Gnome",
            Zone = 1429,
            _index = 12,
        },
        {
            DropQuest = 123,
            DroppableQuest = { MobId = 97, Qid = 123, Text = "Riverpaw Runt" },
            Note = { "The `Gold Pickup Schedule` is a very rare drop. Ignore this step if you don't get it", "Gruff Swiftbite a rare spawn, does have a 100% drop chance" },
            Class = "WARLOCK",
            Race = "Gnome",
            _index = 13,
        },
        {
            Waypoint = 176,
            Note = { "Kill Hogger. Loot him for his Claw", "Hogger can spawn in multiple locations", "Cast `Fear` on Hogger continously and use your regular DoTs to kill him", "This quest is difficult. Find a group for him if needed. Skip this step if you're unable to find a group or solo him" },
            Class = "WARLOCK",
            Coord = { x = 598.29, y = -9946.33 },
            NonSkippableWaypoint = true,
            Race = "Gnome",
            Range = 70.0,
            Zone = 1429,
            _index = 14,
        },
        {
            Waypoint = 176,
            Note = { "Kill Hogger. Loot him for his Claw", "Hogger can spawn in multiple locations", "Cast `Fear` on Hogger continously and use your regular DoTs to kill him", "This quest is difficult. Find a group for him if needed. Skip this step if you're unable to find a group or solo him" },
            Class = "WARLOCK",
            Coord = { x = 629.53, y = -10020.39 },
            NonSkippableWaypoint = true,
            Race = "Gnome",
            Range = 70.0,
            Zone = 1429,
            _index = 15,
        },
        {
            Waypoint = 176,
            Note = { "Kill Hogger. Loot him for his Claw", "Hogger can spawn in multiple locations", "Cast `Fear` on Hogger continously and use your regular DoTs to kill him", "This quest is difficult. Find a group for him if needed. Skip this step if you're unable to find a group or solo him" },
            Class = "WARLOCK",
            Coord = { x = 660.77, y = -10085.2 },
            NonSkippableWaypoint = true,
            Race = "Gnome",
            Range = 70.0,
            Zone = 1429,
            _index = 16,
        },
        {
            Waypoint = 176,
            Note = { "Kill Hogger. Loot him for his Claw", "Hogger can spawn in multiple locations", "Cast `Fear` on Hogger continously and use your regular DoTs to kill him", "This quest is difficult. Find a group for him if needed. Skip this step if you're unable to find a group or solo him" },
            Class = "WARLOCK",
            Coord = { x = 598.29, y = -10112.98 },
            NonSkippableWaypoint = true,
            Race = "Gnome",
            Range = 70.0,
            Zone = 1429,
            _index = 17,
        },
        {
            Waypoint = 176,
            Note = { "Kill Hogger. Loot him for his Claw", "Hogger can spawn in multiple locations", "Cast `Fear` on Hogger continously and use your regular DoTs to kill him", "This quest is difficult. Find a group for him if needed. Skip this step if you're unable to find a group or solo him" },
            Class = "WARLOCK",
            Coord = { x = 598.29, y = -9946.33 },
            NonSkippableWaypoint = true,
            Race = "Gnome",
            Range = 70.0,
            Zone = 1429,
            _index = 18,
        },
        {
            Waypoint = 176,
            Note = { "Kill Hogger. Loot him for his Claw", "Hogger can spawn in multiple locations", "Cast `Fear` on Hogger continously and use your regular DoTs to kill him", "This quest is difficult. Find a group for him if needed. Skip this step if you're unable to find a group or solo him" },
            Class = "WARLOCK",
            Coord = { x = 629.53, y = -10020.39 },
            NonSkippableWaypoint = true,
            Race = "Gnome",
            Range = 70.0,
            Zone = 1429,
            _index = 19,
        },
        {
            Waypoint = 176,
            Note = { "Kill Hogger. Loot him for his Claw", "Hogger can spawn in multiple locations", "Cast `Fear` on Hogger continously and use your regular DoTs to kill him", "This quest is difficult. Find a group for him if needed. Skip this step if you're unable to find a group or solo him" },
            Class = "WARLOCK",
            Coord = { x = 660.77, y = -10085.2 },
            NonSkippableWaypoint = true,
            Race = "Gnome",
            Range = 70.0,
            Zone = 1429,
            _index = 20,
        },
        {
            Waypoint = 176,
            Note = { "Kill Hogger. Loot him for his Claw", "Hogger can spawn in multiple locations", "Cast `Fear` on Hogger continously and use your regular DoTs to kill him", "This quest is difficult. Find a group for him if needed. Skip this step if you're unable to find a group or solo him" },
            Class = "WARLOCK",
            Coord = { x = 598.29, y = -10112.98 },
            NonSkippableWaypoint = true,
            Race = "Gnome",
            Range = 70.0,
            Zone = 1429,
            _index = 21,
        },
        {
            Waypoint = 176,
            Note = { "Kill Hogger. Loot him for his Claw", "Hogger can spawn in multiple locations", "Cast `Fear` on Hogger continously and use your regular DoTs to kill him", "This quest is difficult. Find a group for him if needed. Skip this step if you're unable to find a group or solo him" },
            Class = "WARLOCK",
            Coord = { x = 598.29, y = -9946.33 },
            NonSkippableWaypoint = true,
            Race = "Gnome",
            Range = 70.0,
            Zone = 1429,
            _index = 22,
        },
        {
            Waypoint = 176,
            Note = { "Kill Hogger. Loot him for his Claw", "Hogger can spawn in multiple locations", "Cast `Fear` on Hogger continously and use your regular DoTs to kill him", "This quest is difficult. Find a group for him if needed. Skip this step if you're unable to find a group or solo him" },
            Class = "WARLOCK",
            Coord = { x = 629.53, y = -10020.39 },
            NonSkippableWaypoint = true,
            Race = "Gnome",
            Range = 70.0,
            Zone = 1429,
            _index = 23,
        },
        {
            Waypoint = 176,
            Note = { "Kill Hogger. Loot him for his Claw", "Hogger can spawn in multiple locations", "Cast `Fear` on Hogger continously and use your regular DoTs to kill him", "This quest is difficult. Find a group for him if needed. Skip this step if you're unable to find a group or solo him" },
            Class = "WARLOCK",
            Coord = { x = 660.77, y = -10085.2 },
            NonSkippableWaypoint = true,
            Race = "Gnome",
            Range = 70.0,
            Zone = 1429,
            _index = 24,
        },
        {
            Waypoint = 176,
            Note = { "Kill Hogger. Loot him for his Claw", "Hogger can spawn in multiple locations", "Cast `Fear` on Hogger continously and use your regular DoTs to kill him", "This quest is difficult. Find a group for him if needed. Skip this step if you're unable to find a group or solo him" },
            Class = "WARLOCK",
            Coord = { x = 598.29, y = -10112.98 },
            NonSkippableWaypoint = true,
            Race = "Gnome",
            Range = 70.0,
            Zone = 1429,
            _index = 25,
        },
        {
            Qpart = { [176] = { 1 } },
            Note = { "Hogger can spawn in multiple locations", "Cast `Fear` on Hogger continously and use your regular DoTs to kill him", "This quest is difficult. Find a group for him if needed. Skip this step if you're unable to find a group or solo him" },
            Class = "WARLOCK",
            Coord = { x = 636.47, y = -10112.98 },
            Race = "Gnome",
            Range = 30,
            Zone = 1429,
            _index = 26,
        },
        {
            PickUp = { 88 },
            Coord = { x = 332.43, y = -9895.01 },
            Zone = 1429,
            _index = 27,
        },
        {
            Waypoint = 35,
            Note = { "Travel east to Guard Thomas" },
            Coord = { x = -1032.06, y = -9610.23 },
            NonSkippableWaypoint = true,
            Range = 30.0,
            Zone = 1429,
            _index = 28,
        },
        {
            Done = { 35 },
            Coord = { x = -1032.06, y = -9610.23 },
            Zone = 1429,
            _index = 29,
        },
        {
            PickUp = { 37, 52 },
            Coord = { x = -1032.06, y = -9610.23 },
            Zone = 1429,
            _index = 30,
        },
        {
            Done = { 37 },
            Note = { "Click A half-eaten body on the ground" },
            Coord = { x = -986.35, y = -9336.06 },
            Fillers = { [52] = { 1, 2 } },
            Zone = 1429,
            _index = 31,
        },
        {
            PickUp = { 45 },
            Note = { "Click A half-eaten body on the ground" },
            Coord = { x = -986.35, y = -9336.06 },
            Fillers = { [52] = { 1, 2 } },
            Zone = 1429,
            _index = 32,
        },
        {
            PickUp = { 5545 },
            Coord = { x = -1289.22, y = -9469.8 },
            Fillers = { [52] = { 1, 2 } },
            Zone = 1429,
            _index = 33,
        },
        {
            Done = { 45 },
            Note = { "Click Rolf's corpse on the ground", "Be careful as nearby Murlocs may aggro once you click Rolf's corpse", "Murloc Foragers will cast `Drink Minor Potion` which heals themselves for 61-68" },
            Coord = { x = -1234.31, y = -9224.18 },
            Fillers = { [52] = { 1, 2 }, [5545] = { 1 } },
            Zone = 1429,
            _index = 34,
        },
        {
            PickUp = { 71 },
            Note = { "Click Rolf's corpse on the ground", "Be careful as nearby Murlocs may aggro once you click Rolf's corpse", "Murloc Foragers will cast `Drink Minor Potion` which heals themselves for 61-68" },
            Coord = { x = -1234.31, y = -9224.18 },
            Fillers = { [52] = { 1, 2 }, [5545] = { 1 } },
            Zone = 1429,
            _index = 35,
        },
        {
            Qpart = { [5545] = { 1 } },
            Note = { "Loot the Bundles of Wood on the ground at the base of the trees" },
            Coord = { x = -1296.085, y = -9268.27 },
            Fillers = { [52] = { 1, 2 } },
            Range = 176,
            Zone = 1429,
            _index = 36,
        },
        {
            Done = { 5545 },
            Coord = { x = -1289.22, y = -9469.8 },
            Fillers = { [52] = { 1, 2 } },
            Zone = 1429,
            _index = 37,
        },
        {
            PickUp = { 91733 },
            Coord = { x = -1119.7708, y = -9603.7687 },
            Fillers = { [52] = { 1, 2 } },
            Zone = 1429,
            _index = 38,
        },
        {
            Qpart = { [91733] = { 2 } },
            Note = { "Loot the Waterlogged Saw on the ground" },
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1429, 74.3, 76.4),
            Fillers = { [52] = { 1, 2 } },
            Zone = 1429,
            _index = 39,
        },
        {
            Qpart = { [91733] = { 1 } },
            Note = { "Loot the Waterlogged Axe on the ground" },
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1429, 76.7, 82.5),
            Fillers = { [52] = { 1, 2 } },
            Zone = 1429,
            _index = 40,
        },
        {
            Qpart = { [91733] = { 3 } },
            Note = { "Loot the Waterlogged Toolbox on the ground" },
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1429, 77.3, 86.8),
            Fillers = { [52] = { 1, 2 } },
            Zone = 1429,
            _index = 41,
        },
        {
            DropQuest = 91740,
            DroppableQuest = { MobId = 248278, Qid = 91740, Text = "Croaky" },
            Note = { "He is a level 11 elite. Skip this step if you are unable to kill him" },
            Coord = { x = -1119.8, y = -9931.3 },
            Zone = 1429,
            _index = 42,
        },
        {
            Qpart = { [52] = { 1, 2 } },
            Coord = APR.worldCoordinateConverter:ConvertMapCoordinate(1429, 82.282, 71.543),
            Range = 30,
            Zone = 1429,
            _index = 43,
        },
        {
            Qpart = { [1688] = { 1 } },
            Note = { "Focus on killing Surena Caledon very quickly", "Cast `Fear` on Morgan the Collector continously" },
            Class = "WARLOCK",
            Coord = { x = -932.35, y = -9806.53 },
            IsQuestOnQuest = 147,
            Race = "Gnome",
            Range = 30,
            Zone = 1429,
            _index = 44,
        },
        {
            Qpart = { [147] = { 1 } },
            Note = { "Focus on killing Surena Caledon very quickly", "Cast `Fear` on Morgan the Collector continously" },
            Class = "WARLOCK",
            Coord = { x = -932.35, y = -9806.53 },
            Race = "Gnome",
            Range = 30,
            Zone = 1429,
            _index = 45,
        },
        {
            Qpart = { [1688] = { 1 } },
            Note = { "Focus on killing Surena Caledon very quickly", "Cast `Fear` on Morgan the Collector continously" },
            Class = "WARLOCK",
            Coord = { x = -932.35, y = -9806.53 },
            Race = "Gnome",
            Range = 10,
            Zone = 1429,
            _index = 46,
        },
        {
            Qpart = { [88] = { 1 } },
            Note = { "Princess will aggro with both of her Porcine Entourage", "Princess will also cast `Rushing Charge` which deals heavy damage", "Pool 100 Rage before you engage Princess", "Be ready to use a `Lesser Healing Potion`" },
            Class = "WARRIOR",
            Coord = { x = -869.87, y = -9768.1 },
            Range = 10,
            Zone = 1429,
            _index = 47,
        },
        {
            Qpart = { [88] = { 1 } },
            Note = { "Princess will aggro with both of her Porcine Entourage", "Princess will also cast `Rushing Charge` which deals heavy damage", "Be sure `Evasion` is ready. If you're struggling, you can use the Fence with Throwing Weapons to abuse pathing and buy time", "Be ready to use a `Lesser Healing Potion`" },
            Class = "ROGUE",
            Coord = { x = -869.87, y = -9768.1 },
            Range = 10,
            Zone = 1429,
            _index = 48,
        },
        {
            Qpart = { [88] = { 1 } },
            Note = { "Princess will aggro with both of her Porcine Entourage", "Princess will also cast `Rushing Charge` which deals heavy damage", "Be ready to use a `Lesser Healing Potion`" },
            Class = { "MAGE", "PALADIN", "PRIEST", "SHAMAN", "WARLOCK" },
            Coord = { x = -869.87, y = -9768.1 },
            Range = 10,
            Zone = 1429,
            _index = 49,
        },
        {
            Done = { 52, 71 },
            Coord = { x = -1032.06, y = -9610.23 },
            MinLevel = 9,
            Zone = 1429,
            _index = 50,
        },
        {
            PickUp = { 39, 109 },
            Coord = { x = -1032.06, y = -9610.23 },
            MinLevel = 9,
            Zone = 1429,
            _index = 51,
        },
        {
            Done = { 91733 },
            Coord = { x = -1119.7708, y = -9603.7687 },
            Zone = 1429,
            _index = 52,
        },
        {
            Note = { "Travel to Ridgepoint Tower" },
            _index = 53,
        },
        {
            Done = { 91740 },
            Coord = { x = -1406.2, y = -9775.5 },
            RaidIcon = 248277,
            Zone = 1429,
            _index = 54,
        },
        {
            Waypoint = 244,
            Coord = { x = -1948.56, y = -9582.75 },
            NonSkippableWaypoint = true,
            Range = 5,
            Zone = 1433,
            _index = 55,
        },
        {
            PickUp = { 244 },
            Coord = { x = -1906.4, y = -9606.8 },
            Zone = 1433,
            _index = 56,
        },
        {
            Done = { 244 },
            Note = { "Be careful of high level mobs en route" },
            Coord = { x = -2238.0, y = -9443.69 },
            Zone = 1433,
            _index = 57,
        },
        {
            Note = { "Fly to Stormwind" },
            GetFP = 5,
            Coord = { x = -2234.9, y = -9435.3 },
            Zone = 1433,
            _index = 58,
        },
        {
            Note = { "Get the Redridge Mountains flight path" },
            UseFlightPath = 39,
            Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "WARRIOR" },
            Coord = { x = -2234.9, y = -9435.3 },
            NodeID = 2,
            Zone = 1433,
            _index = 59,
        },
        {
            Note = { "Get the Redridge Mountains flight path" },
            UseFlightPath = 1688,
            Class = "WARLOCK",
            Coord = { x = -2234.9, y = -9435.3 },
            NodeID = 2,
            Zone = 1433,
            _index = 60,
        },
        {
            Note = { "If you don't want to or can't do this, skip this step", "`Stringy Vulture Meat`", "`Murloc Eye`", "`Goretusk Snout`", "`Okra`", "`Goretusk Liver`" },
            BuyMerchant = { { itemID = 729, quantity = 3, questID = 38 } },
            Coord = { x = 660.28, y = -8814.55 },
            ItemCount = { itemID = 729, count = 3, operator = "<" },
            Zone = 1453,
            _index = 61,
        },
        {
            Note = { "If you don't want to or can't do this, skip this step", "`Stringy Vulture Meat`", "`Murloc Eye`", "`Goretusk Snout`", "`Okra`", "`Goretusk Liver`" },
            BuyMerchant = { { itemID = 730, quantity = 3, questID = 38 } },
            Coord = { x = 660.28, y = -8814.55 },
            ItemCount = { itemID = 730, count = 3, operator = "<" },
            Zone = 1453,
            _index = 62,
        },
        {
            Note = { "If you don't want to or can't do this, skip this step", "`Stringy Vulture Meat`", "`Murloc Eye`", "`Goretusk Snout`", "`Okra`", "`Goretusk Liver`" },
            BuyMerchant = { { itemID = 731, quantity = 3, questID = 38 } },
            Coord = { x = 660.28, y = -8814.55 },
            ItemCount = { itemID = 731, count = 3, operator = "<" },
            Zone = 1453,
            _index = 63,
        },
        {
            Note = { "If you don't want to or can't do this, skip this step", "`Stringy Vulture Meat`", "`Murloc Eye`", "`Goretusk Snout`", "`Okra`", "`Goretusk Liver`" },
            BuyMerchant = { { itemID = 732, quantity = 3, questID = 38 } },
            Coord = { x = 660.28, y = -8814.55 },
            ItemCount = { itemID = 732, count = 3, operator = "<" },
            Zone = 1453,
            _index = 64,
        },
        {
            Note = { "If you don't want to or can't do this, skip this step", "`Stringy Vulture Meat`", "`Murloc Eye`", "`Goretusk Snout`", "`Okra`", "`Goretusk Liver`" },
            BuyMerchant = { { itemID = 723, quantity = 8, questID = 22 } },
            Coord = { x = 660.28, y = -8814.55 },
            ItemCount = { itemID = 723, count = 8, operator = "<" },
            Zone = 1453,
            _index = 65,
        },
        {
            Waypoint = 1688,
            Note = { "Travel to The Slaughtered Lamb and go downstairs" },
            Class = "WARLOCK",
            Coord = { x = 988.44, y = -8942.15 },
            NonSkippableWaypoint = true,
            Race = "Gnome",
            Range = 20.0,
            Zone = 1453,
            _index = 66,
        },
        {
            Waypoint = 1688,
            Note = { "Travel to The Slaughtered Lamb and go downstairs" },
            Class = "WARLOCK",
            Coord = { x = 1015.33, y = -8978.9 },
            NonSkippableWaypoint = true,
            Race = "Gnome",
            Range = 15.0,
            Zone = 1453,
            _index = 67,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "WARLOCK",
            Coord = { x = 1029.89, y = -8971.06 },
            MinLevel = 1,
            Race = "Gnome",
            Zone = 1453,
            _index = 68,
        },
        {
            Done = { 1688 },
            Class = "WARLOCK",
            Coord = { x = 1041.54, y = -8983.29 },
            Race = "Gnome",
            Zone = 1453,
            _index = 69,
        },
        {
            PickUp = { 1689 },
            Class = "WARLOCK",
            Coord = { x = 1041.54, y = -8983.29 },
            Race = "Gnome",
            Zone = 1453,
            _index = 70,
        },
        {
            Waypoint = 1689,
            Note = { "Travel to the bottom of The Slaughtered Lamb", "Use the `Bloodstone Choker` to call forth a Summoned Voidwalker" },
            Class = "WARLOCK",
            Coord = { x = 1042.22, y = -9002.21 },
            NonSkippableWaypoint = true,
            Race = "Gnome",
            Range = 18.0,
            Zone = 1453,
            _index = 71,
        },
        {
            Waypoint = 1689,
            Note = { "Travel to the bottom of The Slaughtered Lamb", "Use the `Bloodstone Choker` to call forth a Summoned Voidwalker" },
            Class = "WARLOCK",
            Coord = { x = 1069.1, y = -8991.45 },
            NonSkippableWaypoint = true,
            Race = "Gnome",
            Range = 18.0,
            Zone = 1453,
            _index = 72,
        },
        {
            Waypoint = 1689,
            Note = { "Travel to the bottom of The Slaughtered Lamb", "Use the `Bloodstone Choker` to call forth a Summoned Voidwalker" },
            Class = "WARLOCK",
            Coord = { x = 1027.43, y = -8991.45 },
            NonSkippableWaypoint = true,
            Race = "Gnome",
            Range = 18.0,
            Zone = 1453,
            _index = 73,
        },
        {
            Note = { "Travel to the bottom of The Slaughtered Lamb", "Use the `Bloodstone Choker` to call forth a Summoned Voidwalker" },
            Button = { ["1689-1"] = 6928 },
            Class = "WARLOCK",
            Coord = { x = 1042.83, y = -8972.68 },
            Race = "Gnome",
            SpellButton = { ["1689-1"] = 7728 },
            Zone = 1453,
            _index = 74,
        },
        {
            Qpart = { [1689] = { 1 } },
            Button = { ["1689-1"] = 6928 },
            Class = "WARLOCK",
            Coord = { x = 1042.83, y = -8972.68 },
            Race = "Gnome",
            Range = 10,
            Zone = 1453,
            _index = 75,
        },
        {
            Note = { "Start casting `Life Tap` on your way back up to Gakin the Darkbinder as you will do a deathskip momentarily" },
            Class = "WARLOCK",
            Hardcore = false,
            Race = "Gnome",
            _index = 76,
        },
        {
            Done = { 1689 },
            Class = "WARLOCK",
            Coord = { x = 1041.54, y = -8983.29 },
            Race = "Gnome",
            Zone = 1453,
            _index = 77,
        },
        {
            Note = { "Die and respawn at the Spirit Healer by using `Life Tap` and standing on the Bonfire next to you" },
            DeathSkip = true,
            Class = "WARLOCK",
            Hardcore = false,
            Race = "Gnome",
            _index = 78,
        },
        {
            Waypoint = 39,
            Note = { "Exit Stormwind. Travel to Goldshire" },
            Class = { "MAGE", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "WARRIOR" },
            Coord = { x = 74.02, y = -9465.52 },
            NonSkippableWaypoint = true,
            Range = 5,
            Zone = 1429,
            _index = 79,
        },
        {
            Waypoint = 147,
            Note = { "Exit Stormwind. Travel to Goldshire" },
            Class = "WARLOCK",
            Coord = { x = 74.02, y = -9465.52 },
            NonSkippableWaypoint = true,
            Range = 5,
            Zone = 1429,
            _index = 80,
        },
        {
            Done = { 147 },
            Class = "WARLOCK",
            Coord = { x = 74.02, y = -9465.52 },
            Race = "Gnome",
            Zone = 1429,
            _index = 81,
        },
        {
            Done = { 39 },
            Class = "WARLOCK",
            Coord = { x = 74.02, y = -9465.52 },
            IsQuestOnQuest = 147,
            Race = "Gnome",
            Zone = 1429,
            _index = 82,
        },
        {
            Done = { 39 },
            Coord = { x = 74.02, y = -9465.52 },
            Zone = 1429,
            _index = 83,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "WARRIOR",
            Coord = { x = 109.36, y = -9461.84 },
            MinLevel = 12,
            Zone = 1429,
            _index = 84,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "PALADIN",
            Coord = { x = 109.04, y = -9468.16 },
            MinLevel = 12,
            Race = "Dwarf",
            Zone = 1429,
            _index = 85,
        },
        {
            Waypoint = 88,
            Note = { "Travel upstairs in the Inn" },
            Class = { "MAGE", "PRIEST", "ROGUE" },
            Coord = { x = 12.52, y = -9479.85 },
            NonSkippableWaypoint = true,
            Range = 9.0,
            Zone = 1429,
            _index = 86,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "MAGE",
            Coord = { x = 34.28, y = -9471.61 },
            MinLevel = 12,
            Race = "Gnome",
            Zone = 1429,
            _index = 87,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "PRIEST",
            Coord = { x = 33.14, y = -9460.75 },
            MinLevel = 12,
            Zone = 1429,
            _index = 88,
        },
        {
            LearnSkill = { allAvailable = true },
            Class = "ROGUE",
            Coord = { x = 12.69, y = -9465.75 },
            MinLevel = 12,
            Zone = 1429,
            _index = 89,
        },
        {
            Done = { 88 },
            Coord = { x = 332.43, y = -9895.01 },
            Zone = 1429,
            _index = 90,
        },
        {
            Note = { "Kill Riverpaw Runts and Riverpaw Outrunners. Loot them for `Linen Cloth`", "Ensure you have 10 `Linen Cloth` for your upcoming Paladin class quest" },
            LootItems = { { itemID = 2589, quantity = 10, questID = 1648 } },
            Class = "PALADIN",
            Coord = { x = 629.53, y = -10029.65 },
            Race = "Dwarf",
            Range = 159,
            Zone = 1429,
            _index = 91,
        },
        {
            Waypoint = 184,
            Coord = { x = 918.42, y = -9851.5 },
            NonSkippableWaypoint = true,
            Range = 5,
            Zone = 1436,
            _index = 92,
        },
        {
            Done = { 184 },
            Coord = { x = 918.42, y = -9851.5 },
            Zone = 1436,
            _index = 93,
        },
        {
            Waypoint = 64,
            Coord = { x = 918.42, y = -9851.5 },
            NonSkippableWaypoint = true,
            Range = 5,
            Zone = 1436,
            _index = 94,
        },
        {
            PickUp = { 64, 151, 36 },
            Coord = { x = 919.47, y = -9853.13 },
            Zone = 1436,
            _index = 95,
        },
        {
            PickUp = { 9 },
            Coord = { x = 1055.27, y = -10128.7 },
            Zone = 1436,
            _index = 96,
        },
        {
            Done = { 36 },
            Coord = { x = 1042.67, y = -10111.67 },
            Zone = 1436,
            _index = 97,
        },
        {
            PickUp = { 38, 22 },
            Coord = { x = 1042.67, y = -10111.67 },
            Zone = 1436,
            _index = 98,
        },
        {
            Qpart = { [38] = { 1 } },
            _index = 99,
        },
        {
            Done = { 38 },
            Coord = { x = 1042.67, y = -10111.67 },
            Zone = 1436,
            _index = 100,
        },
        {
            Qpart = { [22] = { 1 } },
            _index = 101,
        },
        {
            Done = { 22 },
            Coord = { x = 1042.67, y = -10111.67 },
            Zone = 1436,
            _index = 102,
        },
        {
            Note = { "Die and respawn at the Spirit Healer or run to Sentinel Hill" },
            DeathSkip = true,
            Hardcore = false,
            _index = 103,
        },
        {
            Done = { 109 },
            Coord = { x = 1045.12, y = -10508.8 },
            Zone = 1436,
            _index = 104,
        },
        {
            PickUp = { 12 },
            Coord = { x = 1045.12, y = -10508.8 },
            Zone = 1436,
            _index = 105,
        },
        {
            PickUp = { 102 },
            Coord = { x = 1041.97, y = -10511.13 },
            Zone = 1436,
            _index = 106,
        },
        {
            PickUp = { 153 },
            Coord = { x = 1126.67, y = -10636.67 },
            Zone = 1436,
            _index = 107,
        },
        {
            GetFP = 4,
            Coord = { x = 1037.42, y = -10628.27 },
            Zone = 1436,
            _index = 108,
        },
        {
            Note = { "Hearth to Ironforge", "Buy food/water if needed" },
            UseHS = 2999,
            Class = "PALADIN",
            ETA = 2.0,
            Race = "Dwarf",
            _index = 109,
        },
        {
            UseFlightPath = 2999,
            Class = "PALADIN",
            Coord = { x = 1037.42, y = -10628.27 },
            NodeID = 6,
            Race = "Dwarf",
            SkipInZones = { 1432, 1455 },
            Zone = 1436,
            _index = 110,
        },
        {
            Note = { "Hearth to Thelsamar", "Buy food if needed" },
            UseHS = 418,
            Class = { "ROGUE", "WARRIOR" },
            ETA = 2.0,
            SkipInZones = { 1432 },
            _index = 111,
        },
        {
            Note = { "Hearth to Thelsamar", "Buy food/water if needed" },
            UseHS = 418,
            Class = { "MAGE", "PRIEST", "SHAMAN", "WARLOCK" },
            ETA = 2.0,
            SkipInZones = { 1432 },
            _index = 112,
        },
        {
            UseFlightPath = 418,
            AnyOf = { { SkipInZones = { 1432, 1455 }, Race = "Dwarf", Class = { "PRIEST", "ROGUE", "SHAMAN", "WARRIOR" } }, { SkipInZones = { 1432, 1455 }, Race = "Gnome" } },
            Coord = { x = 1037.42, y = -10628.27 },
            NodeID = 8,
            Zone = 1436,
            _index = 113,
        },
        {
            RouteCompleted = true,
            _index = 114,
        },
    },
}
