name: "Bug Report"
description: Report a bug or an issue with Azeroth Pilot Reloaded.
title: "[ISSUE] - "
labels: 'bug'
body:
- type: markdown
  attributes:
    value: |
      Please [search for existing issues](https://github.com/Rycia/azeroth-pilot-reloaded/issues) before creating a new one.

- type: textarea
  attributes:
    label: Description
    description: What did you expect to happen and what happened instead?
  validations:
    required: true

- type: input
  attributes:
    label: APR Version
    description: |
      You can see the current version in the title bar of the options window (`/apr`), if the options do not open, check the CurseForge app or the `## Version:` field in the APR.toc file.
    placeholder: "APR 2.1.6"
  validations:
    required: true

- type: dropdown
  id: flavor
  attributes:
    label: World of Warcraft Flavor
    description: What version of World of Warcraft are are you running?
    options:
      - Retail (Default)
      - Beta (Dragonflight)
  validations:
    required: true

- type: checkboxes
  id: testing
  attributes:
    label: Tested with only APR
    description: Did you try having APR as the only enabled addon and everything else (especially something like ElvUI) disabled?
    options:
      - label: "Yes"
      - label: "No"
  validations:
    required: true

- type: textarea
  attributes:
    label: Lua Error
    description: |
      Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://www.curseforge.com/wow/addons/bugsack) & [BugGrabber](https://www.curseforge.com/wow/addons/bug-grabber), yes both are needed.
    render: true
  validations:
    required: false

- type: textarea
  attributes:
    label: Reproduction Steps
    description: Please list out the steps to reproduce your bug. Please verify that your reproduction steps are enough to reproduce the problem.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true

- type: input
  attributes:
    label: Last Good Version
    description: |
      Was it working in a previous version? If yes, which was the last good one?
    placeholder: "APR 2.1.0"
  validations:
    required: false

- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.
    placeholder: Attach directly via "copy & paste," do not link to other sites
  validations:
    required: false

- type: textarea
  attributes:
    label: Any additional information?
    description: |
      If you have additional information that does not match the other fields
    render: true
  validations:
    required: false

