name: CI

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.AZEROTH_PILOT_RELOADED }}

    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Install and run Luacheck
      #   uses: nebularg/actions-luacheck@v1
      #   with:
      #     args: "--no-color -q"

      - name: WoW Packager
        uses: BigWigsMods/packager@master
        with:
          args: -p 618667 -w 26457

