name: Update Version Dropdown

on:
  release:
    types: [published]

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests

      - name: Update bug-report.yml
        env:
          GITHUB_TOKEN: ${{ secrets.AZEROTH_PILOT_RELOADED }}
        run: python .github/scripts/update_bug_report_template.py

      - name: Commit files
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .github/ISSUE_TEMPLATE/bug-report.yml
          git commit -m "Update version options in bug-report template" || echo "No changes to commit"
          git push
